// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: artifact/v1/artifact.proto

package artifactv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRunArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunArtifactsRequest) Reset() {
	*x = ListRunArtifactsRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunArtifactsRequest) ProtoMessage() {}

func (x *ListRunArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListRunArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *ListRunArtifactsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListRunArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Artifact            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunArtifactsResponse) Reset() {
	*x = ListRunArtifactsResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunArtifactsResponse) ProtoMessage() {}

func (x *ListRunArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListRunArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *ListRunArtifactsResponse) GetItems() []*Artifact {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetArtifactDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactDownloadRequest) Reset() {
	*x = GetArtifactDownloadRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactDownloadRequest) ProtoMessage() {}

func (x *GetArtifactDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactDownloadRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactDownloadRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *GetArtifactDownloadRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type GetArtifactDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactDownloadResponse) Reset() {
	*x = GetArtifactDownloadResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactDownloadResponse) ProtoMessage() {}

func (x *GetArtifactDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactDownloadResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactDownloadResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *GetArtifactDownloadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetArtifactDownloadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Artifact) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Artifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Artifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Artifact) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Artifact) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Artifact) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_artifact_v1_artifact_proto protoreflect.FileDescriptor

const file_artifact_v1_artifact_proto_rawDesc = "" +
	"\n" +
	"\x1aartifact/v1/artifact.proto\x12\vartifact.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x17ListRunArtifactsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"G\n" +
	"\x18ListRunArtifactsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.artifact.v1.ArtifactR\x05items\"=\n" +
	"\x1aGetArtifactDownloadRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"j\n" +
	"\x1bGetArtifactDownloadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa7\x03\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.artifact.v1.Artifact.MetadataEntryR\bmetadata\x12>\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_expires_at2\xb1\x02\n" +
	"\x0fArtifactService\x12\x84\x01\n" +
	"\x10ListRunArtifacts\x12$.artifact.v1.ListRunArtifactsRequest\x1a%.artifact.v1.ListRunArtifactsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/runs/{run_id}/artifacts\x12\x96\x01\n" +
	"\x13GetArtifactDownload\x12'.artifact.v1.GetArtifactDownloadRequest\x1a(.artifact.v1.GetArtifactDownloadResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/artifacts/{artifact_id}/downloadB3Z1agent-platform/backend/api/artifact/v1;artifactv1b\x06proto3"

var (
	file_artifact_v1_artifact_proto_rawDescOnce sync.Once
	file_artifact_v1_artifact_proto_rawDescData []byte
)

func file_artifact_v1_artifact_proto_rawDescGZIP() []byte {
	file_artifact_v1_artifact_proto_rawDescOnce.Do(func() {
		file_artifact_v1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_v1_artifact_proto_rawDesc), len(file_artifact_v1_artifact_proto_rawDesc)))
	})
	return file_artifact_v1_artifact_proto_rawDescData
}

var file_artifact_v1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_artifact_v1_artifact_proto_goTypes = []any{
	(*ListRunArtifactsRequest)(nil),     // 0: artifact.v1.ListRunArtifactsRequest
	(*ListRunArtifactsResponse)(nil),    // 1: artifact.v1.ListRunArtifactsResponse
	(*GetArtifactDownloadRequest)(nil),  // 2: artifact.v1.GetArtifactDownloadRequest
	(*GetArtifactDownloadResponse)(nil), // 3: artifact.v1.GetArtifactDownloadResponse
	(*Artifact)(nil),                    // 4: artifact.v1.Artifact
	nil,                                 // 5: artifact.v1.Artifact.MetadataEntry
	(*timestamppb.Timestamp)(nil),       // 6: google.protobuf.Timestamp
}
var file_artifact_v1_artifact_proto_depIdxs = []int32{
	4, // 0: artifact.v1.ListRunArtifactsResponse.items:type_name -> artifact.v1.Artifact
	6, // 1: artifact.v1.GetArtifactDownloadResponse.expires_at:type_name -> google.protobuf.Timestamp
	5, // 2: artifact.v1.Artifact.metadata:type_name -> artifact.v1.Artifact.MetadataEntry
	6, // 3: artifact.v1.Artifact.expires_at:type_name -> google.protobuf.Timestamp
	6, // 4: artifact.v1.Artifact.created_at:type_name -> google.protobuf.Timestamp
	0, // 5: artifact.v1.ArtifactService.ListRunArtifacts:input_type -> artifact.v1.ListRunArtifactsRequest
	2, // 6: artifact.v1.ArtifactService.GetArtifactDownload:input_type -> artifact.v1.GetArtifactDownloadRequest
	1, // 7: artifact.v1.ArtifactService.ListRunArtifacts:output_type -> artifact.v1.ListRunArtifactsResponse
	3, // 8: artifact.v1.ArtifactService.GetArtifactDownload:output_type -> artifact.v1.GetArtifactDownloadResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_artifact_v1_artifact_proto_init() }
func file_artifact_v1_artifact_proto_init() {
	if File_artifact_v1_artifact_proto != nil {
		return
	}
	file_artifact_v1_artifact_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_v1_artifact_proto_rawDesc), len(file_artifact_v1_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifact_v1_artifact_proto_goTypes,
		DependencyIndexes: file_artifact_v1_artifact_proto_depIdxs,
		MessageInfos:      file_artifact_v1_artifact_proto_msgTypes,
	}.Build()
	File_artifact_v1_artifact_proto = out.File
	file_artifact_v1_artifact_proto_goTypes = nil
	file_artifact_v1_artifact_proto_depIdxs = nil
}
