// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtimecatalog/v1/runtime_catalog.proto

package runtimecatalogv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRuntimeImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimeImagesRequest) Reset() {
	*x = ListRuntimeImagesRequest{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimeImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimeImagesRequest) ProtoMessage() {}

func (x *ListRuntimeImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimeImagesRequest.ProtoReflect.Descriptor instead.
func (*ListRuntimeImagesRequest) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{0}
}

type ListRuntimeImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RuntimeImage        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimeImagesResponse) Reset() {
	*x = ListRuntimeImagesResponse{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimeImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimeImagesResponse) ProtoMessage() {}

func (x *ListRuntimeImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimeImagesResponse.ProtoReflect.Descriptor instead.
func (*ListRuntimeImagesResponse) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListRuntimeImagesResponse) GetItems() []*RuntimeImage {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRuntimeImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuntimeImageId string                 `protobuf:"bytes,1,opt,name=runtime_image_id,json=runtimeImageId,proto3" json:"runtime_image_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRuntimeImageRequest) Reset() {
	*x = GetRuntimeImageRequest{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeImageRequest) ProtoMessage() {}

func (x *GetRuntimeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeImageRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeImageRequest) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetRuntimeImageRequest) GetRuntimeImageId() string {
	if x != nil {
		return x.RuntimeImageId
	}
	return ""
}

type GetRuntimeImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeImage  *RuntimeImage          `protobuf:"bytes,1,opt,name=runtime_image,json=runtimeImage,proto3" json:"runtime_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeImageResponse) Reset() {
	*x = GetRuntimeImageResponse{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeImageResponse) ProtoMessage() {}

func (x *GetRuntimeImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeImageResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeImageResponse) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetRuntimeImageResponse) GetRuntimeImage() *RuntimeImage {
	if x != nil {
		return x.RuntimeImage
	}
	return nil
}

type RegisterRuntimeImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Runtime        string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	CliVersion     string                 `protobuf:"bytes,2,opt,name=cli_version,json=cliVersion,proto3" json:"cli_version,omitempty"`
	AdapterVersion string                 `protobuf:"bytes,3,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	ImageDigest    string                 `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	Capabilities   map[string]bool        `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRuntimeImageRequest) Reset() {
	*x = RegisterRuntimeImageRequest{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRuntimeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRuntimeImageRequest) ProtoMessage() {}

func (x *RegisterRuntimeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRuntimeImageRequest.ProtoReflect.Descriptor instead.
func (*RegisterRuntimeImageRequest) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRuntimeImageRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *RegisterRuntimeImageRequest) GetCliVersion() string {
	if x != nil {
		return x.CliVersion
	}
	return ""
}

func (x *RegisterRuntimeImageRequest) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

func (x *RegisterRuntimeImageRequest) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *RegisterRuntimeImageRequest) GetCapabilities() map[string]bool {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterRuntimeImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeImage  *RuntimeImage          `protobuf:"bytes,1,opt,name=runtime_image,json=runtimeImage,proto3" json:"runtime_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRuntimeImageResponse) Reset() {
	*x = RegisterRuntimeImageResponse{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRuntimeImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRuntimeImageResponse) ProtoMessage() {}

func (x *RegisterRuntimeImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRuntimeImageResponse.ProtoReflect.Descriptor instead.
func (*RegisterRuntimeImageResponse) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRuntimeImageResponse) GetRuntimeImage() *RuntimeImage {
	if x != nil {
		return x.RuntimeImage
	}
	return nil
}

type ChangeRuntimeImageStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuntimeImageId string                 `protobuf:"bytes,1,opt,name=runtime_image_id,json=runtimeImageId,proto3" json:"runtime_image_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BlockedReason  string                 `protobuf:"bytes,3,opt,name=blocked_reason,json=blockedReason,proto3" json:"blocked_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangeRuntimeImageStatusRequest) Reset() {
	*x = ChangeRuntimeImageStatusRequest{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRuntimeImageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRuntimeImageStatusRequest) ProtoMessage() {}

func (x *ChangeRuntimeImageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRuntimeImageStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeRuntimeImageStatusRequest) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeRuntimeImageStatusRequest) GetRuntimeImageId() string {
	if x != nil {
		return x.RuntimeImageId
	}
	return ""
}

func (x *ChangeRuntimeImageStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChangeRuntimeImageStatusRequest) GetBlockedReason() string {
	if x != nil {
		return x.BlockedReason
	}
	return ""
}

type ChangeRuntimeImageStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeImage  *RuntimeImage          `protobuf:"bytes,1,opt,name=runtime_image,json=runtimeImage,proto3" json:"runtime_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRuntimeImageStatusResponse) Reset() {
	*x = ChangeRuntimeImageStatusResponse{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRuntimeImageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRuntimeImageStatusResponse) ProtoMessage() {}

func (x *ChangeRuntimeImageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRuntimeImageStatusResponse.ProtoReflect.Descriptor instead.
func (*ChangeRuntimeImageStatusResponse) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeRuntimeImageStatusResponse) GetRuntimeImage() *RuntimeImage {
	if x != nil {
		return x.RuntimeImage
	}
	return nil
}

type RuntimeImage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Runtime        string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	CliVersion     string                 `protobuf:"bytes,3,opt,name=cli_version,json=cliVersion,proto3" json:"cli_version,omitempty"`
	AdapterVersion string                 `protobuf:"bytes,4,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	ImageDigest    string                 `protobuf:"bytes,5,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	Capabilities   map[string]bool        `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	BlockedReason  *string                `protobuf:"bytes,8,opt,name=blocked_reason,json=blockedReason,proto3,oneof" json:"blocked_reason,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version        int64                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeImage) Reset() {
	*x = RuntimeImage{}
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeImage) ProtoMessage() {}

func (x *RuntimeImage) ProtoReflect() protoreflect.Message {
	mi := &file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeImage.ProtoReflect.Descriptor instead.
func (*RuntimeImage) Descriptor() ([]byte, []int) {
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuntimeImage) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *RuntimeImage) GetCliVersion() string {
	if x != nil {
		return x.CliVersion
	}
	return ""
}

func (x *RuntimeImage) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

func (x *RuntimeImage) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *RuntimeImage) GetCapabilities() map[string]bool {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RuntimeImage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuntimeImage) GetBlockedReason() string {
	if x != nil && x.BlockedReason != nil {
		return *x.BlockedReason
	}
	return ""
}

func (x *RuntimeImage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RuntimeImage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RuntimeImage) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_runtimecatalog_v1_runtime_catalog_proto protoreflect.FileDescriptor

const file_runtimecatalog_v1_runtime_catalog_proto_rawDesc = "" +
	"\n" +
	"'runtimecatalog/v1/runtime_catalog.proto\x12\x11runtimecatalog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n" +
	"\x18ListRuntimeImagesRequest\"R\n" +
	"\x19ListRuntimeImagesResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.runtimecatalog.v1.RuntimeImageR\x05items\"B\n" +
	"\x16GetRuntimeImageRequest\x12(\n" +
	"\x10runtime_image_id\x18\x01 \x01(\tR\x0eruntimeImageId\"_\n" +
	"\x17GetRuntimeImageResponse\x12D\n" +
	"\rruntime_image\x18\x01 \x01(\v2\x1f.runtimecatalog.v1.RuntimeImageR\fruntimeImage\"\xcb\x02\n" +
	"\x1bRegisterRuntimeImageRequest\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x1f\n" +
	"\vcli_version\x18\x02 \x01(\tR\n" +
	"cliVersion\x12'\n" +
	"\x0fadapter_version\x18\x03 \x01(\tR\x0eadapterVersion\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x12d\n" +
	"\fcapabilities\x18\x05 \x03(\v2@.runtimecatalog.v1.RegisterRuntimeImageRequest.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"d\n" +
	"\x1cRegisterRuntimeImageResponse\x12D\n" +
	"\rruntime_image\x18\x01 \x01(\v2\x1f.runtimecatalog.v1.RuntimeImageR\fruntimeImage\"\x8a\x01\n" +
	"\x1fChangeRuntimeImageStatusRequest\x12(\n" +
	"\x10runtime_image_id\x18\x01 \x01(\tR\x0eruntimeImageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0eblocked_reason\x18\x03 \x01(\tR\rblockedReason\"h\n" +
	" ChangeRuntimeImageStatusResponse\x12D\n" +
	"\rruntime_image\x18\x01 \x01(\v2\x1f.runtimecatalog.v1.RuntimeImageR\fruntimeImage\"\xa4\x04\n" +
	"\fRuntimeImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12\x1f\n" +
	"\vcli_version\x18\x03 \x01(\tR\n" +
	"cliVersion\x12'\n" +
	"\x0fadapter_version\x18\x04 \x01(\tR\x0eadapterVersion\x12!\n" +
	"\fimage_digest\x18\x05 \x01(\tR\vimageDigest\x12U\n" +
	"\fcapabilities\x18\x06 \x03(\v21.runtimecatalog.v1.RuntimeImage.CapabilitiesEntryR\fcapabilities\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12*\n" +
	"\x0eblocked_reason\x18\b \x01(\tH\x00R\rblockedReason\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\v \x01(\x03R\aversion\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\x11\n" +
	"\x0f_blocked_reason2\xe7\x04\n" +
	"\x15RuntimeCatalogService\x12\x8a\x01\n" +
	"\x11ListRuntimeImages\x12+.runtimecatalog.v1.ListRuntimeImagesRequest\x1a,.runtimecatalog.v1.ListRuntimeImagesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/runtime-images\x12\x8c\x01\n" +
	"\x0fGetRuntimeImage\x12).runtimecatalog.v1.GetRuntimeImageRequest\x1a\x1f.runtimecatalog.v1.RuntimeImage\"-\x82\xd3\xe4\x93\x02'\x12%/v1/runtime-images/{runtime_image_id}\x12\x86\x01\n" +
	"\x14RegisterRuntimeImage\x12..runtimecatalog.v1.RegisterRuntimeImageRequest\x1a\x1f.runtimecatalog.v1.RuntimeImage\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/runtime-images\x12\xa8\x01\n" +
	"\x18ChangeRuntimeImageStatus\x122.runtimecatalog.v1.ChangeRuntimeImageStatusRequest\x1a\x1f.runtimecatalog.v1.RuntimeImage\"7\x82\xd3\xe4\x93\x021:\x01*2,/v1/runtime-images/{runtime_image_id}/statusB?Z=agent-platform/backend/api/runtimecatalog/v1;runtimecatalogv1b\x06proto3"

var (
	file_runtimecatalog_v1_runtime_catalog_proto_rawDescOnce sync.Once
	file_runtimecatalog_v1_runtime_catalog_proto_rawDescData []byte
)

func file_runtimecatalog_v1_runtime_catalog_proto_rawDescGZIP() []byte {
	file_runtimecatalog_v1_runtime_catalog_proto_rawDescOnce.Do(func() {
		file_runtimecatalog_v1_runtime_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtimecatalog_v1_runtime_catalog_proto_rawDesc), len(file_runtimecatalog_v1_runtime_catalog_proto_rawDesc)))
	})
	return file_runtimecatalog_v1_runtime_catalog_proto_rawDescData
}

var file_runtimecatalog_v1_runtime_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_runtimecatalog_v1_runtime_catalog_proto_goTypes = []any{
	(*ListRuntimeImagesRequest)(nil),         // 0: runtimecatalog.v1.ListRuntimeImagesRequest
	(*ListRuntimeImagesResponse)(nil),        // 1: runtimecatalog.v1.ListRuntimeImagesResponse
	(*GetRuntimeImageRequest)(nil),           // 2: runtimecatalog.v1.GetRuntimeImageRequest
	(*GetRuntimeImageResponse)(nil),          // 3: runtimecatalog.v1.GetRuntimeImageResponse
	(*RegisterRuntimeImageRequest)(nil),      // 4: runtimecatalog.v1.RegisterRuntimeImageRequest
	(*RegisterRuntimeImageResponse)(nil),     // 5: runtimecatalog.v1.RegisterRuntimeImageResponse
	(*ChangeRuntimeImageStatusRequest)(nil),  // 6: runtimecatalog.v1.ChangeRuntimeImageStatusRequest
	(*ChangeRuntimeImageStatusResponse)(nil), // 7: runtimecatalog.v1.ChangeRuntimeImageStatusResponse
	(*RuntimeImage)(nil),                     // 8: runtimecatalog.v1.RuntimeImage
	nil,                                      // 9: runtimecatalog.v1.RegisterRuntimeImageRequest.CapabilitiesEntry
	nil,                                      // 10: runtimecatalog.v1.RuntimeImage.CapabilitiesEntry
	(*timestamppb.Timestamp)(nil),            // 11: google.protobuf.Timestamp
}
var file_runtimecatalog_v1_runtime_catalog_proto_depIdxs = []int32{
	8,  // 0: runtimecatalog.v1.ListRuntimeImagesResponse.items:type_name -> runtimecatalog.v1.RuntimeImage
	8,  // 1: runtimecatalog.v1.GetRuntimeImageResponse.runtime_image:type_name -> runtimecatalog.v1.RuntimeImage
	9,  // 2: runtimecatalog.v1.RegisterRuntimeImageRequest.capabilities:type_name -> runtimecatalog.v1.RegisterRuntimeImageRequest.CapabilitiesEntry
	8,  // 3: runtimecatalog.v1.RegisterRuntimeImageResponse.runtime_image:type_name -> runtimecatalog.v1.RuntimeImage
	8,  // 4: runtimecatalog.v1.ChangeRuntimeImageStatusResponse.runtime_image:type_name -> runtimecatalog.v1.RuntimeImage
	10, // 5: runtimecatalog.v1.RuntimeImage.capabilities:type_name -> runtimecatalog.v1.RuntimeImage.CapabilitiesEntry
	11, // 6: runtimecatalog.v1.RuntimeImage.created_at:type_name -> google.protobuf.Timestamp
	11, // 7: runtimecatalog.v1.RuntimeImage.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: runtimecatalog.v1.RuntimeCatalogService.ListRuntimeImages:input_type -> runtimecatalog.v1.ListRuntimeImagesRequest
	2,  // 9: runtimecatalog.v1.RuntimeCatalogService.GetRuntimeImage:input_type -> runtimecatalog.v1.GetRuntimeImageRequest
	4,  // 10: runtimecatalog.v1.RuntimeCatalogService.RegisterRuntimeImage:input_type -> runtimecatalog.v1.RegisterRuntimeImageRequest
	6,  // 11: runtimecatalog.v1.RuntimeCatalogService.ChangeRuntimeImageStatus:input_type -> runtimecatalog.v1.ChangeRuntimeImageStatusRequest
	1,  // 12: runtimecatalog.v1.RuntimeCatalogService.ListRuntimeImages:output_type -> runtimecatalog.v1.ListRuntimeImagesResponse
	8,  // 13: runtimecatalog.v1.RuntimeCatalogService.GetRuntimeImage:output_type -> runtimecatalog.v1.RuntimeImage
	8,  // 14: runtimecatalog.v1.RuntimeCatalogService.RegisterRuntimeImage:output_type -> runtimecatalog.v1.RuntimeImage
	8,  // 15: runtimecatalog.v1.RuntimeCatalogService.ChangeRuntimeImageStatus:output_type -> runtimecatalog.v1.RuntimeImage
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_runtimecatalog_v1_runtime_catalog_proto_init() }
func file_runtimecatalog_v1_runtime_catalog_proto_init() {
	if File_runtimecatalog_v1_runtime_catalog_proto != nil {
		return
	}
	file_runtimecatalog_v1_runtime_catalog_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtimecatalog_v1_runtime_catalog_proto_rawDesc), len(file_runtimecatalog_v1_runtime_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtimecatalog_v1_runtime_catalog_proto_goTypes,
		DependencyIndexes: file_runtimecatalog_v1_runtime_catalog_proto_depIdxs,
		MessageInfos:      file_runtimecatalog_v1_runtime_catalog_proto_msgTypes,
	}.Build()
	File_runtimecatalog_v1_runtime_catalog_proto = out.File
	file_runtimecatalog_v1_runtime_catalog_proto_goTypes = nil
	file_runtimecatalog_v1_runtime_catalog_proto_depIdxs = nil
}
