/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListUsers"];
        put?: never;
        post: operations["AgentWorkspaceService_CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_SetUserEnabled"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_ResetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListExperts"];
        put?: never;
        post: operations["AgentWorkspaceService_CreateExpert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experts/{expert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AgentWorkspaceService_DeleteExpert"];
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_UpdateExpert"];
        trace?: never;
    };
    "/api/v1/extensions/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListMCPServers"];
        put?: never;
        post: operations["AgentWorkspaceService_CreateMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extensions/mcp/{mcp_server_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AgentWorkspaceService_DeleteMCPServer"];
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_UpdateMCPServer"];
        trace?: never;
    };
    "/api/v1/extensions/mcp/{mcp_server_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_TestMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extensions/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListSkills"];
        put?: never;
        post: operations["AgentWorkspaceService_CreateSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extensions/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AgentWorkspaceService_DeleteSkill"];
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_UpdateSkill"];
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_GetCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-provider-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListModelProviderConnections"];
        put?: never;
        post: operations["AgentWorkspaceService_CreateModelProviderConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-provider-connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AgentWorkspaceService_DeleteModelProviderConnection"];
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_UpdateModelProviderConnection"];
        trace?: never;
    };
    "/api/v1/model-provider-connections/{connection_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_CreateProviderModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-provider-connections/{connection_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_RefreshProviderModels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-provider-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListModelProviderPresets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime-engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListRuntimeEngines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListSessions"];
        put?: never;
        post: operations["AgentWorkspaceService_CreateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_GetSession"];
        put?: never;
        post?: never;
        delete: operations["AgentWorkspaceService_DeleteSession"];
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_UpdateSession"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/archived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_SetSessionArchived"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListSessionMessages"];
        put?: never;
        post: operations["AgentWorkspaceService_SendSessionMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages/{message_id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_CancelSessionMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages/{message_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_RetrySessionMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_GetSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_UpdateSettings"];
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListWorkflows"];
        put?: never;
        post: operations["AgentWorkspaceService_CreateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_GetWorkflow"];
        put?: never;
        post?: never;
        delete: operations["AgentWorkspaceService_DeleteWorkflow"];
        options?: never;
        head?: never;
        patch: operations["AgentWorkspaceService_UpdateWorkflow"];
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/api-credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_GenerateWorkflowCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/artifacts/{artifact_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_GetArtifactDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListRuns"];
        put?: never;
        post: operations["AgentWorkspaceService_RunWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_GetRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/runs/{run_id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_CancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/runs/{run_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_RerunWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_ListWorkspaceEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/workspace/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_ClearWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/workspace/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_CloneWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/workspace/directories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_CreateWorkspaceDirectory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/workspace/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentWorkspaceService_GetWorkspaceFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/workspace/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentWorkspaceService_UploadWorkspaceFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthService_Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthService_Ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentWorkspaceServiceCancelRunBody: Record<string, never>;
        AgentWorkspaceServiceCancelSessionMessageBody: Record<string, never>;
        AgentWorkspaceServiceClearWorkspaceBody: {
            confirmation?: string;
        };
        AgentWorkspaceServiceCloneWorkspaceBody: {
            url?: string;
            branch?: string;
            ssh_private_key?: string;
        };
        AgentWorkspaceServiceCreateProviderModelBody: {
            model_id?: string;
            display_name?: string;
            model_type?: string;
        };
        AgentWorkspaceServiceCreateWorkspaceDirectoryBody: {
            path?: string;
        };
        AgentWorkspaceServiceGenerateWorkflowCredentialBody: Record<string, never>;
        AgentWorkspaceServiceRefreshProviderModelsBody: Record<string, never>;
        AgentWorkspaceServiceRerunWorkflowBody: Record<string, never>;
        AgentWorkspaceServiceResetUserPasswordBody: Record<string, never>;
        AgentWorkspaceServiceRetrySessionMessageBody: Record<string, never>;
        AgentWorkspaceServiceRunWorkflowBody: {
            text_input?: string;
            json_input?: Record<string, never>;
        };
        AgentWorkspaceServiceSendSessionMessageBody: {
            content?: string;
            provider_model_id?: string;
        };
        AgentWorkspaceServiceSetSessionArchivedBody: {
            archived?: boolean;
            /** Format: int64 */
            expected_version?: number;
        };
        AgentWorkspaceServiceSetUserEnabledBody: {
            enabled?: boolean;
            /** Format: int64 */
            expected_version?: number;
        };
        AgentWorkspaceServiceTestMCPServerBody: Record<string, never>;
        AgentWorkspaceServiceUpdateExpertBody: {
            expert?: components["schemas"]["v1ExpertInput"];
            /** Format: int64 */
            expected_version?: number;
        };
        AgentWorkspaceServiceUpdateMCPServerBody: {
            mcp_server?: components["schemas"]["v1MCPServerInput"];
            /** Format: int64 */
            expected_version?: number;
        };
        AgentWorkspaceServiceUpdateModelProviderConnectionBody: {
            name?: string;
            endpoint?: string;
            protocols?: string[];
            replacement_api_key?: string;
            /** Format: int64 */
            expected_version?: number;
        };
        AgentWorkspaceServiceUpdateSessionBody: {
            title?: string;
            /** Format: int64 */
            expected_version?: number;
        };
        AgentWorkspaceServiceUpdateSkillBody: {
            git_ref?: string;
            /** Format: byte */
            archive?: string;
            /** Format: int64 */
            expected_version?: number;
        };
        AgentWorkspaceServiceUpdateWorkflowBody: {
            workflow?: components["schemas"]["v1WorkflowInput"];
            /** Format: int64 */
            expected_version?: number;
        };
        AgentWorkspaceServiceUploadWorkspaceFileBody: {
            path?: string;
            /** Format: byte */
            content?: string;
        };
        protobufAny: {
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description `NullValue` is a singleton enumeration to represent the null value for the
         *     `Value` type union.
         *
         *     The JSON representation for `NullValue` is JSON `null`.
         *
         *      - NULL_VALUE: Null value.
         * @default NULL_VALUE
         * @enum {string}
         */
        protobufNullValue: "NULL_VALUE";
        rpcStatus: {
            /** Format: int32 */
            code?: number;
            message?: string;
            details?: components["schemas"]["protobufAny"][];
        };
        v1Artifact: {
            id?: string;
            run_id?: string;
            kind?: string;
            name?: string;
            path?: string;
            /** Format: int64 */
            size?: number;
            sha256?: string;
            text_preview?: string;
            expired?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        v1ArtifactDownload: {
            url?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        v1CreateExpertRequest: {
            expert?: components["schemas"]["v1ExpertInput"];
        };
        v1CreateMCPServerRequest: {
            mcp_server?: components["schemas"]["v1MCPServerInput"];
        };
        v1CreateModelProviderConnectionRequest: {
            name?: string;
            provider_type?: string;
            endpoint?: string;
            protocols?: string[];
            api_key?: string;
        };
        v1CreateSessionRequest: {
            expert_id?: string;
        };
        v1CreateSkillRequest: {
            name?: string;
            source?: string;
            git_url?: string;
            git_ref?: string;
            /** Format: byte */
            archive?: string;
        };
        v1CreateUserRequest: {
            username?: string;
            display_name?: string;
            email?: string;
        };
        v1CreateUserResponse: {
            user?: components["schemas"]["v1UserAccount"];
            temporary_password?: string;
        };
        v1CreateWorkflowRequest: {
            workflow?: components["schemas"]["v1WorkflowInput"];
        };
        v1CurrentUser: {
            id?: string;
            username?: string;
            email?: string;
            display_name?: string;
            administrator?: boolean;
            settings_ready?: boolean;
        };
        v1DeleteResponse: {
            deleted?: boolean;
        };
        v1EnvironmentVariable: {
            name?: string;
            value?: string;
            secret?: boolean;
            configured?: boolean;
        };
        v1Expert: {
            id?: string;
            name?: string;
            description?: string;
            mcp_server_ids?: string[];
            skill_ids?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int64 */
            version?: number;
        };
        v1ExpertInput: {
            name?: string;
            description?: string;
            mcp_server_ids?: string[];
            skill_ids?: string[];
        };
        v1GitSource: {
            url?: string;
            branch?: string;
            private_ssh?: boolean;
            credential_configured?: boolean;
        };
        v1HealthResponse: {
            status?: string;
        };
        v1ListArtifactsResponse: {
            items?: components["schemas"]["v1Artifact"][];
        };
        v1ListExpertsResponse: {
            items?: components["schemas"]["v1Expert"][];
        };
        v1ListMCPServersResponse: {
            items?: components["schemas"]["v1MCPServer"][];
        };
        v1ListModelProviderConnectionsResponse: {
            items?: components["schemas"]["v1ModelProviderConnection"][];
        };
        v1ListModelProviderPresetsResponse: {
            items?: components["schemas"]["v1ModelProviderPreset"][];
        };
        v1ListRunsResponse: {
            items?: components["schemas"]["v1Run"][];
        };
        v1ListRuntimeEnginesResponse: {
            items?: components["schemas"]["v1RuntimeEngineStatus"][];
        };
        v1ListSessionMessagesResponse: {
            items?: components["schemas"]["v1SessionMessage"][];
        };
        v1ListSessionsResponse: {
            items?: components["schemas"]["v1Session"][];
        };
        v1ListSkillsResponse: {
            items?: components["schemas"]["v1Skill"][];
        };
        v1ListUsersResponse: {
            items?: components["schemas"]["v1UserAccount"][];
        };
        v1ListWorkflowsResponse: {
            items?: components["schemas"]["v1Workflow"][];
        };
        v1ListWorkspaceEntriesResponse: {
            items?: components["schemas"]["v1WorkspaceEntry"][];
            /** Format: int64 */
            used_bytes?: number;
            /** Format: int64 */
            limit_bytes?: number;
        };
        v1MCPServer: {
            id?: string;
            name?: string;
            transport?: string;
            url?: string;
            runner?: string;
            package?: string;
            package_version?: string;
            arguments?: string[];
            environment?: components["schemas"]["v1EnvironmentVariable"][];
            tested?: boolean;
            test_error?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int64 */
            version?: number;
            test_pending?: boolean;
        };
        v1MCPServerInput: {
            name?: string;
            transport?: string;
            url?: string;
            runner?: string;
            package?: string;
            package_version?: string;
            arguments?: string[];
            environment?: components["schemas"]["v1EnvironmentVariable"][];
        };
        v1ModelProviderConnection: {
            id?: string;
            name?: string;
            provider_type?: string;
            endpoint?: string;
            protocols?: string[];
            api_key_configured?: boolean;
            verification_status?: string;
            verification_error?: string;
            custom_endpoint?: boolean;
            /** Format: date-time */
            last_synced_at?: string;
            last_sync_error?: string;
            models?: components["schemas"]["v1ProviderModel"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int64 */
            version?: number;
        };
        v1ModelProviderPreset: {
            provider_type?: string;
            display_name?: string;
            official_endpoint?: string;
            protocols?: string[];
            dynamic_discovery?: boolean;
        };
        v1PersonalSettings: {
            personality?: string;
            personality_instructions?: string;
            runtime_model_defaults?: components["schemas"]["v1RuntimeModelDefault"][];
            default_runtime_engine?: string;
            language?: string;
            timezone?: string;
            /** Format: int64 */
            version?: number;
        };
        v1ProviderModel: {
            id?: string;
            connection_id?: string;
            model_id?: string;
            display_name?: string;
            model_type?: string;
            available?: boolean;
            manually_added?: boolean;
            compatibility?: components["schemas"]["v1RuntimeModelCompatibility"][];
        };
        v1ReadyResponse: {
            status?: string;
        };
        v1ResetUserPasswordResponse: {
            temporary_password?: string;
        };
        v1ResponseSnapshot: {
            provider_model_id?: string;
            connection_id?: string;
            connection_name?: string;
            provider_type?: string;
            model_id?: string;
            model_name?: string;
            endpoint?: string;
            protocols?: string[];
            runtime_engine?: string;
            compatibility?: string;
            /** Format: int64 */
            connection_version?: number;
        };
        v1Run: {
            id?: string;
            workflow_id?: string;
            workflow_name?: string;
            trigger?: string;
            state?: string;
            text_input?: string;
            json_input?: Record<string, never>;
            final_text?: string;
            final_json?: Record<string, never>;
            error?: string;
            /** Format: date-time */
            queued_at?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            ended_at?: string;
            /** Format: int64 */
            elapsed_ms?: number;
            workflow_snapshot?: Record<string, never>;
        };
        v1RuntimeEngineStatus: {
            name?: string;
            available?: boolean;
            native_resume?: boolean;
            cli_version?: string;
        };
        v1RuntimeModelCompatibility: {
            runtime_engine?: string;
            status?: string;
            reason?: string;
        };
        v1RuntimeModelDefault: {
            runtime_engine?: string;
            provider_model_id?: string;
        };
        v1Schedule: {
            enabled?: boolean;
            frequency?: string;
            /** Format: int32 */
            hour?: number;
            /** Format: int32 */
            minute?: number;
            /** Format: int32 */
            weekday?: number;
            timezone?: string;
        };
        v1SendSessionMessageResponse: {
            user_message?: components["schemas"]["v1SessionMessage"];
            assistant_message?: components["schemas"]["v1SessionMessage"];
        };
        v1Session: {
            id?: string;
            title?: string;
            expert_id?: string;
            archived?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int64 */
            version?: number;
            current_provider_model_id?: string;
        };
        v1SessionMessage: {
            /** Format: int64 */
            id?: number;
            role?: string;
            state?: string;
            content?: string;
            error?: string;
            /** Format: int64 */
            elapsed_ms?: number;
            /** Format: date-time */
            created_at?: string;
            progress_stage?: string;
            response_snapshot?: components["schemas"]["v1ResponseSnapshot"];
        };
        v1Skill: {
            id?: string;
            name?: string;
            source?: string;
            git_url?: string;
            git_ref?: string;
            sha256?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int64 */
            version?: number;
        };
        v1UpdateSettingsRequest: {
            personality?: string;
            personality_instructions?: string;
            runtime_model_defaults?: components["schemas"]["v1RuntimeModelDefault"][];
            default_runtime_engine?: string;
            language?: string;
            timezone?: string;
            /** Format: int64 */
            expected_version?: number;
        };
        v1UserAccount: {
            id?: string;
            username?: string;
            email?: string;
            display_name?: string;
            administrator?: boolean;
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: int64 */
            version?: number;
        };
        v1Workflow: {
            id?: string;
            name?: string;
            goal?: string;
            expert_id?: string;
            provider_model_id?: string;
            runtime_engine?: string;
            environment?: components["schemas"]["v1EnvironmentVariable"][];
            schedule?: components["schemas"]["v1Schedule"];
            git_source?: components["schemas"]["v1GitSource"];
            api_credential_configured?: boolean;
            deleted?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int64 */
            version?: number;
        };
        v1WorkflowCredential: {
            api_key?: string;
            api_secret?: string;
            /** Format: date-time */
            created_at?: string;
        };
        v1WorkflowInput: {
            name?: string;
            goal?: string;
            expert_id?: string;
            provider_model_id?: string;
            runtime_engine?: string;
            environment?: components["schemas"]["v1EnvironmentVariable"][];
            schedule?: components["schemas"]["v1Schedule"];
        };
        v1WorkspaceEntry: {
            path?: string;
            name?: string;
            directory?: boolean;
            /** Format: int64 */
            size?: number;
            /** Format: date-time */
            modified_at?: string;
        };
        v1WorkspaceFile: {
            path?: string;
            /** Format: byte */
            content?: string;
            content_type?: string;
            /** Format: int64 */
            size?: number;
            /** Format: date-time */
            modified_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AgentWorkspaceService_ListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListUsersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateUserRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CreateUserResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_SetUserEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceSetUserEnabledBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1UserAccount"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ResetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceResetUserPasswordBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ResetUserPasswordResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListExperts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListExpertsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateExpert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateExpertRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Expert"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_DeleteExpert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_UpdateExpert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceUpdateExpertBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Expert"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListMCPServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListMCPServersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateMCPServerRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1MCPServer"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_DeleteMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mcp_server_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_UpdateMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mcp_server_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceUpdateMCPServerBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1MCPServer"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_TestMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mcp_server_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceTestMCPServerBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1MCPServer"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListSkills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListSkillsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateSkill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateSkillRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Skill"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_DeleteSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_UpdateSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceUpdateSkillBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Skill"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CurrentUser"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListModelProviderConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListModelProviderConnectionsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateModelProviderConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateModelProviderConnectionRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ModelProviderConnection"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_DeleteModelProviderConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_UpdateModelProviderConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceUpdateModelProviderConnectionBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ModelProviderConnection"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateProviderModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceCreateProviderModelBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ProviderModel"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_RefreshProviderModels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceRefreshProviderModelsBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ModelProviderConnection"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListModelProviderPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListModelProviderPresetsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListRuntimeEngines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListRuntimeEnginesResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListSessions: {
        parameters: {
            query?: {
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListSessionsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateSessionRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Session"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_GetSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Session"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_DeleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_UpdateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceUpdateSessionBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Session"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_SetSessionArchived: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceSetSessionArchivedBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Session"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListSessionMessages: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListSessionMessagesResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_SendSessionMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceSendSessionMessageBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1SendSessionMessageResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CancelSessionMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceCancelSessionMessageBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1SessionMessage"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_RetrySessionMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceRetrySessionMessageBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1SendSessionMessageResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_GetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1PersonalSettings"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_UpdateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1PersonalSettings"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListWorkflows: {
        parameters: {
            query?: {
                deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListWorkflowsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateWorkflowRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Workflow"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_GetWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Workflow"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_DeleteWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_UpdateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceUpdateWorkflowBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Workflow"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_GenerateWorkflowCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceGenerateWorkflowCredentialBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1WorkflowCredential"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListArtifactsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_GetArtifactDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ArtifactDownload"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListRuns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListRunsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_RunWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceRunWorkflowBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Run"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_GetRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Run"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceCancelRunBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Run"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_RerunWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceRerunWorkflowBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Run"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ListWorkspaceEntries: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListWorkspaceEntriesResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_ClearWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceClearWorkspaceBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CloneWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceCloneWorkspaceBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1Workflow"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_CreateWorkspaceDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceCreateWorkspaceDirectoryBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1WorkspaceEntry"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_GetWorkspaceFile: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1WorkspaceFile"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentWorkspaceService_UploadWorkspaceFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWorkspaceServiceUploadWorkspaceFileBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1WorkspaceEntry"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    HealthService_Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1HealthResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    HealthService_Ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ReadyResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
}
