// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: execution/v1/execution.proto

package executionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_ListRuns_FullMethodName     = "/execution.v1.ExecutionService/ListRuns"
	ExecutionService_GetRun_FullMethodName       = "/execution.v1.ExecutionService/GetRun"
	ExecutionService_InterruptRun_FullMethodName = "/execution.v1.ExecutionService/InterruptRun"
	ExecutionService_ResumeRun_FullMethodName    = "/execution.v1.ExecutionService/ResumeRun"
	ExecutionService_CancelRun_FullMethodName    = "/execution.v1.ExecutionService/CancelRun"
	ExecutionService_KillRun_FullMethodName      = "/execution.v1.ExecutionService/KillRun"
	ExecutionService_RecoverRun_FullMethodName   = "/execution.v1.ExecutionService/RecoverRun"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionServiceClient interface {
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error)
	InterruptRun(ctx context.Context, in *InterruptRunRequest, opts ...grpc.CallOption) (*Run, error)
	ResumeRun(ctx context.Context, in *ResumeRunRequest, opts ...grpc.CallOption) (*Run, error)
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error)
	KillRun(ctx context.Context, in *KillRunRequest, opts ...grpc.CallOption) (*Run, error)
	RecoverRun(ctx context.Context, in *RecoverRunRequest, opts ...grpc.CallOption) (*Run, error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, ExecutionService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) InterruptRun(ctx context.Context, in *InterruptRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, ExecutionService_InterruptRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) ResumeRun(ctx context.Context, in *ResumeRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, ExecutionService_ResumeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, ExecutionService_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) KillRun(ctx context.Context, in *KillRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, ExecutionService_KillRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) RecoverRun(ctx context.Context, in *RecoverRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, ExecutionService_RecoverRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
type ExecutionServiceServer interface {
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	GetRun(context.Context, *GetRunRequest) (*Run, error)
	InterruptRun(context.Context, *InterruptRunRequest) (*Run, error)
	ResumeRun(context.Context, *ResumeRunRequest) (*Run, error)
	CancelRun(context.Context, *CancelRunRequest) (*Run, error)
	KillRun(context.Context, *KillRunRequest) (*Run, error)
	RecoverRun(context.Context, *RecoverRunRequest) (*Run, error)
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedExecutionServiceServer) GetRun(context.Context, *GetRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedExecutionServiceServer) InterruptRun(context.Context, *InterruptRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method InterruptRun not implemented")
}
func (UnimplementedExecutionServiceServer) ResumeRun(context.Context, *ResumeRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRun not implemented")
}
func (UnimplementedExecutionServiceServer) CancelRun(context.Context, *CancelRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedExecutionServiceServer) KillRun(context.Context, *KillRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method KillRun not implemented")
}
func (UnimplementedExecutionServiceServer) RecoverRun(context.Context, *RecoverRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverRun not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_InterruptRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).InterruptRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_InterruptRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).InterruptRun(ctx, req.(*InterruptRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_ResumeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ResumeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ResumeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ResumeRun(ctx, req.(*ResumeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_KillRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).KillRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_KillRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).KillRun(ctx, req.(*KillRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_RecoverRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).RecoverRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_RecoverRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).RecoverRun(ctx, req.(*RecoverRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.v1.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRuns",
			Handler:    _ExecutionService_ListRuns_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _ExecutionService_GetRun_Handler,
		},
		{
			MethodName: "InterruptRun",
			Handler:    _ExecutionService_InterruptRun_Handler,
		},
		{
			MethodName: "ResumeRun",
			Handler:    _ExecutionService_ResumeRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _ExecutionService_CancelRun_Handler,
		},
		{
			MethodName: "KillRun",
			Handler:    _ExecutionService_KillRun_Handler,
		},
		{
			MethodName: "RecoverRun",
			Handler:    _ExecutionService_RecoverRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "execution/v1/execution.proto",
}

const (
	RunEventStreamService_Stream_FullMethodName = "/execution.v1.RunEventStreamService/Stream"
)

// RunEventStreamServiceClient is the client API for RunEventStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunEventStreamServiceClient interface {
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
}

type runEventStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunEventStreamServiceClient(cc grpc.ClientConnInterface) RunEventStreamServiceClient {
	return &runEventStreamServiceClient{cc}
}

func (c *runEventStreamServiceClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunEventStreamService_ServiceDesc.Streams[0], RunEventStreamService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunEventStreamService_StreamClient = grpc.ServerStreamingClient[StreamResponse]

// RunEventStreamServiceServer is the server API for RunEventStreamService service.
// All implementations must embed UnimplementedRunEventStreamServiceServer
// for forward compatibility.
type RunEventStreamServiceServer interface {
	Stream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error
	mustEmbedUnimplementedRunEventStreamServiceServer()
}

// UnimplementedRunEventStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunEventStreamServiceServer struct{}

func (UnimplementedRunEventStreamServiceServer) Stream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRunEventStreamServiceServer) mustEmbedUnimplementedRunEventStreamServiceServer() {}
func (UnimplementedRunEventStreamServiceServer) testEmbeddedByValue()                               {}

// UnsafeRunEventStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunEventStreamServiceServer will
// result in compilation errors.
type UnsafeRunEventStreamServiceServer interface {
	mustEmbedUnimplementedRunEventStreamServiceServer()
}

func RegisterRunEventStreamServiceServer(s grpc.ServiceRegistrar, srv RunEventStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedRunEventStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunEventStreamService_ServiceDesc, srv)
}

func _RunEventStreamService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunEventStreamServiceServer).Stream(m, &grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunEventStreamService_StreamServer = grpc.ServerStreamingServer[StreamResponse]

// RunEventStreamService_ServiceDesc is the grpc.ServiceDesc for RunEventStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunEventStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.v1.RunEventStreamService",
	HandlerType: (*RunEventStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _RunEventStreamService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "execution/v1/execution.proto",
}
