// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: execution/v1/execution.proto

package executionv1

import (
	v1 "agent-platform/backend/api/types/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRunsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TeamId              string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AgentId             *string                `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	RepositoryBindingId *string                `protobuf:"bytes,3,opt,name=repository_binding_id,json=repositoryBindingId,proto3,oneof" json:"repository_binding_id,omitempty"`
	TaskId              *string                `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	State               *string                `protobuf:"bytes,5,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Runtime             *string                `protobuf:"bytes,6,opt,name=runtime,proto3,oneof" json:"runtime,omitempty"`
	CreatedFrom         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_from,json=createdFrom,proto3,oneof" json:"created_from,omitempty"`
	CreatedTo           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_to,json=createdTo,proto3,oneof" json:"created_to,omitempty"`
	Limit               *int32                 `protobuf:"varint,9,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ListRunsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListRunsRequest) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

func (x *ListRunsRequest) GetRepositoryBindingId() string {
	if x != nil && x.RepositoryBindingId != nil {
		return *x.RepositoryBindingId
	}
	return ""
}

func (x *ListRunsRequest) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *ListRunsRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *ListRunsRequest) GetRuntime() string {
	if x != nil && x.Runtime != nil {
		return *x.Runtime
	}
	return ""
}

func (x *ListRunsRequest) GetCreatedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedFrom
	}
	return nil
}

func (x *ListRunsRequest) GetCreatedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTo
	}
	return nil
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Run                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ListRunsResponse) GetItems() []*Run {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunResponse) Reset() {
	*x = GetRunResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunResponse) ProtoMessage() {}

func (x *GetRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunResponse.ProtoReflect.Descriptor instead.
func (*GetRunResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *GetRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

type InterruptRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptRunRequest) Reset() {
	*x = InterruptRunRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptRunRequest) ProtoMessage() {}

func (x *InterruptRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptRunRequest.ProtoReflect.Descriptor instead.
func (*InterruptRunRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *InterruptRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type InterruptRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptRunResponse) Reset() {
	*x = InterruptRunResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptRunResponse) ProtoMessage() {}

func (x *InterruptRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptRunResponse.ProtoReflect.Descriptor instead.
func (*InterruptRunResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *InterruptRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

type ResumeRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRunRequest) Reset() {
	*x = ResumeRunRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunRequest) ProtoMessage() {}

func (x *ResumeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunRequest.ProtoReflect.Descriptor instead.
func (*ResumeRunRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ResumeRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRunResponse) Reset() {
	*x = ResumeRunResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunResponse) ProtoMessage() {}

func (x *ResumeRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunResponse.ProtoReflect.Descriptor instead.
func (*ResumeRunResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{8}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{9}
}

func (x *CancelRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

type KillRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRunRequest) Reset() {
	*x = KillRunRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRunRequest) ProtoMessage() {}

func (x *KillRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRunRequest.ProtoReflect.Descriptor instead.
func (*KillRunRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{10}
}

func (x *KillRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type KillRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRunResponse) Reset() {
	*x = KillRunResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRunResponse) ProtoMessage() {}

func (x *KillRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRunResponse.ProtoReflect.Descriptor instead.
func (*KillRunResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{11}
}

func (x *KillRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

type Run struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentReleaseId  string                 `protobuf:"bytes,3,opt,name=agent_release_id,json=agentReleaseId,proto3" json:"agent_release_id,omitempty"`
	RuntimeImageId  string                 `protobuf:"bytes,4,opt,name=runtime_image_id,json=runtimeImageId,proto3" json:"runtime_image_id,omitempty"`
	RequestText     string                 `protobuf:"bytes,5,opt,name=request_text,json=requestText,proto3" json:"request_text,omitempty"`
	State           string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	ModelBinding    *v1.ModelBinding       `protobuf:"bytes,7,opt,name=model_binding,json=modelBinding,proto3" json:"model_binding,omitempty"`
	ModelBudget     *v1.ModelBudget        `protobuf:"bytes,8,opt,name=model_budget,json=modelBudget,proto3" json:"model_budget,omitempty"`
	ExecutionLimits *v1.ExecutionLimits    `protobuf:"bytes,9,opt,name=execution_limits,json=executionLimits,proto3" json:"execution_limits,omitempty"`
	Usage           *v1.Usage              `protobuf:"bytes,10,opt,name=usage,proto3" json:"usage,omitempty"`
	CostAmount      string                 `protobuf:"bytes,11,opt,name=cost_amount,json=costAmount,proto3" json:"cost_amount,omitempty"`
	TerminalError   *v1.ExecutionError     `protobuf:"bytes,12,opt,name=terminal_error,json=terminalError,proto3,oneof" json:"terminal_error,omitempty"`
	AttemptCount    int32                  `protobuf:"varint,13,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,14,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	EndedAt         *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version         int64                  `protobuf:"varint,19,opt,name=version,proto3" json:"version,omitempty"`
	Attempts        []*Attempt             `protobuf:"bytes,20,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_execution_v1_execution_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{12}
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Run) GetAgentReleaseId() string {
	if x != nil {
		return x.AgentReleaseId
	}
	return ""
}

func (x *Run) GetRuntimeImageId() string {
	if x != nil {
		return x.RuntimeImageId
	}
	return ""
}

func (x *Run) GetRequestText() string {
	if x != nil {
		return x.RequestText
	}
	return ""
}

func (x *Run) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Run) GetModelBinding() *v1.ModelBinding {
	if x != nil {
		return x.ModelBinding
	}
	return nil
}

func (x *Run) GetModelBudget() *v1.ModelBudget {
	if x != nil {
		return x.ModelBudget
	}
	return nil
}

func (x *Run) GetExecutionLimits() *v1.ExecutionLimits {
	if x != nil {
		return x.ExecutionLimits
	}
	return nil
}

func (x *Run) GetUsage() *v1.Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Run) GetCostAmount() string {
	if x != nil {
		return x.CostAmount
	}
	return ""
}

func (x *Run) GetTerminalError() *v1.ExecutionError {
	if x != nil {
		return x.TerminalError
	}
	return nil
}

func (x *Run) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *Run) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Run) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Run) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Run) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Run) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Run) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Run) GetAttempts() []*Attempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

type Attempt struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number                int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	WorkerId              string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	State                 string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	InfrastructureFailure bool                   `protobuf:"varint,5,opt,name=infrastructure_failure,json=infrastructureFailure,proto3" json:"infrastructure_failure,omitempty"`
	Error                 *v1.ExecutionError     `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	StartedAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt               *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Attempt) Reset() {
	*x = Attempt{}
	mi := &file_execution_v1_execution_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attempt) ProtoMessage() {}

func (x *Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attempt.ProtoReflect.Descriptor instead.
func (*Attempt) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{13}
}

func (x *Attempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attempt) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Attempt) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Attempt) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Attempt) GetInfrastructureFailure() bool {
	if x != nil {
		return x.InfrastructureFailure
	}
	return false
}

func (x *Attempt) GetError() *v1.ExecutionError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Attempt) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Attempt) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	After         int64                  `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{14}
}

func (x *StreamRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StreamRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       *structpb.Value        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{15}
}

func (x *StreamResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StreamResponse) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_execution_v1_execution_proto protoreflect.FileDescriptor

const file_execution_v1_execution_proto_rawDesc = "" +
	"\n" +
	"\x1cexecution/v1/execution.proto\x12\fexecution.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x14types/v1/types.proto\"\xed\x03\n" +
	"\x0fListRunsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1e\n" +
	"\bagent_id\x18\x02 \x01(\tH\x00R\aagentId\x88\x01\x01\x127\n" +
	"\x15repository_binding_id\x18\x03 \x01(\tH\x01R\x13repositoryBindingId\x88\x01\x01\x12\x1c\n" +
	"\atask_id\x18\x04 \x01(\tH\x02R\x06taskId\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x05 \x01(\tH\x03R\x05state\x88\x01\x01\x12\x1d\n" +
	"\aruntime\x18\x06 \x01(\tH\x04R\aruntime\x88\x01\x01\x12B\n" +
	"\fcreated_from\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x05R\vcreatedFrom\x88\x01\x01\x12>\n" +
	"\n" +
	"created_to\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x06R\tcreatedTo\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\t \x01(\x05H\aR\x05limit\x88\x01\x01B\v\n" +
	"\t_agent_idB\x18\n" +
	"\x16_repository_binding_idB\n" +
	"\n" +
	"\b_task_idB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_runtimeB\x0f\n" +
	"\r_created_fromB\r\n" +
	"\v_created_toB\b\n" +
	"\x06_limit\";\n" +
	"\x10ListRunsResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.execution.v1.RunR\x05items\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"5\n" +
	"\x0eGetRunResponse\x12#\n" +
	"\x03run\x18\x01 \x01(\v2\x11.execution.v1.RunR\x03run\",\n" +
	"\x13InterruptRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\";\n" +
	"\x14InterruptRunResponse\x12#\n" +
	"\x03run\x18\x01 \x01(\v2\x11.execution.v1.RunR\x03run\")\n" +
	"\x10ResumeRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"8\n" +
	"\x11ResumeRunResponse\x12#\n" +
	"\x03run\x18\x01 \x01(\v2\x11.execution.v1.RunR\x03run\")\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"8\n" +
	"\x11CancelRunResponse\x12#\n" +
	"\x03run\x18\x01 \x01(\v2\x11.execution.v1.RunR\x03run\"'\n" +
	"\x0eKillRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"6\n" +
	"\x0fKillRunResponse\x12#\n" +
	"\x03run\x18\x01 \x01(\v2\x11.execution.v1.RunR\x03run\"\xbe\a\n" +
	"\x03Run\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12(\n" +
	"\x10agent_release_id\x18\x03 \x01(\tR\x0eagentReleaseId\x12(\n" +
	"\x10runtime_image_id\x18\x04 \x01(\tR\x0eruntimeImageId\x12!\n" +
	"\frequest_text\x18\x05 \x01(\tR\vrequestText\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12;\n" +
	"\rmodel_binding\x18\a \x01(\v2\x16.types.v1.ModelBindingR\fmodelBinding\x128\n" +
	"\fmodel_budget\x18\b \x01(\v2\x15.types.v1.ModelBudgetR\vmodelBudget\x12D\n" +
	"\x10execution_limits\x18\t \x01(\v2\x19.types.v1.ExecutionLimitsR\x0fexecutionLimits\x12%\n" +
	"\x05usage\x18\n" +
	" \x01(\v2\x0f.types.v1.UsageR\x05usage\x12\x1f\n" +
	"\vcost_amount\x18\v \x01(\tR\n" +
	"costAmount\x12D\n" +
	"\x0eterminal_error\x18\f \x01(\v2\x18.types.v1.ExecutionErrorH\x00R\rterminalError\x88\x01\x01\x12#\n" +
	"\rattempt_count\x18\r \x01(\x05R\fattemptCount\x12\x1d\n" +
	"\n" +
	"created_by\x18\x0e \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"started_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tstartedAt\x88\x01\x01\x12:\n" +
	"\bended_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\aendedAt\x88\x01\x01\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x13 \x01(\x03R\aversion\x121\n" +
	"\battempts\x18\x14 \x03(\v2\x15.execution.v1.AttemptR\battemptsB\x11\n" +
	"\x0f_terminal_errorB\r\n" +
	"\v_started_atB\v\n" +
	"\t_ended_at\"\xde\x02\n" +
	"\aAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x125\n" +
	"\x16infrastructure_failure\x18\x05 \x01(\bR\x15infrastructureFailure\x123\n" +
	"\x05error\x18\x06 \x01(\v2\x18.types.v1.ExecutionErrorH\x00R\x05error\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendedAt\x88\x01\x01B\b\n" +
	"\x06_errorB\v\n" +
	"\t_ended_at\"<\n" +
	"\rStreamRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x03R\x05after\"\xb8\x01\n" +
	"\x0eStreamResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x120\n" +
	"\apayload\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x83\x06\n" +
	"\x10ExecutionService\x12[\n" +
	"\bListRuns\x12\x1d.execution.v1.ListRunsRequest\x1a\x1e.execution.v1.ListRunsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/runs\x12S\n" +
	"\x06GetRun\x12\x1b.execution.v1.GetRunRequest\x1a\x11.execution.v1.Run\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/runs/{run_id}\x12\x95\x01\n" +
	"\fInterruptRun\x12!.execution.v1.InterruptRunRequest\x1a\x11.execution.v1.Run\"O\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1d\"\x1b/v1/runs/{run_id}/interrupt\x12\x8c\x01\n" +
	"\tResumeRun\x12\x1e.execution.v1.ResumeRunRequest\x1a\x11.execution.v1.Run\"L\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1a\"\x18/v1/runs/{run_id}/resume\x12\x8c\x01\n" +
	"\tCancelRun\x12\x1e.execution.v1.CancelRunRequest\x1a\x11.execution.v1.Run\"L\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1a\"\x18/v1/runs/{run_id}/cancel\x12\x86\x01\n" +
	"\aKillRun\x12\x1c.execution.v1.KillRunRequest\x1a\x11.execution.v1.Run\"J\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02\x18\"\x16/v1/runs/{run_id}/kill2\x80\x01\n" +
	"\x15RunEventStreamService\x12g\n" +
	"\x06Stream\x12\x1b.execution.v1.StreamRequest\x1a\x1c.execution.v1.StreamResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/runs/{run_id}/events0\x01B5Z3agent-platform/backend/api/execution/v1;executionv1b\x06proto3"

var (
	file_execution_v1_execution_proto_rawDescOnce sync.Once
	file_execution_v1_execution_proto_rawDescData []byte
)

func file_execution_v1_execution_proto_rawDescGZIP() []byte {
	file_execution_v1_execution_proto_rawDescOnce.Do(func() {
		file_execution_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_v1_execution_proto_rawDesc), len(file_execution_v1_execution_proto_rawDesc)))
	})
	return file_execution_v1_execution_proto_rawDescData
}

var file_execution_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_execution_v1_execution_proto_goTypes = []any{
	(*ListRunsRequest)(nil),       // 0: execution.v1.ListRunsRequest
	(*ListRunsResponse)(nil),      // 1: execution.v1.ListRunsResponse
	(*GetRunRequest)(nil),         // 2: execution.v1.GetRunRequest
	(*GetRunResponse)(nil),        // 3: execution.v1.GetRunResponse
	(*InterruptRunRequest)(nil),   // 4: execution.v1.InterruptRunRequest
	(*InterruptRunResponse)(nil),  // 5: execution.v1.InterruptRunResponse
	(*ResumeRunRequest)(nil),      // 6: execution.v1.ResumeRunRequest
	(*ResumeRunResponse)(nil),     // 7: execution.v1.ResumeRunResponse
	(*CancelRunRequest)(nil),      // 8: execution.v1.CancelRunRequest
	(*CancelRunResponse)(nil),     // 9: execution.v1.CancelRunResponse
	(*KillRunRequest)(nil),        // 10: execution.v1.KillRunRequest
	(*KillRunResponse)(nil),       // 11: execution.v1.KillRunResponse
	(*Run)(nil),                   // 12: execution.v1.Run
	(*Attempt)(nil),               // 13: execution.v1.Attempt
	(*StreamRequest)(nil),         // 14: execution.v1.StreamRequest
	(*StreamResponse)(nil),        // 15: execution.v1.StreamResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*v1.ModelBinding)(nil),       // 17: types.v1.ModelBinding
	(*v1.ModelBudget)(nil),        // 18: types.v1.ModelBudget
	(*v1.ExecutionLimits)(nil),    // 19: types.v1.ExecutionLimits
	(*v1.Usage)(nil),              // 20: types.v1.Usage
	(*v1.ExecutionError)(nil),     // 21: types.v1.ExecutionError
	(*structpb.Value)(nil),        // 22: google.protobuf.Value
}
var file_execution_v1_execution_proto_depIdxs = []int32{
	16, // 0: execution.v1.ListRunsRequest.created_from:type_name -> google.protobuf.Timestamp
	16, // 1: execution.v1.ListRunsRequest.created_to:type_name -> google.protobuf.Timestamp
	12, // 2: execution.v1.ListRunsResponse.items:type_name -> execution.v1.Run
	12, // 3: execution.v1.GetRunResponse.run:type_name -> execution.v1.Run
	12, // 4: execution.v1.InterruptRunResponse.run:type_name -> execution.v1.Run
	12, // 5: execution.v1.ResumeRunResponse.run:type_name -> execution.v1.Run
	12, // 6: execution.v1.CancelRunResponse.run:type_name -> execution.v1.Run
	12, // 7: execution.v1.KillRunResponse.run:type_name -> execution.v1.Run
	17, // 8: execution.v1.Run.model_binding:type_name -> types.v1.ModelBinding
	18, // 9: execution.v1.Run.model_budget:type_name -> types.v1.ModelBudget
	19, // 10: execution.v1.Run.execution_limits:type_name -> types.v1.ExecutionLimits
	20, // 11: execution.v1.Run.usage:type_name -> types.v1.Usage
	21, // 12: execution.v1.Run.terminal_error:type_name -> types.v1.ExecutionError
	16, // 13: execution.v1.Run.created_at:type_name -> google.protobuf.Timestamp
	16, // 14: execution.v1.Run.started_at:type_name -> google.protobuf.Timestamp
	16, // 15: execution.v1.Run.ended_at:type_name -> google.protobuf.Timestamp
	16, // 16: execution.v1.Run.updated_at:type_name -> google.protobuf.Timestamp
	13, // 17: execution.v1.Run.attempts:type_name -> execution.v1.Attempt
	21, // 18: execution.v1.Attempt.error:type_name -> types.v1.ExecutionError
	16, // 19: execution.v1.Attempt.started_at:type_name -> google.protobuf.Timestamp
	16, // 20: execution.v1.Attempt.ended_at:type_name -> google.protobuf.Timestamp
	22, // 21: execution.v1.StreamResponse.payload:type_name -> google.protobuf.Value
	16, // 22: execution.v1.StreamResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 23: execution.v1.ExecutionService.ListRuns:input_type -> execution.v1.ListRunsRequest
	2,  // 24: execution.v1.ExecutionService.GetRun:input_type -> execution.v1.GetRunRequest
	4,  // 25: execution.v1.ExecutionService.InterruptRun:input_type -> execution.v1.InterruptRunRequest
	6,  // 26: execution.v1.ExecutionService.ResumeRun:input_type -> execution.v1.ResumeRunRequest
	8,  // 27: execution.v1.ExecutionService.CancelRun:input_type -> execution.v1.CancelRunRequest
	10, // 28: execution.v1.ExecutionService.KillRun:input_type -> execution.v1.KillRunRequest
	14, // 29: execution.v1.RunEventStreamService.Stream:input_type -> execution.v1.StreamRequest
	1,  // 30: execution.v1.ExecutionService.ListRuns:output_type -> execution.v1.ListRunsResponse
	12, // 31: execution.v1.ExecutionService.GetRun:output_type -> execution.v1.Run
	12, // 32: execution.v1.ExecutionService.InterruptRun:output_type -> execution.v1.Run
	12, // 33: execution.v1.ExecutionService.ResumeRun:output_type -> execution.v1.Run
	12, // 34: execution.v1.ExecutionService.CancelRun:output_type -> execution.v1.Run
	12, // 35: execution.v1.ExecutionService.KillRun:output_type -> execution.v1.Run
	15, // 36: execution.v1.RunEventStreamService.Stream:output_type -> execution.v1.StreamResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_execution_v1_execution_proto_init() }
func file_execution_v1_execution_proto_init() {
	if File_execution_v1_execution_proto != nil {
		return
	}
	file_execution_v1_execution_proto_msgTypes[0].OneofWrappers = []any{}
	file_execution_v1_execution_proto_msgTypes[12].OneofWrappers = []any{}
	file_execution_v1_execution_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_v1_execution_proto_rawDesc), len(file_execution_v1_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_execution_v1_execution_proto_goTypes,
		DependencyIndexes: file_execution_v1_execution_proto_depIdxs,
		MessageInfos:      file_execution_v1_execution_proto_msgTypes,
	}.Build()
	File_execution_v1_execution_proto = out.File
	file_execution_v1_execution_proto_goTypes = nil
	file_execution_v1_execution_proto_depIdxs = nil
}
