server {
    listen 80;
    server_name _;
    root /ragflow/web/dist;
    client_max_body_size 101m;
    proxy_read_timeout 120s;
    proxy_send_timeout 120s;
    location ~ ^/(v1|api) {
        proxy_pass http://127.0.0.1:9380;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }
    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
