// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"agent-platform/backend/internal/infrastructure/gormdb"
	"agent-platform/backend/internal/platformconfig"
	"agent-platform/backend/internal/server"
	"agent-platform/backend/internal/service/platform"
	"agent-platform/backend/internal/service/workspace"
	"agent-platform/backend/internal/wiring/agentworkspace"
	"agent-platform/backend/internal/wiring/aicreation"
	"agent-platform/backend/internal/wiring/knowledgebase"
	platform2 "agent-platform/backend/internal/wiring/platform"
	"context"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

// Injectors from wire.go:

func initializeAPI(contextContext context.Context, config platformconfig.Config, database *gormdb.Database, logger *slog.Logger) (*kratos.App, error) {
	service, err := platform.New(database)
	if err != nil {
		return nil, err
	}
	tokenVerifier, err := agentworkspace.NewTokenVerifier(contextContext, config)
	if err != nil {
		return nil, err
	}
	provider, err := agentworkspace.NewIdentityProvider(config)
	if err != nil {
		return nil, err
	}
	applicationService, err := agentworkspace.NewAccountService(contextContext, config, database, tokenVerifier, provider)
	if err != nil {
		return nil, err
	}
	repository := agentworkspace.NewCreditsRepository(database)
	service2, err := agentworkspace.NewCreditsService(repository)
	if err != nil {
		return nil, err
	}
	box, err := agentworkspace.NewSecretBox(config)
	if err != nil {
		return nil, err
	}
	objectstoreProvider, err := platform2.NewObjectStore(config)
	if err != nil {
		return nil, err
	}
	service3, err := aicreation.NewApplication(database, repository, service2, box, objectstoreProvider)
	if err != nil {
		return nil, err
	}
	service4, err := agentworkspace.NewAIApplicationService(database, box)
	if err != nil {
		return nil, err
	}
	chatModel := agentworkspace.NewAssistantChatModel()
	service5, err := agentworkspace.NewWorkspaceService(contextContext, database, repository, applicationService, objectstoreProvider, box, config)
	if err != nil {
		return nil, err
	}
	store, err := agentworkspace.NewWorkspaceFiles(config)
	if err != nil {
		return nil, err
	}
	skillstoreStore, err := agentworkspace.NewSkillStore(objectstoreProvider)
	if err != nil {
		return nil, err
	}
	recorder, err := agentworkspace.NewProductAnalytics(database, logger)
	if err != nil {
		return nil, err
	}
	searcher, err := knowledgebase.NewSearcher(config, database)
	if err != nil {
		return nil, err
	}
	workspaceService, err := workspace.New(applicationService, service2, service3, service4, chatModel, service5, box, store, skillstoreStore, objectstoreProvider, recorder, config, searcher)
	if err != nil {
		return nil, err
	}
	filterFunc, err := workspace.NewAuthenticationFilter(applicationService, service5, recorder)
	if err != nil {
		return nil, err
	}
	httpHandlers, err := agentworkspace.NewHTTPHandlers(workspaceService, filterFunc)
	if err != nil {
		return nil, err
	}
	httpServer, err := server.NewHTTPServerFromConfig(config, service, httpHandlers, logger)
	if err != nil {
		return nil, err
	}
	app := server.NewAPIApp(contextContext, config, logger, httpServer)
	return app, nil
}
