<script setup lang="ts">
import { inject, onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";
import { platformApiKey, type Expert, type MCPServer, type Skill } from "../api/client";
import ToastMessage from "../components/ToastMessage.vue";
const api = inject(platformApiKey)!;
const { t } = useI18n(); const experts = ref<Expert[]>([]); const mcp = ref<MCPServer[]>([]); const skills = ref<Skill[]>([]); const showForm = ref(false); const editing = ref<Expert>(); const error = ref("");
const form = ref({ name: "", description: "", mcp_server_ids: [] as string[], skill_ids: [] as string[] });
onMounted(refresh);
async function refresh() { try { [experts.value, mcp.value, skills.value] = await Promise.all([api.listExperts(), api.listMCPServers(), api.listSkills()]); } catch { error.value = t("errors.generic"); } }
function open(item?: Expert) { editing.value = item; form.value = item ? { name: item.name, description: item.description, mcp_server_ids: [...item.mcp_server_ids], skill_ids: [...item.skill_ids] } : { name: "", description: "", mcp_server_ids: [], skill_ids: [] }; showForm.value = true; }
async function save() { try { if (editing.value) await api.updateExpert(editing.value.id, form.value, editing.value.version); else await api.createExpert(form.value); showForm.value = false; await refresh(); } catch { error.value = t("errors.validation"); } }
async function remove(item: Expert) { if (!window.confirm(`${t('common.delete')} “${item.name}”?`)) return; await api.deleteExpert(item.id); await refresh(); }
</script>
<template><section class="page-surface"><header class="page-header"><div><p class="eyebrow">03 / REUSABLE EXPERTISE</p><h1>{{ t('experts.title') }}</h1><p>{{ t('experts.subtitle') }}</p></div><button class="button primary" @click="open()">＋ {{ t('experts.new') }}</button></header><ToastMessage v-if="error" kind="error" :title="t('common.failed')" :message="error" :close-label="t('common.close')" @dismiss="error = ''" /><div v-if="!experts.length" class="empty-workflows"><div class="blueprint expert-print"><i></i><i></i><span>✦</span></div><h2>{{ t('common.empty') }}</h2><p>{{ t('experts.subtitle') }}</p><button class="button primary" @click="open()">{{ t('experts.new') }}</button></div><div v-else class="expert-grid"><article v-for="expert in experts" :key="expert.id" class="expert-card"><div class="expert-sigil">{{ expert.name.slice(0, 2).toUpperCase() }}</div><div><p class="eyebrow">EXPERT / {{ expert.id.slice(0, 6) }}</p><h2>{{ expert.name }}</h2><p>{{ expert.description || '—' }}</p><div class="tag-row"><span v-for="id in expert.mcp_server_ids" :key="id">MCP · {{ mcp.find((item) => item.id === id)?.name ?? id.slice(0, 6) }}</span><span v-for="id in expert.skill_ids" :key="id">SKILL · {{ skills.find((item) => item.id === id)?.name ?? id.slice(0, 6) }}</span><small v-if="!expert.mcp_server_ids.length && !expert.skill_ids.length">{{ t('experts.noBindings') }}</small></div></div><div class="card-menu"><button @click="open(expert)">✎</button><button @click="remove(expert)">×</button></div></article></div></section><div v-if="showForm" class="modal-layer" @click.self="showForm = false"><form class="modal-card wide-modal" @submit.prevent="save"><p class="eyebrow">{{ editing ? t('common.edit') : t('common.new') }} / EXPERT</p><h2>{{ editing ? editing.name : t('experts.new') }}</h2><div class="form-grid"><label>{{ t('experts.name') }}<input v-model="form.name" required></label><label class="full">{{ t('experts.description') }}<textarea v-model="form.description" rows="4"></textarea><small>{{ t('experts.descriptionHint') }}</small></label><fieldset class="full"><legend>{{ t('experts.mcp') }}</legend><label v-for="item in mcp" :key="item.id" class="check-row"><input v-model="form.mcp_server_ids" type="checkbox" :value="item.id" :disabled="!item.tested"><span>{{ item.name }}</span><small>{{ item.tested ? t('experts.tested') : item.test_error || t('experts.testRequired') }}</small></label></fieldset><fieldset class="full"><legend>{{ t('experts.skills') }}</legend><label v-for="item in skills" :key="item.id" class="check-row"><input v-model="form.skill_ids" type="checkbox" :value="item.id"><span>{{ item.name }}</span><small>{{ item.sha256.slice(0, 10) }}</small></label></fieldset></div><div class="modal-actions"><button type="button" class="button ghost" @click="showForm = false">{{ t('common.cancel') }}</button><button class="button primary">{{ t('common.save') }}</button></div></form></div></template>
