<script setup lang="ts">
import { computed, inject, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { Share2 } from "@lucide/vue";
import IconPicker from "../components/IconPicker.vue";
import { ApiError, platformApiKey, type ApplicationKnowledgeBase, type DigitalHuman, type SmartAssistant, type SmartAssistantFAQ, type SmartAssistantInput } from "../api/client";
import { renderMarkdown } from "../markdown";

const api = inject(platformApiKey)!;
const route = useRoute();
const router = useRouter();
const { t } = useI18n();
const assistant = ref<SmartAssistant>();
const faqs = ref<SmartAssistantFAQ[]>([]);
const knowledgeBases = ref<ApplicationKnowledgeBase[]>([]);
const digitalHumans = ref<DigitalHuman[]>([]);
const error = ref("");
const saving = ref(false);
const activeTab = ref<"basic" | "faq">("basic");
const shareDialogOpen = ref(route.query.share === "1");
const faqDraft = ref({ question: "", answer_markdown: "", display_order: 0, category: "", tag: "", icon: "", enabled: true });
const editingFAQ = ref<string>();
const faqEditDraft = ref({ question: "", answer_markdown: "", display_order: 0, category: "", tag: "", icon: "", enabled: true });
const shareToken = ref("");
const embedSnippet = computed(() => assistant.value && shareToken.value ? `<iframe src="${window.location.origin}/embed/assistant/${shareToken.value}" width="${assistant.value.share.width}" height="${assistant.value.share.height}"></iframe>` : "");
const allowedOrigins = computed({ get: () => assistant.value?.share.allowed_origins?.join("\n") || "", set: (value: string) => { if (assistant.value) assistant.value.share.allowed_origins = value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean); } });
const id = String(route.params.assistantId);

async function refresh() { try { [assistant.value, faqs.value, knowledgeBases.value, digitalHumans.value] = await Promise.all([api.getSmartAssistant(id), api.listAssistantFAQs(id), api.listApplicationKnowledgeBases(), api.listDigitalHumans()]); } catch (cause) { error.value = errorMessage(cause, "aiApplications.loadFailed"); } }
function input(state = assistant.value?.state): SmartAssistantInput | undefined {
  if (!assistant.value) return undefined;
  return { name: assistant.value.name.trim(), icon: assistant.value.icon, introduction: assistant.value.introduction, scenario: assistant.value.scenario, service_goal: assistant.value.service_goal, answer_scope: assistant.value.answer_scope, operating_rules: assistant.value.operating_rules, response_style: assistant.value.response_style, knowledge_base_ids: assistant.value.knowledge_base_ids, expert_id: assistant.value.expert_id, expert_team_id: assistant.value.expert_team_id, digital_human_id: assistant.value.digital_human_id || undefined, state, share: { enabled: assistant.value.share.enabled, allowed_origins: assistant.value.share.allowed_origins ?? [], width: assistant.value.share.width || "100%", height: assistant.value.share.height || 600, free_text_enabled: assistant.value.share.free_text_enabled ?? false, daily_call_limit: assistant.value.share.daily_call_limit ?? 0 } };
}
function errorMessage(cause: unknown, fallback: string) {
  if (!(cause instanceof ApiError)) return t(fallback);
  if (cause.code === "invalid_input") return t("aiApplications.validationFailed");
  if (cause.code === "version_conflict") return t("aiApplications.versionConflict");
  if (cause.code === "resource_conflict") return t("aiApplications.conflict");
  return t(fallback);
}
async function save(state = assistant.value?.state) { if (!assistant.value) return false; const payload = input(state); if (!payload) return false; saving.value = true; try { assistant.value = await api.updateSmartAssistant(id, payload, assistant.value.version); return true; } catch (cause) { error.value = errorMessage(cause, "aiApplications.saveFailed"); return false; } finally { saving.value = false; } }
async function addFAQ() { if (!faqDraft.value.question.trim() || !faqDraft.value.answer_markdown.trim()) return; try { faqs.value.push(await api.createAssistantFAQ(id, faqDraft.value)); faqDraft.value = { question: "", answer_markdown: "", display_order: faqs.value.length, category: "", tag: "", icon: "", enabled: true }; } catch (cause) { error.value = errorMessage(cause, "aiApplications.saveFailed"); } }
function editFAQ(faq: SmartAssistantFAQ) { editingFAQ.value = faq.id; faqEditDraft.value = { question: faq.question, answer_markdown: faq.answer_markdown, display_order: faq.display_order, category: faq.category, tag: faq.tag, icon: faq.icon, enabled: faq.enabled }; }
async function saveFAQ(faq: SmartAssistantFAQ) { try { const updated = await api.updateAssistantFAQ(id, faq.id, faqEditDraft.value, faq.version); faqs.value = faqs.value.map((candidate) => candidate.id === updated.id ? updated : candidate); editingFAQ.value = undefined; } catch (cause) { error.value = errorMessage(cause, "aiApplications.saveFailed"); } }
async function toggleFAQ(faq: SmartAssistantFAQ) { try { const updated = await api.updateAssistantFAQ(id, faq.id, { question: faq.question, answer_markdown: faq.answer_markdown, display_order: faq.display_order, category: faq.category, tag: faq.tag, icon: faq.icon, enabled: !faq.enabled }, faq.version); faqs.value = faqs.value.map((candidate) => candidate.id === updated.id ? updated : candidate); } catch (cause) { error.value = errorMessage(cause, "aiApplications.saveFailed"); } }
async function moveFAQ(faq: SmartAssistantFAQ, direction: -1 | 1) { const index = faqs.value.findIndex((candidate) => candidate.id === faq.id); const other = faqs.value[index + direction]; if (!other) return; try { const [updated, swapped] = await Promise.all([api.updateAssistantFAQ(id, faq.id, { question: faq.question, answer_markdown: faq.answer_markdown, display_order: other.display_order, category: faq.category, tag: faq.tag, icon: faq.icon, enabled: faq.enabled }, faq.version), api.updateAssistantFAQ(id, other.id, { question: other.question, answer_markdown: other.answer_markdown, display_order: faq.display_order, category: other.category, tag: other.tag, icon: other.icon, enabled: other.enabled }, other.version)]); faqs.value = faqs.value.map((candidate) => candidate.id === updated.id ? updated : candidate.id === swapped.id ? swapped : candidate).sort((left, right) => left.display_order - right.display_order); } catch (cause) { error.value = errorMessage(cause, "aiApplications.saveFailed"); } }
async function removeFAQ(faq: SmartAssistantFAQ) { try { await api.deleteAssistantFAQ(id, faq.id); faqs.value = faqs.value.filter((item) => item.id !== faq.id); } catch (cause) { error.value = errorMessage(cause, "aiApplications.deleteFailed"); } }
async function regenerateToken() { if (!assistant.value) return; try { const result = await api.regenerateAssistantShareToken(id, assistant.value.version); assistant.value = result.assistant; shareToken.value = result.token; } catch (cause) { error.value = errorMessage(cause, "aiApplications.saveFailed"); } }
async function saveShare() { if (await save()) shareDialogOpen.value = false; }
async function startConversation() { if (!assistant.value) return; try { if (assistant.value.state !== "enabled" && !(await save("enabled"))) return; const session = await api.createAssistantSession(id); const welcome = assistant.value.introduction.trim(); await router.push(`/sessions?open=${encodeURIComponent(session.id)}${welcome ? `&assistant_welcome=${encodeURIComponent(welcome)}` : ""}`); } catch (cause) { error.value = errorMessage(cause, "aiApplications.startFailed"); } }
onMounted(refresh);
</script>

<template>
  <section class="application-detail-page">
    <header class="application-detail-header"><el-button text @click="router.push('/ai-apps/assistants')">← {{ t('common.back') }}</el-button><div><p class="eyebrow">{{ t('aiApplications.assistants.title') }}</p><h1>{{ assistant?.name || t('common.loading') }}</h1></div><div class="assistant-detail-actions"><el-button @click="startConversation">{{ t('aiApplications.startConversation') }}</el-button><el-button type="primary" :loading="saving" @click="save()">{{ t('common.save') }}</el-button></div></header>
    <el-alert v-if="error" :title="error" type="error" show-icon closable @close="error = ''" />
    <template v-if="assistant">
      <nav class="assistant-detail-tabs" role="tablist"><button type="button" :class="{ active: activeTab === 'basic' }" role="tab" :aria-selected="activeTab === 'basic'" @click="activeTab = 'basic'">{{ t('aiApplications.basic') }}</button><button type="button" :class="{ active: activeTab === 'faq' }" role="tab" :aria-selected="activeTab === 'faq'" @click="activeTab = 'faq'">{{ t('aiApplications.faq.title') }}</button></nav>
      <el-card v-if="activeTab === 'basic'" class="application-detail-card"><el-form label-position="top"><el-form-item :label="t('aiApplications.name')"><el-input v-model="assistant.name" /></el-form-item><el-form-item :label="t('aiApplications.icon')"><IconPicker v-model="assistant.icon" fallback="sparkles" /></el-form-item><el-form-item :label="t('aiApplications.welcome')"><el-input v-model="assistant.introduction" type="textarea" :rows="3" :placeholder="t('aiApplications.welcomePlaceholder')" /></el-form-item><el-form-item :label="t('aiApplications.goal')"><el-input v-model="assistant.service_goal" /></el-form-item><el-form-item :label="t('aiApplications.answerScope')"><el-input v-model="assistant.answer_scope" type="textarea" :rows="4" :placeholder="t('aiApplications.answerScopePlaceholder')" /></el-form-item><el-form-item :label="t('aiApplications.rules')"><el-input v-model="assistant.operating_rules" type="textarea" :rows="4" /></el-form-item><el-form-item :label="t('aiApplications.responseStyle')"><el-input v-model="assistant.response_style" /></el-form-item><el-form-item :label="t('aiApplications.digitalHuman.binding')"><el-select v-model="assistant.digital_human_id" clearable :placeholder="t('aiApplications.digitalHuman.selectPlaceholder')"><el-option v-for="human in digitalHumans.filter((item) => item.state === 'enabled')" :key="human.id" :label="human.name" :value="human.id" /></el-select></el-form-item><el-form-item :label="t('aiApplications.state')"><el-switch v-model="assistant.state" active-value="enabled" inactive-value="disabled" /></el-form-item><el-form-item :label="t('aiApplications.knowledge.selected')"><el-select v-model="assistant.knowledge_base_ids" multiple collapse-tags :placeholder="t('aiApplications.knowledge.selectPlaceholder')"><el-option v-for="base in knowledgeBases" :key="base.id" :label="base.name" :value="base.id" /></el-select></el-form-item><el-button text type="primary" @click="router.push('/ai-apps/knowledge-bases')">{{ t('aiApplications.knowledge.manage') }}</el-button></el-form></el-card>
      <el-card v-else class="application-detail-card"><template #header><div class="faq-list-header"><strong>{{ t('aiApplications.faq.title') }}</strong><el-button type="primary" @click="faqDraft.question = ''; faqDraft.answer_markdown = ''">{{ t('aiApplications.faq.add') }}</el-button></div></template><div v-for="(faq, index) in faqs" :key="faq.id" class="faq-row"><template v-if="editingFAQ === faq.id"><el-form label-position="top" class="faq-edit-form"><el-form-item :label="t('aiApplications.faq.question')"><el-input v-model="faqEditDraft.question" /></el-form-item><el-form-item :label="t('aiApplications.faq.answer')"><el-input v-model="faqEditDraft.answer_markdown" type="textarea" :rows="3" /></el-form-item><el-button type="primary" @click="saveFAQ(faq)">{{ t('common.save') }}</el-button><el-button @click="editingFAQ = undefined">{{ t('common.cancel') }}</el-button></el-form></template><template v-else><div class="faq-list-copy"><strong>{{ faq.question }}</strong><div class="markdown-body faq-answer" v-html="renderMarkdown(faq.answer_markdown)"></div></div><div class="faq-actions"><el-button text @click="editFAQ(faq)">{{ t('common.edit') }}</el-button><el-button text @click="toggleFAQ(faq)">{{ faq.enabled ? t('aiApplications.faq.disable') : t('aiApplications.faq.enable') }}</el-button><el-button text :disabled="index === 0" @click="moveFAQ(faq, -1)">↑</el-button><el-button text :disabled="index === faqs.length - 1" @click="moveFAQ(faq, 1)">↓</el-button><el-button text type="danger" @click="removeFAQ(faq)">{{ t('common.delete') }}</el-button></div></template></div><el-empty v-if="!faqs.length" :description="t('aiApplications.faq.empty')" /><el-form class="faq-create-form" label-position="top"><el-form-item :label="t('aiApplications.faq.question')"><el-input v-model="faqDraft.question" /></el-form-item><el-form-item :label="t('aiApplications.faq.answer')"><el-input v-model="faqDraft.answer_markdown" type="textarea" :rows="3" /></el-form-item><el-button type="primary" @click="addFAQ">{{ t('aiApplications.faq.add') }}</el-button></el-form></el-card>
    </template>
    <el-dialog v-model="shareDialogOpen" class="application-share-dialog" :title="t('aiApplications.share.title')" width="min(620px, 92vw)" destroy-on-close><el-form v-if="assistant" label-position="top"><el-form-item :label="t('aiApplications.share.enabled')"><el-switch v-model="assistant.share.enabled" /></el-form-item><el-form-item :label="t('aiApplications.share.width')"><el-input v-model="assistant.share.width" /></el-form-item><el-form-item :label="t('aiApplications.share.height')"><el-input-number v-model="assistant.share.height" :min="400" :max="1600" /></el-form-item><el-form-item :label="t('aiApplications.share.allowedOrigins')"><el-input v-model="allowedOrigins" type="textarea" :rows="3" :placeholder="t('aiApplications.share.allowedOriginsPlaceholder')" /></el-form-item><el-form-item :label="t('aiApplications.share.dailyLimit')"><el-input-number v-model="assistant.share.daily_call_limit" :min="0" :max="100000" /></el-form-item><el-form-item :label="t('aiApplications.share.freeText')"><el-switch v-model="assistant.share.free_text_enabled" /></el-form-item><el-button :disabled="!assistant.share.enabled" @click="regenerateToken">{{ t('aiApplications.share.regenerate') }}</el-button><el-input v-if="shareToken" class="share-snippet" :model-value="embedSnippet" readonly type="textarea" :rows="3" /></el-form><template #footer><el-button @click="shareDialogOpen = false">{{ t('common.cancel') }}</el-button><el-button type="primary" :loading="saving" @click="saveShare">{{ t('common.save') }}</el-button></template></el-dialog>
  </section>
</template>
