<script setup lang="ts">
import { inject, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { platformApiKey, type UserAccount } from "../api/client";
const api = inject(platformApiKey)!;
const { t } = useI18n(); const router = useRouter(); const users = ref<UserAccount[]>([]); const showCreate = ref(false); const revealed = ref(""); const error = ref(""); const form = ref({ username: "", email: "", display_name: "" });
onMounted(refresh); async function refresh() { try { users.value = await api.listUsers(); } catch { error.value = t("errors.generic"); } }
async function create() { try { const result = await api.createUser(form.value); revealed.value = result.temporary_password; showCreate.value = false; form.value = { username: "", email: "", display_name: "" }; await refresh(); } catch { error.value = t("errors.validation"); } }
async function toggle(item: UserAccount) { try { await api.setUserEnabled(item.id, !item.enabled, item.version); await refresh(); } catch { error.value = t("errors.conflict"); } }
async function reset(item: UserAccount) { if (!confirm(`${t('users.reset')} — ${item.username}?`)) return; try { revealed.value = (await api.resetUserPassword(item.id)).temporary_password; } catch { error.value = t("errors.generic"); } }
async function copy() { await navigator.clipboard.writeText(revealed.value); }
</script>
<template><section class="page-surface"><header class="page-header"><div><button class="back-link" @click="router.push('/sessions')">← {{ t('common.back') }}</button><p class="eyebrow">ADMIN / IDENTITY</p><h1>{{ t('users.title') }}</h1><p>{{ t('users.subtitle') }}</p></div><button class="button primary" @click="showCreate = true">＋ {{ t('users.create') }}</button></header><div v-if="error" class="notice error-notice">{{ error }}</div><div v-if="revealed" class="secret-banner"><div><p class="eyebrow">{{ t('users.temporary') }}</p><code>{{ revealed }}</code><small>{{ t('users.forceChange') }}</small></div><button class="button ghost" @click="copy">{{ t('common.copy') }}</button><button class="icon-button" @click="revealed = ''">×</button></div><div class="user-table"><div class="user-row user-head"><span>{{ t('users.user') }}</span><span>{{ t('users.email') }}</span><span>{{ t('users.status') }}</span><span>{{ t('users.created') }}</span><span></span></div><div v-for="item in users" :key="item.id" class="user-row"><span><span class="avatar">{{ item.display_name.slice(0, 2).toUpperCase() }}</span><span><strong>{{ item.display_name }}</strong><small>@{{ item.username }}<template v-if="item.administrator"> · {{ t('users.administrator') }}</template></small></span></span><span>{{ item.email }}</span><span><i class="run-state" :class="item.enabled ? 'succeeded' : 'failed'"></i>{{ item.enabled ? t('users.enabled') : t('users.disabled') }}</span><span>{{ new Date(item.created_at).toLocaleDateString() }}</span><span v-if="!item.administrator" class="run-actions"><button @click="reset(item)">{{ t('users.reset') }}</button><button @click="toggle(item)">{{ item.enabled ? t('users.disabled') : t('users.enabled') }}</button></span></div></div></section><div v-if="showCreate" class="modal-layer" @click.self="showCreate = false"><form class="modal-card" @submit.prevent="create"><p class="eyebrow">NEW / USER</p><h2>{{ t('users.create') }}</h2><label>{{ t('users.username') }}<input v-model="form.username" required pattern="[a-z][a-z0-9._-]{2,63}"></label><label>{{ t('users.displayName') }}<input v-model="form.display_name" required></label><label>{{ t('users.email') }}<input v-model="form.email" type="email" required></label><div class="modal-actions"><button type="button" class="button ghost" @click="showCreate = false">{{ t('common.cancel') }}</button><button class="button primary">{{ t('users.create') }}</button></div></form></div></template>
