<script setup lang="ts">
import { computed, inject, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { formatDuration, type SupportedLocale } from "../i18n";
import { platformApiKey, type Artifact, type Expert, type ModelProviderConnection, type Run, type RunEvent, type RuntimeEngineStatus, type Workflow, type WorkflowInput, type WorkspaceEntry } from "../api/client";
import ToastMessage from "../components/ToastMessage.vue";

type Tab = "artifacts" | "workspace" | "history" | "settings";
const api = inject(platformApiKey)!;
const route = useRoute(); const router = useRouter(); const { t, locale } = useI18n();
const workflowID = computed(() => String(route.params.workflowId));
const origin = window.location.origin;
const tab = ref<Tab>((route.query.tab as Tab) || "artifacts"); const workflow = ref<Workflow>(); const experts = ref<Expert[]>([]); const connections = ref<ModelProviderConnection[]>([]); const runtimes = ref<RuntimeEngineStatus[]>([]); const runs = ref<Run[]>([]); const selectedRun = ref<Run>(); const runEvents = ref<RunEvent[]>([]); const artifacts = ref<Artifact[]>([]); const entries = ref<WorkspaceEntry[]>([]); const workspacePath = ref(""); const workspaceUsage = ref({ used: 0, limit: 1 }); const loading = ref(true); const error = ref(""); const runInput = ref(""); const runInputMode = ref<"text" | "json">("text"); const running = ref(false); const preview = ref<{ path: string; content: string }>(); const credential = ref<{ api_key: string; api_secret: string }>();
const models = computed(() => connections.value.flatMap((connection) => connection.models.filter((model) => model.available).map((model) => ({ ...model, connection_name: connection.name }))));
const settingsForm = ref<WorkflowInput>({ name: "", goal: "", environment: [] });
function modelIncompatible(model: (typeof models.value)[number]) {
  if (!settingsForm.value.runtime_engine) return false;
  return model.compatibility.find((item) => item.runtime_engine === settingsForm.value.runtime_engine)?.status === "incompatible";
}
watch(() => settingsForm.value.runtime_engine, () => {
  const selectedModel = models.value.find((model) => model.id === settingsForm.value.provider_model_id);
  if (selectedModel && modelIncompatible(selectedModel)) settingsForm.value.provider_model_id = undefined;
});
const tabs: Tab[] = ["artifacts", "workspace", "history", "settings"];
const selectedRunArtifacts = computed(() => artifacts.value.filter((item) => item.run_id === selectedRun.value?.id));
watch(tab, (value) => {
  void router.replace({ query: { ...route.query, tab: value } });
  if (value === "workspace" && workflow.value && !workflow.value.deleted) void loadDirectory(workspacePath.value);
});
let runTimer: ReturnType<typeof setInterval> | undefined;
let eventController: AbortController | undefined;
onMounted(async () => { await refresh(); runTimer = setInterval(() => void refreshRuns(), 1500); });
onBeforeUnmount(() => { if (runTimer) clearInterval(runTimer); eventController?.abort(); });
async function refresh() { loading.value = true; error.value = ""; try { workflow.value = await api.getWorkflow(workflowID.value); settingsForm.value = { name: workflow.value.name, goal: workflow.value.goal, expert_id: workflow.value.expert_id, provider_model_id: workflow.value.provider_model_id, runtime_engine: workflow.value.runtime_engine, environment: workflow.value.environment ?? [], schedule: workflow.value.schedule }; [experts.value, connections.value, runtimes.value, runs.value, artifacts.value] = await Promise.all([api.listExperts(), api.listModelProviderConnections(), api.listRuntimeEngines(), api.listRuns(workflowID.value), api.listArtifacts(workflowID.value)]); if (!workflow.value.deleted) await loadDirectory(""); else if (tab.value === "workspace" || tab.value === "settings") tab.value = "history"; } catch { error.value = t("errors.generic"); } finally { loading.value = false; } }
async function refreshRuns() { try { runs.value = await api.listRuns(workflowID.value); if (selectedRun.value) selectedRun.value = runs.value.find((item) => item.id === selectedRun.value?.id); if (!runs.value.some((item) => item.state === "queued" || item.state === "running")) artifacts.value = await api.listArtifacts(workflowID.value); } catch { /* Keep the last usable projection during a transient poll failure. */ } }
async function runNow() { running.value = true; try { const input = runInputMode.value === "json" && runInput.value.trim() ? { json_input: JSON.parse(runInput.value) as Record<string, unknown> } : { text_input: runInput.value || undefined }; await api.runWorkflow(workflowID.value, input); runInput.value = ""; tab.value = "history"; runs.value = await api.listRuns(workflowID.value); } catch { error.value = runInputMode.value === "json" ? t("errors.validation") : t("errors.generic"); } finally { running.value = false; } }
async function loadDirectory(path: string) { const result = await api.listWorkspace(workflowID.value, path); entries.value = result.items ?? []; workspacePath.value = path; workspaceUsage.value = { used: result.used_bytes, limit: result.limit_bytes }; }
async function openEntry(entry: WorkspaceEntry) { if (entry.directory) { await loadDirectory(entry.path); return; } if (entry.size > 1024 * 1024) { await downloadEntry(entry); return; } const file = await api.getWorkspaceFile(workflowID.value, entry.path); if (!file.content_type.startsWith("text/") && !file.content_type.includes("json") && !file.content_type.includes("xml")) { await downloadEntry(entry); return; } preview.value = { path: file.path, content: decodeBase64(file.content) }; }
async function downloadEntry(entry: WorkspaceEntry) { const blob = await api.downloadWorkspaceFile(workflowID.value, entry.path); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = entry.name; anchor.click(); URL.revokeObjectURL(url); }
async function upload(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; if (file.size > 100 * 1024 * 1024) { error.value = t("errors.validation"); input.value = ""; return; } const path = [workspacePath.value, file.name].filter(Boolean).join("/"); try { await api.uploadWorkspaceFile(workflowID.value, path, file); await loadDirectory(workspacePath.value); } catch { error.value = t("errors.validation"); } input.value = ""; }
async function mkdir() { const name = window.prompt(t("workflows.directoryName"))?.trim(); if (!name) return; await api.createWorkspaceDirectory(workflowID.value, [workspacePath.value, name].filter(Boolean).join("/")); await loadDirectory(workspacePath.value); }
async function clearWorkspace() { if (!workflow.value) return; const confirmation = window.prompt(`Enter “${workflow.value.name}” to clear the workspace`); if (confirmation !== workflow.value.name) return; await api.clearWorkspace(workflowID.value, confirmation); await loadDirectory(""); }
async function clone() { const url = window.prompt(t("workflows.gitURL"))?.trim(); if (!url) return; const branch = window.prompt(t("workflows.branch"), "main")?.trim() || "main"; const ssh = url.startsWith("ssh://") || /^[^@\s]+@[^:\s]+:/.test(url); const ssh_private_key = ssh ? window.prompt(t("workflows.privateKey"))?.trim() : undefined; if (ssh && !ssh_private_key) return; try { workflow.value = await api.cloneWorkspace(workflowID.value, { url, branch, ssh_private_key }); await loadDirectory(""); } catch { error.value = t("errors.validation"); } }
async function saveSettings() { if (!workflow.value) return; try { workflow.value = await api.updateWorkflow(workflowID.value, settingsForm.value, workflow.value.version); await refresh(); } catch { error.value = t("errors.conflict"); } }
async function generateCredential() { try { credential.value = await api.generateWorkflowCredential(workflowID.value); } catch { error.value = t("errors.generic"); } }
async function removeWorkflow() { if (!workflow.value || !window.confirm(`${t('common.delete')} “${workflow.value.name}”?`)) return; await api.deleteWorkflow(workflowID.value); await router.push("/workflows"); }
async function cancelRun(item: Run) { await api.cancelRun(workflowID.value, item.id); runs.value = await api.listRuns(workflowID.value); }
async function rerun(item: Run) { await api.rerunWorkflow(workflowID.value, item.id); runs.value = await api.listRuns(workflowID.value); }
async function openRun(item: Run) {
  eventController?.abort();
  selectedRun.value = item;
  runEvents.value = [];
  eventController = new AbortController();
  try { await api.streamRunEvents(workflowID.value, item.id, (event) => runEvents.value.push(event), eventController.signal); } catch (streamError) { if (!(streamError instanceof DOMException && streamError.name === "AbortError")) error.value = t("errors.generic"); }
}
function closeRun() { eventController?.abort(); eventController = undefined; selectedRun.value = undefined; runEvents.value = []; }
function addEnvironment() { settingsForm.value.environment.push({ name: "", value: "", secret: false, configured: false }); }
function removeEnvironment(index: number) { settingsForm.value.environment.splice(index, 1); }
function enableSchedule() { settingsForm.value.schedule = settingsForm.value.schedule ?? { enabled: true, frequency: "daily", hour: 9, minute: 0, weekday: 1, timezone: "Asia/Shanghai" }; }
async function openArtifact(item: Artifact) { if (item.text_preview) { preview.value = { path: item.path || item.name, content: item.text_preview }; return; } if (item.kind === "file" && !item.expired) { try { const download = await api.getArtifactDownload(workflowID.value, item.id); window.open(download.url, "_blank", "noopener,noreferrer"); } catch { error.value = t("errors.generic"); } } }
function stateLabel(state: Run["state"]) { return state === "succeeded" ? t("common.success") : state === "failed" ? t("common.failed") : state === "running" ? t("common.running") : state === "queued" ? t("common.queued") : state; }
function triggerLabel(trigger: Run["trigger"]) { return t(`workflows.${trigger}`); }
function parentPath() { const parts = workspacePath.value.split("/").filter(Boolean); parts.pop(); return parts.join("/"); }
function decodeBase64(value: string) { try { return decodeURIComponent(escape(atob(value))); } catch { return atob(value); } }
</script>

<template>
  <section class="detail-page">
    <header class="detail-hero"><button class="back-link" @click="router.push('/workflows')">← {{ t('common.back') }}</button><div v-if="workflow"><p class="eyebrow">WORKFLOW / {{ workflow.id.slice(0, 8).toUpperCase() }}</p><h1>{{ workflow.name }}</h1><p>{{ workflow.goal }}</p></div><div v-if="workflow && !workflow.deleted" class="hero-actions"><select v-model="runInputMode"><option value="text">Text</option><option value="json">JSON</option></select><input v-model="runInput" :placeholder="runInputMode === 'json' ? '{&quot;key&quot;:&quot;value&quot;}' : t('workflows.input')"><button class="button primary" :disabled="running" @click="runNow">{{ running ? t('common.running') : '▶ ' + t('workflows.runNow') }}</button></div><span v-else-if="workflow" class="engine-chip">{{ t('common.readOnly') }}</span></header>
    <ToastMessage v-if="error" kind="error" :title="t('common.failed')" :message="error" :close-label="t('common.close')" @dismiss="error = ''" /><div v-if="loading" class="quiet-state large">{{ t('common.loading') }}</div>
    <template v-else-if="workflow">
      <nav class="tabs"><button v-for="item in tabs" :key="item" :class="{ active: tab === item }" @click="tab = item">{{ t(`workflows.${item}`) }}</button></nav>
      <div v-if="tab === 'artifacts'" class="tab-content"><div class="section-heading"><div><p class="eyebrow">OUTPUT / 90 DAY FILE RETENTION</p><h2>{{ t('workflows.artifacts') }}</h2></div></div><div v-if="!artifacts.length" class="empty-inline"><span>◇</span><p>{{ t('common.empty') }}</p></div><div v-else class="artifact-list"><article v-for="item in artifacts" :key="item.id" role="button" tabindex="0" @click="openArtifact(item)" @keydown.enter="openArtifact(item)"><span class="file-icon">{{ item.kind === 'result' ? 'TXT' : 'FILE' }}</span><div><strong>{{ item.name }}</strong><small>{{ item.path || item.kind }} · {{ item.size }} B <template v-if="item.expired">· {{ t('workflows.expired') }}</template></small></div><code>{{ (item.sha256 || 'inline').slice(0, 12) }}</code></article></div></div>
      <div v-if="tab === 'workspace'" class="tab-content"><div class="section-heading"><div><p class="eyebrow">PERSISTENT / {{ Math.round(workspaceUsage.used / 1024 / 1024) }} MB / 1 GB</p><h2>{{ t('workflows.workspace') }}</h2><p class="path-line">/{{ workspacePath }}</p></div><div><button class="button ghost" @click="clone">Git clone</button><button class="button ghost" @click="mkdir">＋ {{ t('common.folder') }}</button><label class="button primary file-button">↑ {{ t('common.upload') }}<input type="file" @change="upload"></label></div></div><div class="usage-track"><i :style="{ width: `${Math.min(100, workspaceUsage.used / workspaceUsage.limit * 100)}%` }"></i></div><div class="file-browser"><button v-if="workspacePath" class="file-row" @click="loadDirectory(parentPath())"><span class="file-icon">UP</span><strong>..</strong></button><div v-for="entry in entries" :key="entry.path" class="file-row" role="button" tabindex="0" @click="openEntry(entry)" @keydown.enter="openEntry(entry)"><span class="file-icon">{{ entry.directory ? 'DIR' : 'DOC' }}</span><strong>{{ entry.name }}</strong><small>{{ entry.directory ? '—' : `${entry.size} B` }}</small><time>{{ new Date(entry.modified_at).toLocaleString() }}</time><button v-if="!entry.directory" class="text-button" :aria-label="t('common.download')" @click.stop="downloadEntry(entry)">↓</button></div><div v-if="!entries.length" class="empty-inline"><span>□</span><p>{{ t('common.empty') }}</p></div></div><button class="danger-link" @click="clearWorkspace">{{ t('workflows.clearWorkspace') }}</button></div>
      <div v-if="tab === 'history'" class="tab-content"><div class="section-heading"><div><p class="eyebrow">EXECUTION / IMMUTABLE SNAPSHOTS</p><h2>{{ t('workflows.history') }}</h2></div></div><div v-if="!runs.length" class="empty-inline"><span>◷</span><p>{{ t('workflows.noRuns') }}</p></div><div v-else class="run-table"><div class="run-row run-head"><span>{{ t('workflows.started') }}</span><span>{{ t('workflows.trigger') }}</span><span>{{ t('workflows.state') }}</span><span>{{ t('workflows.duration') }}</span><span></span></div><div v-for="item in runs" :key="item.id" class="run-row" role="button" tabindex="0" @click="openRun(item)" @keydown.enter="openRun(item)"><span><strong>{{ new Date(item.started_at || item.queued_at).toLocaleString() }}</strong><small>{{ item.id.slice(0, 8) }}</small></span><span>{{ triggerLabel(item.trigger) }}</span><span><i class="run-state" :class="item.state"></i>{{ stateLabel(item.state) }}</span><span>{{ formatDuration(item.elapsed_ms, locale as SupportedLocale) }}</span><span class="run-actions"><button v-if="item.state === 'queued' || item.state === 'running'" @click.stop="cancelRun(item)">{{ t('common.cancel') }}</button><button v-else-if="!workflow.deleted" @click.stop="rerun(item)">↻</button></span></div></div></div>
      <form v-if="tab === 'settings' && !workflow.deleted" class="tab-content settings-form" @submit.prevent="saveSettings">
        <div class="section-heading"><div><p class="eyebrow">CONFIGURATION / FUTURE RUNS</p><h2>{{ t('workflows.settings') }}</h2></div><button class="button primary">{{ t('common.save') }}</button></div>
        <details class="settings-section" open><summary><span class="section-number">01</span><h3>{{ t('workflows.basic') }}</h3></summary><div class="form-grid"><label>{{ t('workflows.name') }}<input v-model="settingsForm.name" required></label><label>{{ t('workflows.expert') }}<select v-model="settingsForm.expert_id"><option :value="undefined">{{ t('sessions.noExpert') }}</option><option v-for="expert in experts" :key="expert.id" :value="expert.id">{{ expert.name }}</option></select></label><label class="full">{{ t('workflows.goal') }}<textarea v-model="settingsForm.goal" rows="7" required></textarea></label></div></details>
        <details class="settings-section"><summary><span class="section-number">02</span><h3>{{ t('workflows.execution') }}</h3></summary><div class="form-grid"><label>{{ t('settings.model') }}<select v-model="settingsForm.provider_model_id"><option :value="undefined">{{ t('workflows.personalDefault') }}</option><option v-for="model in models" :key="model.id" :value="model.id" :disabled="modelIncompatible(model)">{{ model.connection_name }} / {{ model.display_name }}</option></select></label><label>{{ t('workflows.runtime') }}<select v-model="settingsForm.runtime_engine"><option :value="undefined">{{ t('workflows.personalDefault') }}</option><option v-for="runtime in runtimes" :key="runtime.name" :value="runtime.name" :disabled="!runtime.available">{{ runtime.name }} · {{ runtime.available ? t('settings.available') : t('settings.unavailable') }}</option></select></label><div class="full"><div v-for="(variable, index) in settingsForm.environment" :key="index" class="inline-fields"><input v-model="variable.name" placeholder="VARIABLE_NAME"><input v-model="variable.value" :type="variable.secret ? 'password' : 'text'" :placeholder="variable.configured && variable.secret ? t('settings.keepSecret') : t('settings.value')"><label><input v-model="variable.secret" type="checkbox"> Secret</label><button type="button" class="text-button" @click="removeEnvironment(index)">×</button></div><button type="button" class="button ghost" @click="addEnvironment">＋ {{ t('workflows.environment') }}</button></div></div></details>
        <details class="settings-section"><summary><span class="section-number">03</span><h3>{{ t('workflows.schedule') }}</h3></summary><button v-if="!settingsForm.schedule" type="button" class="button ghost" @click="enableSchedule">{{ t('workflows.enableSchedule') }}</button><div v-else class="form-grid"><label><input v-model="settingsForm.schedule.enabled" type="checkbox"> {{ t('common.enabled') }}</label><label>{{ t('workflows.frequency') }}<select v-model="settingsForm.schedule.frequency"><option value="hourly">{{ t('workflows.hourly') }}</option><option value="daily">{{ t('workflows.daily') }}</option><option value="weekly">{{ t('workflows.weekly') }}</option></select></label><label>{{ t('workflows.hour') }}<input v-model.number="settingsForm.schedule.hour" type="number" min="0" max="23"></label><label>{{ t('workflows.minute') }}<input v-model.number="settingsForm.schedule.minute" type="number" min="0" max="59"></label><label v-if="settingsForm.schedule.frequency === 'weekly'">{{ t('workflows.weekday') }}<input v-model.number="settingsForm.schedule.weekday" type="number" min="0" max="6"></label><label>{{ t('workflows.timezone') }}<input v-model="settingsForm.schedule.timezone"></label></div></details>
        <details class="settings-section"><summary><span class="section-number">04</span><h3>{{ t('workflows.apiCredential') }}</h3></summary><p class="muted">HTTP Basic: API Key / API Secret · POST /api/v1/workflows/{{ workflow.id }}/runs</p><button type="button" class="button ghost" @click="generateCredential">{{ workflow.api_credential_configured ? t('workflows.regenerate') : t('workflows.generate') }}</button><div v-if="credential" class="secret-reveal"><p>{{ t('workflows.copySecret') }}</p><code>{{ credential.api_key }}</code><code>{{ credential.api_secret }}</code><code>curl -u '{{ credential.api_key }}:{{ credential.api_secret }}' -H 'Idempotency-Key: unique-request' -H 'Content-Type: application/json' -d '{"text_input":"Run now"}' {{ origin }}/api/v1/workflows/{{ workflow.id }}/runs</code></div></details>
        <details class="settings-section"><summary><span class="section-number">05</span><h3>{{ t('workflows.gitSource') }}</h3></summary><p v-if="workflow.git_source" class="muted">{{ workflow.git_source.url }} · {{ workflow.git_source.branch }} · {{ workflow.git_source.private_ssh ? 'SSH' : 'HTTPS' }}</p><p v-else class="muted">{{ t('workflows.gitDescription') }}</p><button type="button" class="button ghost" @click="tab = 'workspace'">{{ t('workflows.openWorkspace') }}</button></details>
        <section class="danger-zone"><h3>{{ t('workflows.deleteTitle') }}</h3><p>{{ t('workflows.deleteDescription') }}</p><button type="button" class="button danger" @click="removeWorkflow">{{ t('common.delete') }}</button></section>
      </form>
    </template>
  </section>
  <div v-if="preview" class="modal-layer" @click.self="preview = undefined"><div class="modal-card preview-card"><div class="section-heading"><h2>{{ preview.path }}</h2><button class="icon-button" @click="preview = undefined">×</button></div><pre>{{ preview.content }}</pre></div></div>
  <div v-if="selectedRun" class="modal-layer" @click.self="closeRun"><div class="modal-card preview-card"><div class="section-heading"><div><p class="eyebrow">RUN / {{ selectedRun.id.slice(0, 8) }}</p><h2>{{ stateLabel(selectedRun.state) }}</h2></div><button class="icon-button" @click="closeRun">×</button></div><dl class="run-detail-grid"><dt>{{ t('workflows.queuedAt') }}</dt><dd>{{ new Date(selectedRun.queued_at).toLocaleString() }}</dd><dt>{{ t('workflows.startedAt') }}</dt><dd>{{ selectedRun.started_at ? new Date(selectedRun.started_at).toLocaleString() : '—' }}</dd><dt>{{ t('workflows.endedAt') }}</dt><dd>{{ selectedRun.ended_at ? new Date(selectedRun.ended_at).toLocaleString() : '—' }}</dd><dt>{{ t('workflows.trigger') }}</dt><dd>{{ triggerLabel(selectedRun.trigger) }}</dd></dl><h3>{{ t('workflows.inputLabel') }}</h3><pre>{{ selectedRun.text_input || JSON.stringify(selectedRun.json_input, null, 2) || '—' }}</pre><h3>{{ t('workflows.eventsLabel') }}</h3><div class="event-stream"><div v-for="event in runEvents" :key="event.sequence"><code>{{ event.sequence }} · {{ event.type }}</code><pre>{{ JSON.stringify(event.payload, null, 2) }}</pre></div><p v-if="!runEvents.length" class="muted">{{ t('common.loading') }}</p></div><h3>{{ t('workflows.runArtifacts') }}</h3><div v-if="selectedRunArtifacts.length" class="artifact-list"><article v-for="item in selectedRunArtifacts" :key="item.id" role="button" tabindex="0" @click="openArtifact(item)" @keydown.enter="openArtifact(item)"><span class="file-icon">{{ item.kind === 'result' ? 'TXT' : 'FILE' }}</span><div><strong>{{ item.name }}</strong><small>{{ item.path || item.kind }} · {{ item.size }} B</small></div><code>{{ (item.sha256 || 'inline').slice(0, 12) }}</code></article></div><p v-else class="muted">{{ t('workflows.noRunArtifacts') }}</p><h3>{{ t('workflows.snapshotLabel') }}</h3><pre>{{ JSON.stringify(selectedRun.workflow_snapshot, null, 2) }}</pre><h3>{{ t('workflows.resultLabel') }}</h3><pre>{{ selectedRun.final_text || JSON.stringify(selectedRun.final_json, null, 2) || selectedRun.error || '—' }}</pre></div></div>
</template>
