// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: sourcecontrol/v1/source_control.proto

package sourcecontrolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SourceControlService_ListSourceControlProviders_FullMethodName        = "/sourcecontrol.v1.SourceControlService/ListSourceControlProviders"
	SourceControlService_GetSourceControlProvider_FullMethodName          = "/sourcecontrol.v1.SourceControlService/GetSourceControlProvider"
	SourceControlService_RegisterSourceControlProvider_FullMethodName     = "/sourcecontrol.v1.SourceControlService/RegisterSourceControlProvider"
	SourceControlService_ChangeSourceControlProviderStatus_FullMethodName = "/sourcecontrol.v1.SourceControlService/ChangeSourceControlProviderStatus"
	SourceControlService_ListRepositoryBindings_FullMethodName            = "/sourcecontrol.v1.SourceControlService/ListRepositoryBindings"
	SourceControlService_GetRepositoryBinding_FullMethodName              = "/sourcecontrol.v1.SourceControlService/GetRepositoryBinding"
	SourceControlService_RegisterRepositoryBinding_FullMethodName         = "/sourcecontrol.v1.SourceControlService/RegisterRepositoryBinding"
	SourceControlService_UpdateRepositoryBinding_FullMethodName           = "/sourcecontrol.v1.SourceControlService/UpdateRepositoryBinding"
	SourceControlService_ValidateRepositoryBinding_FullMethodName         = "/sourcecontrol.v1.SourceControlService/ValidateRepositoryBinding"
)

// SourceControlServiceClient is the client API for SourceControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SourceControlServiceClient interface {
	ListSourceControlProviders(ctx context.Context, in *ListSourceControlProvidersRequest, opts ...grpc.CallOption) (*ListSourceControlProvidersResponse, error)
	GetSourceControlProvider(ctx context.Context, in *GetSourceControlProviderRequest, opts ...grpc.CallOption) (*SourceControlProvider, error)
	RegisterSourceControlProvider(ctx context.Context, in *RegisterSourceControlProviderRequest, opts ...grpc.CallOption) (*SourceControlProvider, error)
	ChangeSourceControlProviderStatus(ctx context.Context, in *ChangeSourceControlProviderStatusRequest, opts ...grpc.CallOption) (*SourceControlProvider, error)
	ListRepositoryBindings(ctx context.Context, in *ListRepositoryBindingsRequest, opts ...grpc.CallOption) (*ListRepositoryBindingsResponse, error)
	GetRepositoryBinding(ctx context.Context, in *GetRepositoryBindingRequest, opts ...grpc.CallOption) (*RepositoryBinding, error)
	RegisterRepositoryBinding(ctx context.Context, in *RegisterRepositoryBindingRequest, opts ...grpc.CallOption) (*RepositoryBinding, error)
	UpdateRepositoryBinding(ctx context.Context, in *UpdateRepositoryBindingRequest, opts ...grpc.CallOption) (*RepositoryBinding, error)
	ValidateRepositoryBinding(ctx context.Context, in *ValidateRepositoryBindingRequest, opts ...grpc.CallOption) (*RepositoryBinding, error)
}

type sourceControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceControlServiceClient(cc grpc.ClientConnInterface) SourceControlServiceClient {
	return &sourceControlServiceClient{cc}
}

func (c *sourceControlServiceClient) ListSourceControlProviders(ctx context.Context, in *ListSourceControlProvidersRequest, opts ...grpc.CallOption) (*ListSourceControlProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourceControlProvidersResponse)
	err := c.cc.Invoke(ctx, SourceControlService_ListSourceControlProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceControlServiceClient) GetSourceControlProvider(ctx context.Context, in *GetSourceControlProviderRequest, opts ...grpc.CallOption) (*SourceControlProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceControlProvider)
	err := c.cc.Invoke(ctx, SourceControlService_GetSourceControlProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceControlServiceClient) RegisterSourceControlProvider(ctx context.Context, in *RegisterSourceControlProviderRequest, opts ...grpc.CallOption) (*SourceControlProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceControlProvider)
	err := c.cc.Invoke(ctx, SourceControlService_RegisterSourceControlProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceControlServiceClient) ChangeSourceControlProviderStatus(ctx context.Context, in *ChangeSourceControlProviderStatusRequest, opts ...grpc.CallOption) (*SourceControlProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceControlProvider)
	err := c.cc.Invoke(ctx, SourceControlService_ChangeSourceControlProviderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceControlServiceClient) ListRepositoryBindings(ctx context.Context, in *ListRepositoryBindingsRequest, opts ...grpc.CallOption) (*ListRepositoryBindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoryBindingsResponse)
	err := c.cc.Invoke(ctx, SourceControlService_ListRepositoryBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceControlServiceClient) GetRepositoryBinding(ctx context.Context, in *GetRepositoryBindingRequest, opts ...grpc.CallOption) (*RepositoryBinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryBinding)
	err := c.cc.Invoke(ctx, SourceControlService_GetRepositoryBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceControlServiceClient) RegisterRepositoryBinding(ctx context.Context, in *RegisterRepositoryBindingRequest, opts ...grpc.CallOption) (*RepositoryBinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryBinding)
	err := c.cc.Invoke(ctx, SourceControlService_RegisterRepositoryBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceControlServiceClient) UpdateRepositoryBinding(ctx context.Context, in *UpdateRepositoryBindingRequest, opts ...grpc.CallOption) (*RepositoryBinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryBinding)
	err := c.cc.Invoke(ctx, SourceControlService_UpdateRepositoryBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceControlServiceClient) ValidateRepositoryBinding(ctx context.Context, in *ValidateRepositoryBindingRequest, opts ...grpc.CallOption) (*RepositoryBinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryBinding)
	err := c.cc.Invoke(ctx, SourceControlService_ValidateRepositoryBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceControlServiceServer is the server API for SourceControlService service.
// All implementations must embed UnimplementedSourceControlServiceServer
// for forward compatibility.
type SourceControlServiceServer interface {
	ListSourceControlProviders(context.Context, *ListSourceControlProvidersRequest) (*ListSourceControlProvidersResponse, error)
	GetSourceControlProvider(context.Context, *GetSourceControlProviderRequest) (*SourceControlProvider, error)
	RegisterSourceControlProvider(context.Context, *RegisterSourceControlProviderRequest) (*SourceControlProvider, error)
	ChangeSourceControlProviderStatus(context.Context, *ChangeSourceControlProviderStatusRequest) (*SourceControlProvider, error)
	ListRepositoryBindings(context.Context, *ListRepositoryBindingsRequest) (*ListRepositoryBindingsResponse, error)
	GetRepositoryBinding(context.Context, *GetRepositoryBindingRequest) (*RepositoryBinding, error)
	RegisterRepositoryBinding(context.Context, *RegisterRepositoryBindingRequest) (*RepositoryBinding, error)
	UpdateRepositoryBinding(context.Context, *UpdateRepositoryBindingRequest) (*RepositoryBinding, error)
	ValidateRepositoryBinding(context.Context, *ValidateRepositoryBindingRequest) (*RepositoryBinding, error)
	mustEmbedUnimplementedSourceControlServiceServer()
}

// UnimplementedSourceControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceControlServiceServer struct{}

func (UnimplementedSourceControlServiceServer) ListSourceControlProviders(context.Context, *ListSourceControlProvidersRequest) (*ListSourceControlProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSourceControlProviders not implemented")
}
func (UnimplementedSourceControlServiceServer) GetSourceControlProvider(context.Context, *GetSourceControlProviderRequest) (*SourceControlProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSourceControlProvider not implemented")
}
func (UnimplementedSourceControlServiceServer) RegisterSourceControlProvider(context.Context, *RegisterSourceControlProviderRequest) (*SourceControlProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSourceControlProvider not implemented")
}
func (UnimplementedSourceControlServiceServer) ChangeSourceControlProviderStatus(context.Context, *ChangeSourceControlProviderStatusRequest) (*SourceControlProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeSourceControlProviderStatus not implemented")
}
func (UnimplementedSourceControlServiceServer) ListRepositoryBindings(context.Context, *ListRepositoryBindingsRequest) (*ListRepositoryBindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepositoryBindings not implemented")
}
func (UnimplementedSourceControlServiceServer) GetRepositoryBinding(context.Context, *GetRepositoryBindingRequest) (*RepositoryBinding, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepositoryBinding not implemented")
}
func (UnimplementedSourceControlServiceServer) RegisterRepositoryBinding(context.Context, *RegisterRepositoryBindingRequest) (*RepositoryBinding, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRepositoryBinding not implemented")
}
func (UnimplementedSourceControlServiceServer) UpdateRepositoryBinding(context.Context, *UpdateRepositoryBindingRequest) (*RepositoryBinding, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepositoryBinding not implemented")
}
func (UnimplementedSourceControlServiceServer) ValidateRepositoryBinding(context.Context, *ValidateRepositoryBindingRequest) (*RepositoryBinding, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRepositoryBinding not implemented")
}
func (UnimplementedSourceControlServiceServer) mustEmbedUnimplementedSourceControlServiceServer() {}
func (UnimplementedSourceControlServiceServer) testEmbeddedByValue()                              {}

// UnsafeSourceControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceControlServiceServer will
// result in compilation errors.
type UnsafeSourceControlServiceServer interface {
	mustEmbedUnimplementedSourceControlServiceServer()
}

func RegisterSourceControlServiceServer(s grpc.ServiceRegistrar, srv SourceControlServiceServer) {
	// If the following call panics, it indicates UnimplementedSourceControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceControlService_ServiceDesc, srv)
}

func _SourceControlService_ListSourceControlProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourceControlProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).ListSourceControlProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_ListSourceControlProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).ListSourceControlProviders(ctx, req.(*ListSourceControlProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceControlService_GetSourceControlProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSourceControlProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).GetSourceControlProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_GetSourceControlProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).GetSourceControlProvider(ctx, req.(*GetSourceControlProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceControlService_RegisterSourceControlProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSourceControlProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).RegisterSourceControlProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_RegisterSourceControlProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).RegisterSourceControlProvider(ctx, req.(*RegisterSourceControlProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceControlService_ChangeSourceControlProviderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeSourceControlProviderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).ChangeSourceControlProviderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_ChangeSourceControlProviderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).ChangeSourceControlProviderStatus(ctx, req.(*ChangeSourceControlProviderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceControlService_ListRepositoryBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoryBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).ListRepositoryBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_ListRepositoryBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).ListRepositoryBindings(ctx, req.(*ListRepositoryBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceControlService_GetRepositoryBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).GetRepositoryBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_GetRepositoryBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).GetRepositoryBinding(ctx, req.(*GetRepositoryBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceControlService_RegisterRepositoryBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRepositoryBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).RegisterRepositoryBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_RegisterRepositoryBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).RegisterRepositoryBinding(ctx, req.(*RegisterRepositoryBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceControlService_UpdateRepositoryBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepositoryBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).UpdateRepositoryBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_UpdateRepositoryBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).UpdateRepositoryBinding(ctx, req.(*UpdateRepositoryBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceControlService_ValidateRepositoryBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRepositoryBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceControlServiceServer).ValidateRepositoryBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceControlService_ValidateRepositoryBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceControlServiceServer).ValidateRepositoryBinding(ctx, req.(*ValidateRepositoryBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceControlService_ServiceDesc is the grpc.ServiceDesc for SourceControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sourcecontrol.v1.SourceControlService",
	HandlerType: (*SourceControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSourceControlProviders",
			Handler:    _SourceControlService_ListSourceControlProviders_Handler,
		},
		{
			MethodName: "GetSourceControlProvider",
			Handler:    _SourceControlService_GetSourceControlProvider_Handler,
		},
		{
			MethodName: "RegisterSourceControlProvider",
			Handler:    _SourceControlService_RegisterSourceControlProvider_Handler,
		},
		{
			MethodName: "ChangeSourceControlProviderStatus",
			Handler:    _SourceControlService_ChangeSourceControlProviderStatus_Handler,
		},
		{
			MethodName: "ListRepositoryBindings",
			Handler:    _SourceControlService_ListRepositoryBindings_Handler,
		},
		{
			MethodName: "GetRepositoryBinding",
			Handler:    _SourceControlService_GetRepositoryBinding_Handler,
		},
		{
			MethodName: "RegisterRepositoryBinding",
			Handler:    _SourceControlService_RegisterRepositoryBinding_Handler,
		},
		{
			MethodName: "UpdateRepositoryBinding",
			Handler:    _SourceControlService_UpdateRepositoryBinding_Handler,
		},
		{
			MethodName: "ValidateRepositoryBinding",
			Handler:    _SourceControlService_ValidateRepositoryBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sourcecontrol/v1/source_control.proto",
}
