// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"agent-platform/backend/internal/infrastructure/gormdb"
	"agent-platform/backend/internal/platformconfig"
	"agent-platform/backend/internal/wiring/execution"
	"agent-platform/backend/internal/wiring/workerprocess"
	"agent-platform/backend/internal/wiring/workflow"
	"context"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

// Injectors from wire.go:

func initializeWorker(contextContext context.Context, config platformconfig.Config, database *gormdb.Database, logger *slog.Logger) (*kratos.App, error) {
	manager := workflow.NewManager(database)
	service := execution.NewService(database, manager)
	v, err := workerprocess.NewServers(database, service, config)
	if err != nil {
		return nil, err
	}
	app := workerprocess.NewApp(contextContext, config, logger, v)
	return app, nil
}
