// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modelcatalog/v1/model_catalog.proto

package modelcatalogv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCredentialProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialProfilesRequest) Reset() {
	*x = ListCredentialProfilesRequest{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialProfilesRequest) ProtoMessage() {}

func (x *ListCredentialProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListCredentialProfilesRequest) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{0}
}

type ListCredentialProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CredentialProfile   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialProfilesResponse) Reset() {
	*x = ListCredentialProfilesResponse{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialProfilesResponse) ProtoMessage() {}

func (x *ListCredentialProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListCredentialProfilesResponse) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListCredentialProfilesResponse) GetItems() []*CredentialProfile {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetCredentialProfileRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CredentialProfileId string                 `protobuf:"bytes,1,opt,name=credential_profile_id,json=credentialProfileId,proto3" json:"credential_profile_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCredentialProfileRequest) Reset() {
	*x = GetCredentialProfileRequest{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialProfileRequest) ProtoMessage() {}

func (x *GetCredentialProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialProfileRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialProfileRequest) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetCredentialProfileRequest) GetCredentialProfileId() string {
	if x != nil {
		return x.CredentialProfileId
	}
	return ""
}

type GetCredentialProfileResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CredentialProfile *CredentialProfile     `protobuf:"bytes,1,opt,name=credential_profile,json=credentialProfile,proto3" json:"credential_profile,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCredentialProfileResponse) Reset() {
	*x = GetCredentialProfileResponse{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialProfileResponse) ProtoMessage() {}

func (x *GetCredentialProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialProfileResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialProfileResponse) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetCredentialProfileResponse) GetCredentialProfile() *CredentialProfile {
	if x != nil {
		return x.CredentialProfile
	}
	return nil
}

type RegisterCredentialProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        *string                `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	SecretRef     string                 `protobuf:"bytes,4,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCredentialProfileRequest) Reset() {
	*x = RegisterCredentialProfileRequest{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCredentialProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCredentialProfileRequest) ProtoMessage() {}

func (x *RegisterCredentialProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCredentialProfileRequest.ProtoReflect.Descriptor instead.
func (*RegisterCredentialProfileRequest) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterCredentialProfileRequest) GetTeamId() string {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return ""
}

func (x *RegisterCredentialProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterCredentialProfileRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RegisterCredentialProfileRequest) GetSecretRef() string {
	if x != nil {
		return x.SecretRef
	}
	return ""
}

type RegisterCredentialProfileResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CredentialProfile *CredentialProfile     `protobuf:"bytes,1,opt,name=credential_profile,json=credentialProfile,proto3" json:"credential_profile,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterCredentialProfileResponse) Reset() {
	*x = RegisterCredentialProfileResponse{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCredentialProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCredentialProfileResponse) ProtoMessage() {}

func (x *RegisterCredentialProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCredentialProfileResponse.ProtoReflect.Descriptor instead.
func (*RegisterCredentialProfileResponse) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterCredentialProfileResponse) GetCredentialProfile() *CredentialProfile {
	if x != nil {
		return x.CredentialProfile
	}
	return nil
}

type ChangeCredentialProfileStatusRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CredentialProfileId string                 `protobuf:"bytes,1,opt,name=credential_profile_id,json=credentialProfileId,proto3" json:"credential_profile_id,omitempty"`
	Enabled             bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChangeCredentialProfileStatusRequest) Reset() {
	*x = ChangeCredentialProfileStatusRequest{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeCredentialProfileStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCredentialProfileStatusRequest) ProtoMessage() {}

func (x *ChangeCredentialProfileStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCredentialProfileStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeCredentialProfileStatusRequest) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeCredentialProfileStatusRequest) GetCredentialProfileId() string {
	if x != nil {
		return x.CredentialProfileId
	}
	return ""
}

func (x *ChangeCredentialProfileStatusRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ChangeCredentialProfileStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CredentialProfile *CredentialProfile     `protobuf:"bytes,1,opt,name=credential_profile,json=credentialProfile,proto3" json:"credential_profile,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChangeCredentialProfileStatusResponse) Reset() {
	*x = ChangeCredentialProfileStatusResponse{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeCredentialProfileStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCredentialProfileStatusResponse) ProtoMessage() {}

func (x *ChangeCredentialProfileStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCredentialProfileStatusResponse.ProtoReflect.Descriptor instead.
func (*ChangeCredentialProfileStatusResponse) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeCredentialProfileStatusResponse) GetCredentialProfile() *CredentialProfile {
	if x != nil {
		return x.CredentialProfile
	}
	return nil
}

type ListConfiguredModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfiguredModelsRequest) Reset() {
	*x = ListConfiguredModelsRequest{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfiguredModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfiguredModelsRequest) ProtoMessage() {}

func (x *ListConfiguredModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfiguredModelsRequest.ProtoReflect.Descriptor instead.
func (*ListConfiguredModelsRequest) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{8}
}

type ListConfiguredModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfiguredModel     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfiguredModelsResponse) Reset() {
	*x = ListConfiguredModelsResponse{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfiguredModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfiguredModelsResponse) ProtoMessage() {}

func (x *ListConfiguredModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfiguredModelsResponse.ProtoReflect.Descriptor instead.
func (*ListConfiguredModelsResponse) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *ListConfiguredModelsResponse) GetItems() []*ConfiguredModel {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetConfiguredModelRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredModelId string                 `protobuf:"bytes,1,opt,name=configured_model_id,json=configuredModelId,proto3" json:"configured_model_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetConfiguredModelRequest) Reset() {
	*x = GetConfiguredModelRequest{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfiguredModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfiguredModelRequest) ProtoMessage() {}

func (x *GetConfiguredModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfiguredModelRequest.ProtoReflect.Descriptor instead.
func (*GetConfiguredModelRequest) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *GetConfiguredModelRequest) GetConfiguredModelId() string {
	if x != nil {
		return x.ConfiguredModelId
	}
	return ""
}

type GetConfiguredModelResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredModel *ConfiguredModel       `protobuf:"bytes,1,opt,name=configured_model,json=configuredModel,proto3" json:"configured_model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConfiguredModelResponse) Reset() {
	*x = GetConfiguredModelResponse{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfiguredModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfiguredModelResponse) ProtoMessage() {}

func (x *GetConfiguredModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfiguredModelResponse.ProtoReflect.Descriptor instead.
func (*GetConfiguredModelResponse) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfiguredModelResponse) GetConfiguredModel() *ConfiguredModel {
	if x != nil {
		return x.ConfiguredModel
	}
	return nil
}

type RegisterConfiguredModelRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ModelId             string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Endpoint            string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CredentialProfileId string                 `protobuf:"bytes,4,opt,name=credential_profile_id,json=credentialProfileId,proto3" json:"credential_profile_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterConfiguredModelRequest) Reset() {
	*x = RegisterConfiguredModelRequest{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConfiguredModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConfiguredModelRequest) ProtoMessage() {}

func (x *RegisterConfiguredModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConfiguredModelRequest.ProtoReflect.Descriptor instead.
func (*RegisterConfiguredModelRequest) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterConfiguredModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterConfiguredModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RegisterConfiguredModelRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterConfiguredModelRequest) GetCredentialProfileId() string {
	if x != nil {
		return x.CredentialProfileId
	}
	return ""
}

type RegisterConfiguredModelResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredModel *ConfiguredModel       `protobuf:"bytes,1,opt,name=configured_model,json=configuredModel,proto3" json:"configured_model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterConfiguredModelResponse) Reset() {
	*x = RegisterConfiguredModelResponse{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConfiguredModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConfiguredModelResponse) ProtoMessage() {}

func (x *RegisterConfiguredModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConfiguredModelResponse.ProtoReflect.Descriptor instead.
func (*RegisterConfiguredModelResponse) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterConfiguredModelResponse) GetConfiguredModel() *ConfiguredModel {
	if x != nil {
		return x.ConfiguredModel
	}
	return nil
}

type ChangeConfiguredModelStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredModelId string                 `protobuf:"bytes,1,opt,name=configured_model_id,json=configuredModelId,proto3" json:"configured_model_id,omitempty"`
	Enabled           bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChangeConfiguredModelStatusRequest) Reset() {
	*x = ChangeConfiguredModelStatusRequest{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeConfiguredModelStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeConfiguredModelStatusRequest) ProtoMessage() {}

func (x *ChangeConfiguredModelStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeConfiguredModelStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeConfiguredModelStatusRequest) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeConfiguredModelStatusRequest) GetConfiguredModelId() string {
	if x != nil {
		return x.ConfiguredModelId
	}
	return ""
}

func (x *ChangeConfiguredModelStatusRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ChangeConfiguredModelStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredModel *ConfiguredModel       `protobuf:"bytes,1,opt,name=configured_model,json=configuredModel,proto3" json:"configured_model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangeConfiguredModelStatusResponse) Reset() {
	*x = ChangeConfiguredModelStatusResponse{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeConfiguredModelStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeConfiguredModelStatusResponse) ProtoMessage() {}

func (x *ChangeConfiguredModelStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeConfiguredModelStatusResponse.ProtoReflect.Descriptor instead.
func (*ChangeConfiguredModelStatusResponse) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *ChangeConfiguredModelStatusResponse) GetConfiguredModel() *ConfiguredModel {
	if x != nil {
		return x.ConfiguredModel
	}
	return nil
}

type CredentialProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId           *string                `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Kind             string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	SecretConfigured bool                   `protobuf:"varint,5,opt,name=secret_configured,json=secretConfigured,proto3" json:"secret_configured,omitempty"`
	Enabled          bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version          int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CredentialProfile) Reset() {
	*x = CredentialProfile{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialProfile) ProtoMessage() {}

func (x *CredentialProfile) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialProfile.ProtoReflect.Descriptor instead.
func (*CredentialProfile) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *CredentialProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CredentialProfile) GetTeamId() string {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return ""
}

func (x *CredentialProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialProfile) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CredentialProfile) GetSecretConfigured() bool {
	if x != nil {
		return x.SecretConfigured
	}
	return false
}

func (x *CredentialProfile) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CredentialProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CredentialProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CredentialProfile) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ConfiguredModel struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModelId             string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Endpoint            string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CredentialProfileId string                 `protobuf:"bytes,5,opt,name=credential_profile_id,json=credentialProfileId,proto3" json:"credential_profile_id,omitempty"`
	Enabled             bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version             int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfiguredModel) Reset() {
	*x = ConfiguredModel{}
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfiguredModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfiguredModel) ProtoMessage() {}

func (x *ConfiguredModel) ProtoReflect() protoreflect.Message {
	mi := &file_modelcatalog_v1_model_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfiguredModel.ProtoReflect.Descriptor instead.
func (*ConfiguredModel) Descriptor() ([]byte, []int) {
	return file_modelcatalog_v1_model_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *ConfiguredModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfiguredModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfiguredModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ConfiguredModel) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ConfiguredModel) GetCredentialProfileId() string {
	if x != nil {
		return x.CredentialProfileId
	}
	return ""
}

func (x *ConfiguredModel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConfiguredModel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfiguredModel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfiguredModel) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_modelcatalog_v1_model_catalog_proto protoreflect.FileDescriptor

const file_modelcatalog_v1_model_catalog_proto_rawDesc = "" +
	"\n" +
	"#modelcatalog/v1/model_catalog.proto\x12\x0fmodelcatalog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x1f\n" +
	"\x1dListCredentialProfilesRequest\"Z\n" +
	"\x1eListCredentialProfilesResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".modelcatalog.v1.CredentialProfileR\x05items\"Q\n" +
	"\x1bGetCredentialProfileRequest\x122\n" +
	"\x15credential_profile_id\x18\x01 \x01(\tR\x13credentialProfileId\"q\n" +
	"\x1cGetCredentialProfileResponse\x12Q\n" +
	"\x12credential_profile\x18\x01 \x01(\v2\".modelcatalog.v1.CredentialProfileR\x11credentialProfile\"\x93\x01\n" +
	" RegisterCredentialProfileRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tH\x00R\x06teamId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"secret_ref\x18\x04 \x01(\tR\tsecretRefB\n" +
	"\n" +
	"\b_team_id\"v\n" +
	"!RegisterCredentialProfileResponse\x12Q\n" +
	"\x12credential_profile\x18\x01 \x01(\v2\".modelcatalog.v1.CredentialProfileR\x11credentialProfile\"t\n" +
	"$ChangeCredentialProfileStatusRequest\x122\n" +
	"\x15credential_profile_id\x18\x01 \x01(\tR\x13credentialProfileId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"z\n" +
	"%ChangeCredentialProfileStatusResponse\x12Q\n" +
	"\x12credential_profile\x18\x01 \x01(\v2\".modelcatalog.v1.CredentialProfileR\x11credentialProfile\"\x1d\n" +
	"\x1bListConfiguredModelsRequest\"V\n" +
	"\x1cListConfiguredModelsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .modelcatalog.v1.ConfiguredModelR\x05items\"K\n" +
	"\x19GetConfiguredModelRequest\x12.\n" +
	"\x13configured_model_id\x18\x01 \x01(\tR\x11configuredModelId\"i\n" +
	"\x1aGetConfiguredModelResponse\x12K\n" +
	"\x10configured_model\x18\x01 \x01(\v2 .modelcatalog.v1.ConfiguredModelR\x0fconfiguredModel\"\x9f\x01\n" +
	"\x1eRegisterConfiguredModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x122\n" +
	"\x15credential_profile_id\x18\x04 \x01(\tR\x13credentialProfileId\"n\n" +
	"\x1fRegisterConfiguredModelResponse\x12K\n" +
	"\x10configured_model\x18\x01 \x01(\v2 .modelcatalog.v1.ConfiguredModelR\x0fconfiguredModel\"n\n" +
	"\"ChangeConfiguredModelStatusRequest\x12.\n" +
	"\x13configured_model_id\x18\x01 \x01(\tR\x11configuredModelId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"r\n" +
	"#ChangeConfiguredModelStatusResponse\x12K\n" +
	"\x10configured_model\x18\x01 \x01(\v2 .modelcatalog.v1.ConfiguredModelR\x0fconfiguredModel\"\xcc\x02\n" +
	"\x11CredentialProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ateam_id\x18\x02 \x01(\tH\x00R\x06teamId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12+\n" +
	"\x11secret_configured\x18\x05 \x01(\bR\x10secretConfigured\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversionB\n" +
	"\n" +
	"\b_team_id\"\xca\x02\n" +
	"\x0fConfiguredModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x122\n" +
	"\x15credential_profile_id\x18\x05 \x01(\tR\x13credentialProfileId\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion2\xb5\v\n" +
	"\x13ModelCatalogService\x12\x9a\x01\n" +
	"\x16ListCredentialProfiles\x12..modelcatalog.v1.ListCredentialProfilesRequest\x1a/.modelcatalog.v1.ListCredentialProfilesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/credential-profiles\x12\xa1\x01\n" +
	"\x14GetCredentialProfile\x12,.modelcatalog.v1.GetCredentialProfileRequest\x1a\".modelcatalog.v1.CredentialProfile\"7\x82\xd3\xe4\x93\x021\x12//v1/credential-profiles/{credential_profile_id}\x12\xb2\x01\n" +
	"\x19RegisterCredentialProfile\x121.modelcatalog.v1.RegisterCredentialProfileRequest\x1a\".modelcatalog.v1.CredentialProfile\">\x92A\x19r\x17\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/credential-profiles\x12\xe9\x01\n" +
	"\x1dChangeCredentialProfileStatus\x125.modelcatalog.v1.ChangeCredentialProfileStatusRequest\x1a\".modelcatalog.v1.CredentialProfile\"m\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02;:\x01*26/v1/credential-profiles/{credential_profile_id}/status\x12\x92\x01\n" +
	"\x14ListConfiguredModels\x12,.modelcatalog.v1.ListConfiguredModelsRequest\x1a-.modelcatalog.v1.ListConfiguredModelsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/configured-models\x12\x97\x01\n" +
	"\x12GetConfiguredModel\x12*.modelcatalog.v1.GetConfiguredModelRequest\x1a .modelcatalog.v1.ConfiguredModel\"3\x82\xd3\xe4\x93\x02-\x12+/v1/configured-models/{configured_model_id}\x12\xaa\x01\n" +
	"\x17RegisterConfiguredModel\x12/.modelcatalog.v1.RegisterConfiguredModelRequest\x1a .modelcatalog.v1.ConfiguredModel\"<\x92A\x19r\x17\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/configured-models\x12\xdf\x01\n" +
	"\x1bChangeConfiguredModelStatus\x123.modelcatalog.v1.ChangeConfiguredModelStatusRequest\x1a .modelcatalog.v1.ConfiguredModel\"i\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x027:\x01*22/v1/configured-models/{configured_model_id}/statusB;Z9agent-platform/backend/api/modelcatalog/v1;modelcatalogv1b\x06proto3"

var (
	file_modelcatalog_v1_model_catalog_proto_rawDescOnce sync.Once
	file_modelcatalog_v1_model_catalog_proto_rawDescData []byte
)

func file_modelcatalog_v1_model_catalog_proto_rawDescGZIP() []byte {
	file_modelcatalog_v1_model_catalog_proto_rawDescOnce.Do(func() {
		file_modelcatalog_v1_model_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modelcatalog_v1_model_catalog_proto_rawDesc), len(file_modelcatalog_v1_model_catalog_proto_rawDesc)))
	})
	return file_modelcatalog_v1_model_catalog_proto_rawDescData
}

var file_modelcatalog_v1_model_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_modelcatalog_v1_model_catalog_proto_goTypes = []any{
	(*ListCredentialProfilesRequest)(nil),         // 0: modelcatalog.v1.ListCredentialProfilesRequest
	(*ListCredentialProfilesResponse)(nil),        // 1: modelcatalog.v1.ListCredentialProfilesResponse
	(*GetCredentialProfileRequest)(nil),           // 2: modelcatalog.v1.GetCredentialProfileRequest
	(*GetCredentialProfileResponse)(nil),          // 3: modelcatalog.v1.GetCredentialProfileResponse
	(*RegisterCredentialProfileRequest)(nil),      // 4: modelcatalog.v1.RegisterCredentialProfileRequest
	(*RegisterCredentialProfileResponse)(nil),     // 5: modelcatalog.v1.RegisterCredentialProfileResponse
	(*ChangeCredentialProfileStatusRequest)(nil),  // 6: modelcatalog.v1.ChangeCredentialProfileStatusRequest
	(*ChangeCredentialProfileStatusResponse)(nil), // 7: modelcatalog.v1.ChangeCredentialProfileStatusResponse
	(*ListConfiguredModelsRequest)(nil),           // 8: modelcatalog.v1.ListConfiguredModelsRequest
	(*ListConfiguredModelsResponse)(nil),          // 9: modelcatalog.v1.ListConfiguredModelsResponse
	(*GetConfiguredModelRequest)(nil),             // 10: modelcatalog.v1.GetConfiguredModelRequest
	(*GetConfiguredModelResponse)(nil),            // 11: modelcatalog.v1.GetConfiguredModelResponse
	(*RegisterConfiguredModelRequest)(nil),        // 12: modelcatalog.v1.RegisterConfiguredModelRequest
	(*RegisterConfiguredModelResponse)(nil),       // 13: modelcatalog.v1.RegisterConfiguredModelResponse
	(*ChangeConfiguredModelStatusRequest)(nil),    // 14: modelcatalog.v1.ChangeConfiguredModelStatusRequest
	(*ChangeConfiguredModelStatusResponse)(nil),   // 15: modelcatalog.v1.ChangeConfiguredModelStatusResponse
	(*CredentialProfile)(nil),                     // 16: modelcatalog.v1.CredentialProfile
	(*ConfiguredModel)(nil),                       // 17: modelcatalog.v1.ConfiguredModel
	(*timestamppb.Timestamp)(nil),                 // 18: google.protobuf.Timestamp
}
var file_modelcatalog_v1_model_catalog_proto_depIdxs = []int32{
	16, // 0: modelcatalog.v1.ListCredentialProfilesResponse.items:type_name -> modelcatalog.v1.CredentialProfile
	16, // 1: modelcatalog.v1.GetCredentialProfileResponse.credential_profile:type_name -> modelcatalog.v1.CredentialProfile
	16, // 2: modelcatalog.v1.RegisterCredentialProfileResponse.credential_profile:type_name -> modelcatalog.v1.CredentialProfile
	16, // 3: modelcatalog.v1.ChangeCredentialProfileStatusResponse.credential_profile:type_name -> modelcatalog.v1.CredentialProfile
	17, // 4: modelcatalog.v1.ListConfiguredModelsResponse.items:type_name -> modelcatalog.v1.ConfiguredModel
	17, // 5: modelcatalog.v1.GetConfiguredModelResponse.configured_model:type_name -> modelcatalog.v1.ConfiguredModel
	17, // 6: modelcatalog.v1.RegisterConfiguredModelResponse.configured_model:type_name -> modelcatalog.v1.ConfiguredModel
	17, // 7: modelcatalog.v1.ChangeConfiguredModelStatusResponse.configured_model:type_name -> modelcatalog.v1.ConfiguredModel
	18, // 8: modelcatalog.v1.CredentialProfile.created_at:type_name -> google.protobuf.Timestamp
	18, // 9: modelcatalog.v1.CredentialProfile.updated_at:type_name -> google.protobuf.Timestamp
	18, // 10: modelcatalog.v1.ConfiguredModel.created_at:type_name -> google.protobuf.Timestamp
	18, // 11: modelcatalog.v1.ConfiguredModel.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 12: modelcatalog.v1.ModelCatalogService.ListCredentialProfiles:input_type -> modelcatalog.v1.ListCredentialProfilesRequest
	2,  // 13: modelcatalog.v1.ModelCatalogService.GetCredentialProfile:input_type -> modelcatalog.v1.GetCredentialProfileRequest
	4,  // 14: modelcatalog.v1.ModelCatalogService.RegisterCredentialProfile:input_type -> modelcatalog.v1.RegisterCredentialProfileRequest
	6,  // 15: modelcatalog.v1.ModelCatalogService.ChangeCredentialProfileStatus:input_type -> modelcatalog.v1.ChangeCredentialProfileStatusRequest
	8,  // 16: modelcatalog.v1.ModelCatalogService.ListConfiguredModels:input_type -> modelcatalog.v1.ListConfiguredModelsRequest
	10, // 17: modelcatalog.v1.ModelCatalogService.GetConfiguredModel:input_type -> modelcatalog.v1.GetConfiguredModelRequest
	12, // 18: modelcatalog.v1.ModelCatalogService.RegisterConfiguredModel:input_type -> modelcatalog.v1.RegisterConfiguredModelRequest
	14, // 19: modelcatalog.v1.ModelCatalogService.ChangeConfiguredModelStatus:input_type -> modelcatalog.v1.ChangeConfiguredModelStatusRequest
	1,  // 20: modelcatalog.v1.ModelCatalogService.ListCredentialProfiles:output_type -> modelcatalog.v1.ListCredentialProfilesResponse
	16, // 21: modelcatalog.v1.ModelCatalogService.GetCredentialProfile:output_type -> modelcatalog.v1.CredentialProfile
	16, // 22: modelcatalog.v1.ModelCatalogService.RegisterCredentialProfile:output_type -> modelcatalog.v1.CredentialProfile
	16, // 23: modelcatalog.v1.ModelCatalogService.ChangeCredentialProfileStatus:output_type -> modelcatalog.v1.CredentialProfile
	9,  // 24: modelcatalog.v1.ModelCatalogService.ListConfiguredModels:output_type -> modelcatalog.v1.ListConfiguredModelsResponse
	17, // 25: modelcatalog.v1.ModelCatalogService.GetConfiguredModel:output_type -> modelcatalog.v1.ConfiguredModel
	17, // 26: modelcatalog.v1.ModelCatalogService.RegisterConfiguredModel:output_type -> modelcatalog.v1.ConfiguredModel
	17, // 27: modelcatalog.v1.ModelCatalogService.ChangeConfiguredModelStatus:output_type -> modelcatalog.v1.ConfiguredModel
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_modelcatalog_v1_model_catalog_proto_init() }
func file_modelcatalog_v1_model_catalog_proto_init() {
	if File_modelcatalog_v1_model_catalog_proto != nil {
		return
	}
	file_modelcatalog_v1_model_catalog_proto_msgTypes[4].OneofWrappers = []any{}
	file_modelcatalog_v1_model_catalog_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modelcatalog_v1_model_catalog_proto_rawDesc), len(file_modelcatalog_v1_model_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modelcatalog_v1_model_catalog_proto_goTypes,
		DependencyIndexes: file_modelcatalog_v1_model_catalog_proto_depIdxs,
		MessageInfos:      file_modelcatalog_v1_model_catalog_proto_msgTypes,
	}.Build()
	File_modelcatalog_v1_model_catalog_proto = out.File
	file_modelcatalog_v1_model_catalog_proto_goTypes = nil
	file_modelcatalog_v1_model_catalog_proto_depIdxs = nil
}
