// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: modelcatalog/v1/model_catalog.proto

package modelcatalogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelCatalogService_ListCredentialProfiles_FullMethodName        = "/modelcatalog.v1.ModelCatalogService/ListCredentialProfiles"
	ModelCatalogService_GetCredentialProfile_FullMethodName          = "/modelcatalog.v1.ModelCatalogService/GetCredentialProfile"
	ModelCatalogService_RegisterCredentialProfile_FullMethodName     = "/modelcatalog.v1.ModelCatalogService/RegisterCredentialProfile"
	ModelCatalogService_ChangeCredentialProfileStatus_FullMethodName = "/modelcatalog.v1.ModelCatalogService/ChangeCredentialProfileStatus"
	ModelCatalogService_ListConfiguredModels_FullMethodName          = "/modelcatalog.v1.ModelCatalogService/ListConfiguredModels"
	ModelCatalogService_GetConfiguredModel_FullMethodName            = "/modelcatalog.v1.ModelCatalogService/GetConfiguredModel"
	ModelCatalogService_RegisterConfiguredModel_FullMethodName       = "/modelcatalog.v1.ModelCatalogService/RegisterConfiguredModel"
	ModelCatalogService_ChangeConfiguredModelStatus_FullMethodName   = "/modelcatalog.v1.ModelCatalogService/ChangeConfiguredModelStatus"
)

// ModelCatalogServiceClient is the client API for ModelCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelCatalogServiceClient interface {
	ListCredentialProfiles(ctx context.Context, in *ListCredentialProfilesRequest, opts ...grpc.CallOption) (*ListCredentialProfilesResponse, error)
	GetCredentialProfile(ctx context.Context, in *GetCredentialProfileRequest, opts ...grpc.CallOption) (*CredentialProfile, error)
	RegisterCredentialProfile(ctx context.Context, in *RegisterCredentialProfileRequest, opts ...grpc.CallOption) (*CredentialProfile, error)
	ChangeCredentialProfileStatus(ctx context.Context, in *ChangeCredentialProfileStatusRequest, opts ...grpc.CallOption) (*CredentialProfile, error)
	ListConfiguredModels(ctx context.Context, in *ListConfiguredModelsRequest, opts ...grpc.CallOption) (*ListConfiguredModelsResponse, error)
	GetConfiguredModel(ctx context.Context, in *GetConfiguredModelRequest, opts ...grpc.CallOption) (*ConfiguredModel, error)
	RegisterConfiguredModel(ctx context.Context, in *RegisterConfiguredModelRequest, opts ...grpc.CallOption) (*ConfiguredModel, error)
	ChangeConfiguredModelStatus(ctx context.Context, in *ChangeConfiguredModelStatusRequest, opts ...grpc.CallOption) (*ConfiguredModel, error)
}

type modelCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelCatalogServiceClient(cc grpc.ClientConnInterface) ModelCatalogServiceClient {
	return &modelCatalogServiceClient{cc}
}

func (c *modelCatalogServiceClient) ListCredentialProfiles(ctx context.Context, in *ListCredentialProfilesRequest, opts ...grpc.CallOption) (*ListCredentialProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCredentialProfilesResponse)
	err := c.cc.Invoke(ctx, ModelCatalogService_ListCredentialProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelCatalogServiceClient) GetCredentialProfile(ctx context.Context, in *GetCredentialProfileRequest, opts ...grpc.CallOption) (*CredentialProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialProfile)
	err := c.cc.Invoke(ctx, ModelCatalogService_GetCredentialProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelCatalogServiceClient) RegisterCredentialProfile(ctx context.Context, in *RegisterCredentialProfileRequest, opts ...grpc.CallOption) (*CredentialProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialProfile)
	err := c.cc.Invoke(ctx, ModelCatalogService_RegisterCredentialProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelCatalogServiceClient) ChangeCredentialProfileStatus(ctx context.Context, in *ChangeCredentialProfileStatusRequest, opts ...grpc.CallOption) (*CredentialProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialProfile)
	err := c.cc.Invoke(ctx, ModelCatalogService_ChangeCredentialProfileStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelCatalogServiceClient) ListConfiguredModels(ctx context.Context, in *ListConfiguredModelsRequest, opts ...grpc.CallOption) (*ListConfiguredModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfiguredModelsResponse)
	err := c.cc.Invoke(ctx, ModelCatalogService_ListConfiguredModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelCatalogServiceClient) GetConfiguredModel(ctx context.Context, in *GetConfiguredModelRequest, opts ...grpc.CallOption) (*ConfiguredModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfiguredModel)
	err := c.cc.Invoke(ctx, ModelCatalogService_GetConfiguredModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelCatalogServiceClient) RegisterConfiguredModel(ctx context.Context, in *RegisterConfiguredModelRequest, opts ...grpc.CallOption) (*ConfiguredModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfiguredModel)
	err := c.cc.Invoke(ctx, ModelCatalogService_RegisterConfiguredModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelCatalogServiceClient) ChangeConfiguredModelStatus(ctx context.Context, in *ChangeConfiguredModelStatusRequest, opts ...grpc.CallOption) (*ConfiguredModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfiguredModel)
	err := c.cc.Invoke(ctx, ModelCatalogService_ChangeConfiguredModelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelCatalogServiceServer is the server API for ModelCatalogService service.
// All implementations must embed UnimplementedModelCatalogServiceServer
// for forward compatibility.
type ModelCatalogServiceServer interface {
	ListCredentialProfiles(context.Context, *ListCredentialProfilesRequest) (*ListCredentialProfilesResponse, error)
	GetCredentialProfile(context.Context, *GetCredentialProfileRequest) (*CredentialProfile, error)
	RegisterCredentialProfile(context.Context, *RegisterCredentialProfileRequest) (*CredentialProfile, error)
	ChangeCredentialProfileStatus(context.Context, *ChangeCredentialProfileStatusRequest) (*CredentialProfile, error)
	ListConfiguredModels(context.Context, *ListConfiguredModelsRequest) (*ListConfiguredModelsResponse, error)
	GetConfiguredModel(context.Context, *GetConfiguredModelRequest) (*ConfiguredModel, error)
	RegisterConfiguredModel(context.Context, *RegisterConfiguredModelRequest) (*ConfiguredModel, error)
	ChangeConfiguredModelStatus(context.Context, *ChangeConfiguredModelStatusRequest) (*ConfiguredModel, error)
	mustEmbedUnimplementedModelCatalogServiceServer()
}

// UnimplementedModelCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelCatalogServiceServer struct{}

func (UnimplementedModelCatalogServiceServer) ListCredentialProfiles(context.Context, *ListCredentialProfilesRequest) (*ListCredentialProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCredentialProfiles not implemented")
}
func (UnimplementedModelCatalogServiceServer) GetCredentialProfile(context.Context, *GetCredentialProfileRequest) (*CredentialProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentialProfile not implemented")
}
func (UnimplementedModelCatalogServiceServer) RegisterCredentialProfile(context.Context, *RegisterCredentialProfileRequest) (*CredentialProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCredentialProfile not implemented")
}
func (UnimplementedModelCatalogServiceServer) ChangeCredentialProfileStatus(context.Context, *ChangeCredentialProfileStatusRequest) (*CredentialProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeCredentialProfileStatus not implemented")
}
func (UnimplementedModelCatalogServiceServer) ListConfiguredModels(context.Context, *ListConfiguredModelsRequest) (*ListConfiguredModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfiguredModels not implemented")
}
func (UnimplementedModelCatalogServiceServer) GetConfiguredModel(context.Context, *GetConfiguredModelRequest) (*ConfiguredModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfiguredModel not implemented")
}
func (UnimplementedModelCatalogServiceServer) RegisterConfiguredModel(context.Context, *RegisterConfiguredModelRequest) (*ConfiguredModel, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterConfiguredModel not implemented")
}
func (UnimplementedModelCatalogServiceServer) ChangeConfiguredModelStatus(context.Context, *ChangeConfiguredModelStatusRequest) (*ConfiguredModel, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeConfiguredModelStatus not implemented")
}
func (UnimplementedModelCatalogServiceServer) mustEmbedUnimplementedModelCatalogServiceServer() {}
func (UnimplementedModelCatalogServiceServer) testEmbeddedByValue()                             {}

// UnsafeModelCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelCatalogServiceServer will
// result in compilation errors.
type UnsafeModelCatalogServiceServer interface {
	mustEmbedUnimplementedModelCatalogServiceServer()
}

func RegisterModelCatalogServiceServer(s grpc.ServiceRegistrar, srv ModelCatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedModelCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelCatalogService_ServiceDesc, srv)
}

func _ModelCatalogService_ListCredentialProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCredentialProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).ListCredentialProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_ListCredentialProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).ListCredentialProfiles(ctx, req.(*ListCredentialProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelCatalogService_GetCredentialProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).GetCredentialProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_GetCredentialProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).GetCredentialProfile(ctx, req.(*GetCredentialProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelCatalogService_RegisterCredentialProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCredentialProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).RegisterCredentialProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_RegisterCredentialProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).RegisterCredentialProfile(ctx, req.(*RegisterCredentialProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelCatalogService_ChangeCredentialProfileStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeCredentialProfileStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).ChangeCredentialProfileStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_ChangeCredentialProfileStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).ChangeCredentialProfileStatus(ctx, req.(*ChangeCredentialProfileStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelCatalogService_ListConfiguredModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfiguredModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).ListConfiguredModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_ListConfiguredModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).ListConfiguredModels(ctx, req.(*ListConfiguredModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelCatalogService_GetConfiguredModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfiguredModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).GetConfiguredModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_GetConfiguredModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).GetConfiguredModel(ctx, req.(*GetConfiguredModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelCatalogService_RegisterConfiguredModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConfiguredModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).RegisterConfiguredModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_RegisterConfiguredModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).RegisterConfiguredModel(ctx, req.(*RegisterConfiguredModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelCatalogService_ChangeConfiguredModelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeConfiguredModelStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelCatalogServiceServer).ChangeConfiguredModelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelCatalogService_ChangeConfiguredModelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelCatalogServiceServer).ChangeConfiguredModelStatus(ctx, req.(*ChangeConfiguredModelStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelCatalogService_ServiceDesc is the grpc.ServiceDesc for ModelCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modelcatalog.v1.ModelCatalogService",
	HandlerType: (*ModelCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCredentialProfiles",
			Handler:    _ModelCatalogService_ListCredentialProfiles_Handler,
		},
		{
			MethodName: "GetCredentialProfile",
			Handler:    _ModelCatalogService_GetCredentialProfile_Handler,
		},
		{
			MethodName: "RegisterCredentialProfile",
			Handler:    _ModelCatalogService_RegisterCredentialProfile_Handler,
		},
		{
			MethodName: "ChangeCredentialProfileStatus",
			Handler:    _ModelCatalogService_ChangeCredentialProfileStatus_Handler,
		},
		{
			MethodName: "ListConfiguredModels",
			Handler:    _ModelCatalogService_ListConfiguredModels_Handler,
		},
		{
			MethodName: "GetConfiguredModel",
			Handler:    _ModelCatalogService_GetConfiguredModel_Handler,
		},
		{
			MethodName: "RegisterConfiguredModel",
			Handler:    _ModelCatalogService_RegisterConfiguredModel_Handler,
		},
		{
			MethodName: "ChangeConfiguredModelStatus",
			Handler:    _ModelCatalogService_ChangeConfiguredModelStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modelcatalog/v1/model_catalog.proto",
}
