// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: collaboration/v1/collaboration.proto

package collaborationv1

import (
	v1 "agent-platform/backend/api/types/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCodingTaskLaunchOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCodingTaskLaunchOptionsRequest) Reset() {
	*x = ListCodingTaskLaunchOptionsRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCodingTaskLaunchOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCodingTaskLaunchOptionsRequest) ProtoMessage() {}

func (x *ListCodingTaskLaunchOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCodingTaskLaunchOptionsRequest.ProtoReflect.Descriptor instead.
func (*ListCodingTaskLaunchOptionsRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{0}
}

func (x *ListCodingTaskLaunchOptionsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type ListCodingTaskLaunchOptionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*CodingTaskLaunchOption `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Prerequisite  string                    `protobuf:"bytes,2,opt,name=prerequisite,proto3" json:"prerequisite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCodingTaskLaunchOptionsResponse) Reset() {
	*x = ListCodingTaskLaunchOptionsResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCodingTaskLaunchOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCodingTaskLaunchOptionsResponse) ProtoMessage() {}

func (x *ListCodingTaskLaunchOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCodingTaskLaunchOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListCodingTaskLaunchOptionsResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{1}
}

func (x *ListCodingTaskLaunchOptionsResponse) GetItems() []*CodingTaskLaunchOption {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCodingTaskLaunchOptionsResponse) GetPrerequisite() string {
	if x != nil {
		return x.Prerequisite
	}
	return ""
}

type CodingTaskLaunchOption struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentReleaseId      string                 `protobuf:"bytes,1,opt,name=agent_release_id,json=agentReleaseId,proto3" json:"agent_release_id,omitempty"`
	RepositoryBindingId string                 `protobuf:"bytes,2,opt,name=repository_binding_id,json=repositoryBindingId,proto3" json:"repository_binding_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CodingTaskLaunchOption) Reset() {
	*x = CodingTaskLaunchOption{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodingTaskLaunchOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodingTaskLaunchOption) ProtoMessage() {}

func (x *CodingTaskLaunchOption) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodingTaskLaunchOption.ProtoReflect.Descriptor instead.
func (*CodingTaskLaunchOption) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{2}
}

func (x *CodingTaskLaunchOption) GetAgentReleaseId() string {
	if x != nil {
		return x.AgentReleaseId
	}
	return ""
}

func (x *CodingTaskLaunchOption) GetRepositoryBindingId() string {
	if x != nil {
		return x.RepositoryBindingId
	}
	return ""
}

type ListCodingTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCodingTasksRequest) Reset() {
	*x = ListCodingTasksRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCodingTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCodingTasksRequest) ProtoMessage() {}

func (x *ListCodingTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCodingTasksRequest.ProtoReflect.Descriptor instead.
func (*ListCodingTasksRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{3}
}

func (x *ListCodingTasksRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type ListCodingTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CodingTask          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCodingTasksResponse) Reset() {
	*x = ListCodingTasksResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCodingTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCodingTasksResponse) ProtoMessage() {}

func (x *ListCodingTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCodingTasksResponse.ProtoReflect.Descriptor instead.
func (*ListCodingTasksResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{4}
}

func (x *ListCodingTasksResponse) GetItems() []*CodingTask {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateCodingTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TeamId         string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AgentReleaseId string                 `protobuf:"bytes,2,opt,name=agent_release_id,json=agentReleaseId,proto3" json:"agent_release_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	RequestText    string                 `protobuf:"bytes,4,opt,name=request_text,json=requestText,proto3" json:"request_text,omitempty"`
	IssueSnapshot  *v1.IssueSnapshot      `protobuf:"bytes,5,opt,name=issue_snapshot,json=issueSnapshot,proto3,oneof" json:"issue_snapshot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCodingTaskRequest) Reset() {
	*x = CreateCodingTaskRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCodingTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCodingTaskRequest) ProtoMessage() {}

func (x *CreateCodingTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCodingTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateCodingTaskRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCodingTaskRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateCodingTaskRequest) GetAgentReleaseId() string {
	if x != nil {
		return x.AgentReleaseId
	}
	return ""
}

func (x *CreateCodingTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCodingTaskRequest) GetRequestText() string {
	if x != nil {
		return x.RequestText
	}
	return ""
}

func (x *CreateCodingTaskRequest) GetIssueSnapshot() *v1.IssueSnapshot {
	if x != nil {
		return x.IssueSnapshot
	}
	return nil
}

type CreateCodingTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *CodingTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Session       *Session               `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCodingTaskResponse) Reset() {
	*x = CreateCodingTaskResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCodingTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCodingTaskResponse) ProtoMessage() {}

func (x *CreateCodingTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCodingTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateCodingTaskResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCodingTaskResponse) GetTask() *CodingTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *CreateCodingTaskResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CreateCodingTaskResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetCodingTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodingTaskRequest) Reset() {
	*x = GetCodingTaskRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodingTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodingTaskRequest) ProtoMessage() {}

func (x *GetCodingTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodingTaskRequest.ProtoReflect.Descriptor instead.
func (*GetCodingTaskRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{7}
}

func (x *GetCodingTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetCodingTaskRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetCodingTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *CodingTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodingTaskResponse) Reset() {
	*x = GetCodingTaskResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodingTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodingTaskResponse) ProtoMessage() {}

func (x *GetCodingTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodingTaskResponse.ProtoReflect.Descriptor instead.
func (*GetCodingTaskResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{8}
}

func (x *GetCodingTaskResponse) GetTask() *CodingTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateCodingTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCodingTaskRequest) Reset() {
	*x = UpdateCodingTaskRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCodingTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCodingTaskRequest) ProtoMessage() {}

func (x *UpdateCodingTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCodingTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateCodingTaskRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCodingTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateCodingTaskRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateCodingTaskRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type UpdateCodingTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *CodingTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCodingTaskResponse) Reset() {
	*x = UpdateCodingTaskResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCodingTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCodingTaskResponse) ProtoMessage() {}

func (x *UpdateCodingTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCodingTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateCodingTaskResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCodingTaskResponse) GetTask() *CodingTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type ContinueCodingTaskRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TaskId                 string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TeamId                 string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RequestText            string                 `protobuf:"bytes,3,opt,name=request_text,json=requestText,proto3" json:"request_text,omitempty"`
	ExpectedSessionVersion int64                  `protobuf:"varint,4,opt,name=expected_session_version,json=expectedSessionVersion,proto3" json:"expected_session_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContinueCodingTaskRequest) Reset() {
	*x = ContinueCodingTaskRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueCodingTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueCodingTaskRequest) ProtoMessage() {}

func (x *ContinueCodingTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueCodingTaskRequest.ProtoReflect.Descriptor instead.
func (*ContinueCodingTaskRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{11}
}

func (x *ContinueCodingTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ContinueCodingTaskRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ContinueCodingTaskRequest) GetRequestText() string {
	if x != nil {
		return x.RequestText
	}
	return ""
}

func (x *ContinueCodingTaskRequest) GetExpectedSessionVersion() int64 {
	if x != nil {
		return x.ExpectedSessionVersion
	}
	return 0
}

type ContinueCodingTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *CodingTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Session       *Session               `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueCodingTaskResponse) Reset() {
	*x = ContinueCodingTaskResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueCodingTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueCodingTaskResponse) ProtoMessage() {}

func (x *ContinueCodingTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueCodingTaskResponse.ProtoReflect.Descriptor instead.
func (*ContinueCodingTaskResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{12}
}

func (x *ContinueCodingTaskResponse) GetTask() *CodingTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ContinueCodingTaskResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ContinueCodingTaskResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetCodingTaskSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodingTaskSessionRequest) Reset() {
	*x = GetCodingTaskSessionRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodingTaskSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodingTaskSessionRequest) ProtoMessage() {}

func (x *GetCodingTaskSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodingTaskSessionRequest.ProtoReflect.Descriptor instead.
func (*GetCodingTaskSessionRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{13}
}

func (x *GetCodingTaskSessionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetCodingTaskSessionRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetCodingTaskSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodingTaskSessionResponse) Reset() {
	*x = GetCodingTaskSessionResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodingTaskSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodingTaskSessionResponse) ProtoMessage() {}

func (x *GetCodingTaskSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodingTaskSessionResponse.ProtoReflect.Descriptor instead.
func (*GetCodingTaskSessionResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{14}
}

func (x *GetCodingTaskSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type UpdateCodingTaskSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Memory        *v1.SessionMemory      `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCodingTaskSessionRequest) Reset() {
	*x = UpdateCodingTaskSessionRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCodingTaskSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCodingTaskSessionRequest) ProtoMessage() {}

func (x *UpdateCodingTaskSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCodingTaskSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCodingTaskSessionRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCodingTaskSessionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateCodingTaskSessionRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateCodingTaskSessionRequest) GetMemory() *v1.SessionMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

type UpdateCodingTaskSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCodingTaskSessionResponse) Reset() {
	*x = UpdateCodingTaskSessionResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCodingTaskSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCodingTaskSessionResponse) ProtoMessage() {}

func (x *UpdateCodingTaskSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCodingTaskSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateCodingTaskSessionResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCodingTaskSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	After         *int64                 `protobuf:"varint,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	Limit         *int32                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionMessagesRequest) Reset() {
	*x = ListSessionMessagesRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionMessagesRequest) ProtoMessage() {}

func (x *ListSessionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListSessionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{17}
}

func (x *ListSessionMessagesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListSessionMessagesRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListSessionMessagesRequest) GetAfter() int64 {
	if x != nil && x.After != nil {
		return *x.After
	}
	return 0
}

func (x *ListSessionMessagesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ListSessionMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SessionMessage      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionMessagesResponse) Reset() {
	*x = ListSessionMessagesResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionMessagesResponse) ProtoMessage() {}

func (x *ListSessionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListSessionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{18}
}

func (x *ListSessionMessagesResponse) GetItems() []*SessionMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListMemoryCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoryCandidatesRequest) Reset() {
	*x = ListMemoryCandidatesRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoryCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoryCandidatesRequest) ProtoMessage() {}

func (x *ListMemoryCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoryCandidatesRequest.ProtoReflect.Descriptor instead.
func (*ListMemoryCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{19}
}

func (x *ListMemoryCandidatesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListMemoryCandidatesRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type ListMemoryCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MemoryCandidate     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoryCandidatesResponse) Reset() {
	*x = ListMemoryCandidatesResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoryCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoryCandidatesResponse) ProtoMessage() {}

func (x *ListMemoryCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoryCandidatesResponse.ProtoReflect.Descriptor instead.
func (*ListMemoryCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{20}
}

func (x *ListMemoryCandidatesResponse) GetItems() []*MemoryCandidate {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProposeMemoryCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeMemoryCandidateRequest) Reset() {
	*x = ProposeMemoryCandidateRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeMemoryCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeMemoryCandidateRequest) ProtoMessage() {}

func (x *ProposeMemoryCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeMemoryCandidateRequest.ProtoReflect.Descriptor instead.
func (*ProposeMemoryCandidateRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{21}
}

func (x *ProposeMemoryCandidateRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProposeMemoryCandidateRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ProposeMemoryCandidateRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProposeMemoryCandidateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ProposeMemoryCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     *MemoryCandidate       `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeMemoryCandidateResponse) Reset() {
	*x = ProposeMemoryCandidateResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeMemoryCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeMemoryCandidateResponse) ProtoMessage() {}

func (x *ProposeMemoryCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeMemoryCandidateResponse.ProtoReflect.Descriptor instead.
func (*ProposeMemoryCandidateResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{22}
}

func (x *ProposeMemoryCandidateResponse) GetCandidate() *MemoryCandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type DecideMemoryCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideMemoryCandidateRequest) Reset() {
	*x = DecideMemoryCandidateRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideMemoryCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideMemoryCandidateRequest) ProtoMessage() {}

func (x *DecideMemoryCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideMemoryCandidateRequest.ProtoReflect.Descriptor instead.
func (*DecideMemoryCandidateRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{23}
}

func (x *DecideMemoryCandidateRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *DecideMemoryCandidateRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *DecideMemoryCandidateRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type DecideMemoryCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     *MemoryCandidate       `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Memory        *AgentMemory           `protobuf:"bytes,2,opt,name=memory,proto3,oneof" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideMemoryCandidateResponse) Reset() {
	*x = DecideMemoryCandidateResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideMemoryCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideMemoryCandidateResponse) ProtoMessage() {}

func (x *DecideMemoryCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideMemoryCandidateResponse.ProtoReflect.Descriptor instead.
func (*DecideMemoryCandidateResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{24}
}

func (x *DecideMemoryCandidateResponse) GetCandidate() *MemoryCandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *DecideMemoryCandidateResponse) GetMemory() *AgentMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

type ListAgentMemoriesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TeamId         string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	IncludeDeleted *bool                  `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAgentMemoriesRequest) Reset() {
	*x = ListAgentMemoriesRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentMemoriesRequest) ProtoMessage() {}

func (x *ListAgentMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentMemoriesRequest.ProtoReflect.Descriptor instead.
func (*ListAgentMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{25}
}

func (x *ListAgentMemoriesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListAgentMemoriesRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListAgentMemoriesRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

type ListAgentMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AgentMemory         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentMemoriesResponse) Reset() {
	*x = ListAgentMemoriesResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentMemoriesResponse) ProtoMessage() {}

func (x *ListAgentMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentMemoriesResponse.ProtoReflect.Descriptor instead.
func (*ListAgentMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{26}
}

func (x *ListAgentMemoriesResponse) GetItems() []*AgentMemory {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateAgentMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentMemoryRequest) Reset() {
	*x = UpdateAgentMemoryRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentMemoryRequest) ProtoMessage() {}

func (x *UpdateAgentMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentMemoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentMemoryRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateAgentMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *UpdateAgentMemoryRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateAgentMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateAgentMemoryRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateAgentMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *AgentMemory           `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentMemoryResponse) Reset() {
	*x = UpdateAgentMemoryResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentMemoryResponse) ProtoMessage() {}

func (x *UpdateAgentMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentMemoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentMemoryResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateAgentMemoryResponse) GetMemory() *AgentMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

type DeleteAgentMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentMemoryRequest) Reset() {
	*x = DeleteAgentMemoryRequest{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentMemoryRequest) ProtoMessage() {}

func (x *DeleteAgentMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentMemoryRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteAgentMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *DeleteAgentMemoryRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type DeleteAgentMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *AgentMemory           `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentMemoryResponse) Reset() {
	*x = DeleteAgentMemoryResponse{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentMemoryResponse) ProtoMessage() {}

func (x *DeleteAgentMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentMemoryResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteAgentMemoryResponse) GetMemory() *AgentMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

type CodingTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId         string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AgentReleaseId string                 `protobuf:"bytes,3,opt,name=agent_release_id,json=agentReleaseId,proto3" json:"agent_release_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	RequestText    string                 `protobuf:"bytes,6,opt,name=request_text,json=requestText,proto3" json:"request_text,omitempty"`
	IssueSnapshot  *v1.IssueSnapshot      `protobuf:"bytes,7,opt,name=issue_snapshot,json=issueSnapshot,proto3,oneof" json:"issue_snapshot,omitempty"`
	State          string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	Version        int64                  `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodingTask) Reset() {
	*x = CodingTask{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodingTask) ProtoMessage() {}

func (x *CodingTask) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodingTask.ProtoReflect.Descriptor instead.
func (*CodingTask) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{31}
}

func (x *CodingTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CodingTask) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CodingTask) GetAgentReleaseId() string {
	if x != nil {
		return x.AgentReleaseId
	}
	return ""
}

func (x *CodingTask) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CodingTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CodingTask) GetRequestText() string {
	if x != nil {
		return x.RequestText
	}
	return ""
}

func (x *CodingTask) GetIssueSnapshot() *v1.IssueSnapshot {
	if x != nil {
		return x.IssueSnapshot
	}
	return nil
}

func (x *CodingTask) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CodingTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CodingTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CodingTask) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *CodingTask) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Session struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CodingTaskId        string                 `protobuf:"bytes,2,opt,name=coding_task_id,json=codingTaskId,proto3" json:"coding_task_id,omitempty"`
	RepositoryBindingId string                 `protobuf:"bytes,3,opt,name=repository_binding_id,json=repositoryBindingId,proto3" json:"repository_binding_id,omitempty"`
	TargetBranch        string                 `protobuf:"bytes,4,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	ReviewBranch        string                 `protobuf:"bytes,5,opt,name=review_branch,json=reviewBranch,proto3" json:"review_branch,omitempty"`
	Memory              *v1.SessionMemory      `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	RunCount            int32                  `protobuf:"varint,7,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version             int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{32}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetCodingTaskId() string {
	if x != nil {
		return x.CodingTaskId
	}
	return ""
}

func (x *Session) GetRepositoryBindingId() string {
	if x != nil {
		return x.RepositoryBindingId
	}
	return ""
}

func (x *Session) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *Session) GetReviewBranch() string {
	if x != nil {
		return x.ReviewBranch
	}
	return ""
}

func (x *Session) GetMemory() *v1.SessionMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Session) GetRunCount() int32 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Session) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SessionMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            int64                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RunId         *string                   `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	Author        string                    `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	AuthorUserId  *string                   `protobuf:"bytes,4,opt,name=author_user_id,json=authorUserId,proto3,oneof" json:"author_user_id,omitempty"`
	Content       *v1.SessionMessageContent `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{33}
}

func (x *SessionMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionMessage) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *SessionMessage) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SessionMessage) GetAuthorUserId() string {
	if x != nil && x.AuthorUserId != nil {
		return *x.AuthorUserId
	}
	return ""
}

func (x *SessionMessage) GetContent() *v1.SessionMessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SessionMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MemoryCandidate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId           string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CodingTaskId      string                 `protobuf:"bytes,3,opt,name=coding_task_id,json=codingTaskId,proto3" json:"coding_task_id,omitempty"`
	ProposedContent   string                 `protobuf:"bytes,4,opt,name=proposed_content,json=proposedContent,proto3" json:"proposed_content,omitempty"`
	State             string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	ProposedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=proposed_at,json=proposedAt,proto3" json:"proposed_at,omitempty"`
	DecidedBy         *string                `protobuf:"bytes,7,opt,name=decided_by,json=decidedBy,proto3,oneof" json:"decided_by,omitempty"`
	DecidedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=decided_at,json=decidedAt,proto3,oneof" json:"decided_at,omitempty"`
	ResultingMemoryId *string                `protobuf:"bytes,9,opt,name=resulting_memory_id,json=resultingMemoryId,proto3,oneof" json:"resulting_memory_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MemoryCandidate) Reset() {
	*x = MemoryCandidate{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryCandidate) ProtoMessage() {}

func (x *MemoryCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryCandidate.ProtoReflect.Descriptor instead.
func (*MemoryCandidate) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{34}
}

func (x *MemoryCandidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryCandidate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MemoryCandidate) GetCodingTaskId() string {
	if x != nil {
		return x.CodingTaskId
	}
	return ""
}

func (x *MemoryCandidate) GetProposedContent() string {
	if x != nil {
		return x.ProposedContent
	}
	return ""
}

func (x *MemoryCandidate) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MemoryCandidate) GetProposedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProposedAt
	}
	return nil
}

func (x *MemoryCandidate) GetDecidedBy() string {
	if x != nil && x.DecidedBy != nil {
		return *x.DecidedBy
	}
	return ""
}

func (x *MemoryCandidate) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

func (x *MemoryCandidate) GetResultingMemoryId() string {
	if x != nil && x.ResultingMemoryId != nil {
		return *x.ResultingMemoryId
	}
	return ""
}

type AgentMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,4,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	SourceTaskId  *string                `protobuf:"bytes,5,opt,name=source_task_id,json=sourceTaskId,proto3,oneof" json:"source_task_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Version       int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMemory) Reset() {
	*x = AgentMemory{}
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMemory) ProtoMessage() {}

func (x *AgentMemory) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_v1_collaboration_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMemory.ProtoReflect.Descriptor instead.
func (*AgentMemory) Descriptor() ([]byte, []int) {
	return file_collaboration_v1_collaboration_proto_rawDescGZIP(), []int{35}
}

func (x *AgentMemory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentMemory) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMemory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentMemory) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *AgentMemory) GetSourceTaskId() string {
	if x != nil && x.SourceTaskId != nil {
		return *x.SourceTaskId
	}
	return ""
}

func (x *AgentMemory) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AgentMemory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentMemory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AgentMemory) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *AgentMemory) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_collaboration_v1_collaboration_proto protoreflect.FileDescriptor

const file_collaboration_v1_collaboration_proto_rawDesc = "" +
	"\n" +
	"$collaboration/v1/collaboration.proto\x12\x10collaboration.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x14types/v1/types.proto\"=\n" +
	"\"ListCodingTaskLaunchOptionsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\x89\x01\n" +
	"#ListCodingTaskLaunchOptionsResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.collaboration.v1.CodingTaskLaunchOptionR\x05items\x12\"\n" +
	"\fprerequisite\x18\x02 \x01(\tR\fprerequisite\"v\n" +
	"\x16CodingTaskLaunchOption\x12(\n" +
	"\x10agent_release_id\x18\x01 \x01(\tR\x0eagentReleaseId\x122\n" +
	"\x15repository_binding_id\x18\x02 \x01(\tR\x13repositoryBindingId\"1\n" +
	"\x16ListCodingTasksRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"M\n" +
	"\x17ListCodingTasksResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.collaboration.v1.CodingTaskR\x05items\"\xed\x01\n" +
	"\x17CreateCodingTaskRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12(\n" +
	"\x10agent_release_id\x18\x02 \x01(\tR\x0eagentReleaseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12!\n" +
	"\frequest_text\x18\x04 \x01(\tR\vrequestText\x12C\n" +
	"\x0eissue_snapshot\x18\x05 \x01(\v2\x17.types.v1.IssueSnapshotH\x00R\rissueSnapshot\x88\x01\x01B\x11\n" +
	"\x0f_issue_snapshot\"\x98\x01\n" +
	"\x18CreateCodingTaskResponse\x120\n" +
	"\x04task\x18\x01 \x01(\v2\x1c.collaboration.v1.CodingTaskR\x04task\x123\n" +
	"\asession\x18\x02 \x01(\v2\x19.collaboration.v1.SessionR\asession\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"H\n" +
	"\x14GetCodingTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\"I\n" +
	"\x15GetCodingTaskResponse\x120\n" +
	"\x04task\x18\x01 \x01(\v2\x1c.collaboration.v1.CodingTaskR\x04task\"a\n" +
	"\x17UpdateCodingTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"L\n" +
	"\x18UpdateCodingTaskResponse\x120\n" +
	"\x04task\x18\x01 \x01(\v2\x1c.collaboration.v1.CodingTaskR\x04task\"\xaa\x01\n" +
	"\x19ContinueCodingTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12!\n" +
	"\frequest_text\x18\x03 \x01(\tR\vrequestText\x128\n" +
	"\x18expected_session_version\x18\x04 \x01(\x03R\x16expectedSessionVersion\"\x9a\x01\n" +
	"\x1aContinueCodingTaskResponse\x120\n" +
	"\x04task\x18\x01 \x01(\v2\x1c.collaboration.v1.CodingTaskR\x04task\x123\n" +
	"\asession\x18\x02 \x01(\v2\x19.collaboration.v1.SessionR\asession\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"O\n" +
	"\x1bGetCodingTaskSessionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\"S\n" +
	"\x1cGetCodingTaskSessionResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.collaboration.v1.SessionR\asession\"\x83\x01\n" +
	"\x1eUpdateCodingTaskSessionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12/\n" +
	"\x06memory\x18\x03 \x01(\v2\x17.types.v1.SessionMemoryR\x06memory\"V\n" +
	"\x1fUpdateCodingTaskSessionResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.collaboration.v1.SessionR\asession\"\x98\x01\n" +
	"\x1aListSessionMessagesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x19\n" +
	"\x05after\x18\x03 \x01(\x03H\x00R\x05after\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x05H\x01R\x05limit\x88\x01\x01B\b\n" +
	"\x06_afterB\b\n" +
	"\x06_limit\"U\n" +
	"\x1bListSessionMessagesResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .collaboration.v1.SessionMessageR\x05items\"O\n" +
	"\x1bListMemoryCandidatesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\"W\n" +
	"\x1cListMemoryCandidatesResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.collaboration.v1.MemoryCandidateR\x05items\"\x86\x01\n" +
	"\x1dProposeMemoryCandidateRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"a\n" +
	"\x1eProposeMemoryCandidateResponse\x12?\n" +
	"\tcandidate\x18\x01 \x01(\v2!.collaboration.v1.MemoryCandidateR\tcandidate\"t\n" +
	"\x1cDecideMemoryCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\"\xa7\x01\n" +
	"\x1dDecideMemoryCandidateResponse\x12?\n" +
	"\tcandidate\x18\x01 \x01(\v2!.collaboration.v1.MemoryCandidateR\tcandidate\x12:\n" +
	"\x06memory\x18\x02 \x01(\v2\x1d.collaboration.v1.AgentMemoryH\x00R\x06memory\x88\x01\x01B\t\n" +
	"\a_memory\"\x90\x01\n" +
	"\x18ListAgentMemoriesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12,\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bH\x00R\x0eincludeDeleted\x88\x01\x01B\x12\n" +
	"\x10_include_deleted\"P\n" +
	"\x19ListAgentMemoriesResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.collaboration.v1.AgentMemoryR\x05items\"\x84\x01\n" +
	"\x18UpdateAgentMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"R\n" +
	"\x19UpdateAgentMemoryResponse\x125\n" +
	"\x06memory\x18\x01 \x01(\v2\x1d.collaboration.v1.AgentMemoryR\x06memory\"P\n" +
	"\x18DeleteAgentMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\"R\n" +
	"\x19DeleteAgentMemoryResponse\x125\n" +
	"\x06memory\x18\x01 \x01(\v2\x1d.collaboration.v1.AgentMemoryR\x06memory\"\x8a\x04\n" +
	"\n" +
	"CodingTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12(\n" +
	"\x10agent_release_id\x18\x03 \x01(\tR\x0eagentReleaseId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12!\n" +
	"\frequest_text\x18\x06 \x01(\tR\vrequestText\x12C\n" +
	"\x0eissue_snapshot\x18\a \x01(\v2\x17.types.v1.IssueSnapshotH\x00R\rissueSnapshot\x88\x01\x01\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\f \x01(\x03R\aversionB\x11\n" +
	"\x0f_issue_snapshotB\x0f\n" +
	"\r_completed_at\"\x9b\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0ecoding_task_id\x18\x02 \x01(\tR\fcodingTaskId\x122\n" +
	"\x15repository_binding_id\x18\x03 \x01(\tR\x13repositoryBindingId\x12#\n" +
	"\rtarget_branch\x18\x04 \x01(\tR\ftargetBranch\x12#\n" +
	"\rreview_branch\x18\x05 \x01(\tR\freviewBranch\x12/\n" +
	"\x06memory\x18\x06 \x01(\v2\x17.types.v1.SessionMemoryR\x06memory\x12\x1b\n" +
	"\trun_count\x18\a \x01(\x05R\brunCount\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\"\x93\x02\n" +
	"\x0eSessionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\x06run_id\x18\x02 \x01(\tH\x00R\x05runId\x88\x01\x01\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12)\n" +
	"\x0eauthor_user_id\x18\x04 \x01(\tH\x01R\fauthorUserId\x88\x01\x01\x129\n" +
	"\acontent\x18\x05 \x01(\v2\x1f.types.v1.SessionMessageContentR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\t\n" +
	"\a_run_idB\x11\n" +
	"\x0f_author_user_id\"\xaf\x03\n" +
	"\x0fMemoryCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12$\n" +
	"\x0ecoding_task_id\x18\x03 \x01(\tR\fcodingTaskId\x12)\n" +
	"\x10proposed_content\x18\x04 \x01(\tR\x0fproposedContent\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12;\n" +
	"\vproposed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"proposedAt\x12\"\n" +
	"\n" +
	"decided_by\x18\a \x01(\tH\x00R\tdecidedBy\x88\x01\x01\x12>\n" +
	"\n" +
	"decided_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdecidedAt\x88\x01\x01\x123\n" +
	"\x13resulting_memory_id\x18\t \x01(\tH\x02R\x11resultingMemoryId\x88\x01\x01B\r\n" +
	"\v_decided_byB\r\n" +
	"\v_decided_atB\x16\n" +
	"\x14_resulting_memory_id\"\xaa\x03\n" +
	"\vAgentMemory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vapproved_by\x18\x04 \x01(\tR\n" +
	"approvedBy\x12)\n" +
	"\x0esource_task_id\x18\x05 \x01(\tH\x00R\fsourceTaskId\x88\x01\x01\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdeletedAt\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversionB\x11\n" +
	"\x0f_source_task_idB\r\n" +
	"\v_deleted_at2\xa8\x14\n" +
	"\x14CollaborationService\x12\xb2\x01\n" +
	"\x1bListCodingTaskLaunchOptions\x124.collaboration.v1.ListCodingTaskLaunchOptionsRequest\x1a5.collaboration.v1.ListCodingTaskLaunchOptionsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/coding-task-launch-options\x12\x80\x01\n" +
	"\x0fListCodingTasks\x12(.collaboration.v1.ListCodingTasksRequest\x1a).collaboration.v1.ListCodingTasksResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/coding-tasks\x12\xa2\x01\n" +
	"\x10CreateCodingTask\x12).collaboration.v1.CreateCodingTaskRequest\x1a*.collaboration.v1.CreateCodingTaskResponse\"7\x92A\x19r\x17\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/coding-tasks\x12y\n" +
	"\rGetCodingTask\x12&.collaboration.v1.GetCodingTaskRequest\x1a\x1c.collaboration.v1.CodingTask\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/coding-tasks/{task_id}\x12\xae\x01\n" +
	"\x10UpdateCodingTask\x12).collaboration.v1.UpdateCodingTaskRequest\x1a\x1c.collaboration.v1.CodingTask\"Q\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1f:\x01*2\x1a/v1/coding-tasks/{task_id}\x12\xc7\x01\n" +
	"\x12ContinueCodingTask\x12+.collaboration.v1.ContinueCodingTaskRequest\x1a,.collaboration.v1.ContinueCodingTaskResponse\"V\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/coding-tasks/{task_id}/runs\x12\x8c\x01\n" +
	"\x14GetCodingTaskSession\x12-.collaboration.v1.GetCodingTaskSessionRequest\x1a\x19.collaboration.v1.Session\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/coding-tasks/{task_id}/session\x12\xc1\x01\n" +
	"\x17UpdateCodingTaskSession\x120.collaboration.v1.UpdateCodingTaskSessionRequest\x1a\x19.collaboration.v1.Session\"Y\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02':\x01*2\"/v1/coding-tasks/{task_id}/session\x12\x9f\x01\n" +
	"\x13ListSessionMessages\x12,.collaboration.v1.ListSessionMessagesRequest\x1a-.collaboration.v1.ListSessionMessagesResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/coding-tasks/{task_id}/messages\x12\xab\x01\n" +
	"\x14ListMemoryCandidates\x12-.collaboration.v1.ListMemoryCandidatesRequest\x1a..collaboration.v1.ListMemoryCandidatesResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/coding-tasks/{task_id}/memory-candidates\x12\xc1\x01\n" +
	"\x16ProposeMemoryCandidate\x12/.collaboration.v1.ProposeMemoryCandidateRequest\x1a!.collaboration.v1.MemoryCandidate\"S\x92A\x19r\x17\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x021:\x01*\",/v1/coding-tasks/{task_id}/memory-candidates\x12\xc5\x01\n" +
	"\x15DecideMemoryCandidate\x12..collaboration.v1.DecideMemoryCandidateRequest\x1a/.collaboration.v1.DecideMemoryCandidateResponse\"K\x92A\x19r\x17\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x02):\x01*2$/v1/memory-candidates/{candidate_id}\x12\x94\x01\n" +
	"\x11ListAgentMemories\x12*.collaboration.v1.ListAgentMemoriesRequest\x1a+.collaboration.v1.ListAgentMemoriesResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/agents/{agent_id}/memories\x12\xb5\x01\n" +
	"\x11UpdateAgentMemory\x12*.collaboration.v1.UpdateAgentMemoryRequest\x1a\x1d.collaboration.v1.AgentMemory\"U\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02#:\x01*2\x1e/v1/agent-memories/{memory_id}\x12\xbe\x01\n" +
	"\x11DeleteAgentMemory\x12*.collaboration.v1.DeleteAgentMemoryRequest\x1a\x1d.collaboration.v1.AgentMemory\"^\x92A)r'\n" +
	"\x15\n" +
	"\x0fIdempotency-Key\x18\x01(\x01\n" +
	"\x0e\n" +
	"\bIf-Match\x18\x01(\x01\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/agent-memories/{memory_id}/deletionB=Z;agent-platform/backend/api/collaboration/v1;collaborationv1b\x06proto3"

var (
	file_collaboration_v1_collaboration_proto_rawDescOnce sync.Once
	file_collaboration_v1_collaboration_proto_rawDescData []byte
)

func file_collaboration_v1_collaboration_proto_rawDescGZIP() []byte {
	file_collaboration_v1_collaboration_proto_rawDescOnce.Do(func() {
		file_collaboration_v1_collaboration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collaboration_v1_collaboration_proto_rawDesc), len(file_collaboration_v1_collaboration_proto_rawDesc)))
	})
	return file_collaboration_v1_collaboration_proto_rawDescData
}

var file_collaboration_v1_collaboration_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_collaboration_v1_collaboration_proto_goTypes = []any{
	(*ListCodingTaskLaunchOptionsRequest)(nil),  // 0: collaboration.v1.ListCodingTaskLaunchOptionsRequest
	(*ListCodingTaskLaunchOptionsResponse)(nil), // 1: collaboration.v1.ListCodingTaskLaunchOptionsResponse
	(*CodingTaskLaunchOption)(nil),              // 2: collaboration.v1.CodingTaskLaunchOption
	(*ListCodingTasksRequest)(nil),              // 3: collaboration.v1.ListCodingTasksRequest
	(*ListCodingTasksResponse)(nil),             // 4: collaboration.v1.ListCodingTasksResponse
	(*CreateCodingTaskRequest)(nil),             // 5: collaboration.v1.CreateCodingTaskRequest
	(*CreateCodingTaskResponse)(nil),            // 6: collaboration.v1.CreateCodingTaskResponse
	(*GetCodingTaskRequest)(nil),                // 7: collaboration.v1.GetCodingTaskRequest
	(*GetCodingTaskResponse)(nil),               // 8: collaboration.v1.GetCodingTaskResponse
	(*UpdateCodingTaskRequest)(nil),             // 9: collaboration.v1.UpdateCodingTaskRequest
	(*UpdateCodingTaskResponse)(nil),            // 10: collaboration.v1.UpdateCodingTaskResponse
	(*ContinueCodingTaskRequest)(nil),           // 11: collaboration.v1.ContinueCodingTaskRequest
	(*ContinueCodingTaskResponse)(nil),          // 12: collaboration.v1.ContinueCodingTaskResponse
	(*GetCodingTaskSessionRequest)(nil),         // 13: collaboration.v1.GetCodingTaskSessionRequest
	(*GetCodingTaskSessionResponse)(nil),        // 14: collaboration.v1.GetCodingTaskSessionResponse
	(*UpdateCodingTaskSessionRequest)(nil),      // 15: collaboration.v1.UpdateCodingTaskSessionRequest
	(*UpdateCodingTaskSessionResponse)(nil),     // 16: collaboration.v1.UpdateCodingTaskSessionResponse
	(*ListSessionMessagesRequest)(nil),          // 17: collaboration.v1.ListSessionMessagesRequest
	(*ListSessionMessagesResponse)(nil),         // 18: collaboration.v1.ListSessionMessagesResponse
	(*ListMemoryCandidatesRequest)(nil),         // 19: collaboration.v1.ListMemoryCandidatesRequest
	(*ListMemoryCandidatesResponse)(nil),        // 20: collaboration.v1.ListMemoryCandidatesResponse
	(*ProposeMemoryCandidateRequest)(nil),       // 21: collaboration.v1.ProposeMemoryCandidateRequest
	(*ProposeMemoryCandidateResponse)(nil),      // 22: collaboration.v1.ProposeMemoryCandidateResponse
	(*DecideMemoryCandidateRequest)(nil),        // 23: collaboration.v1.DecideMemoryCandidateRequest
	(*DecideMemoryCandidateResponse)(nil),       // 24: collaboration.v1.DecideMemoryCandidateResponse
	(*ListAgentMemoriesRequest)(nil),            // 25: collaboration.v1.ListAgentMemoriesRequest
	(*ListAgentMemoriesResponse)(nil),           // 26: collaboration.v1.ListAgentMemoriesResponse
	(*UpdateAgentMemoryRequest)(nil),            // 27: collaboration.v1.UpdateAgentMemoryRequest
	(*UpdateAgentMemoryResponse)(nil),           // 28: collaboration.v1.UpdateAgentMemoryResponse
	(*DeleteAgentMemoryRequest)(nil),            // 29: collaboration.v1.DeleteAgentMemoryRequest
	(*DeleteAgentMemoryResponse)(nil),           // 30: collaboration.v1.DeleteAgentMemoryResponse
	(*CodingTask)(nil),                          // 31: collaboration.v1.CodingTask
	(*Session)(nil),                             // 32: collaboration.v1.Session
	(*SessionMessage)(nil),                      // 33: collaboration.v1.SessionMessage
	(*MemoryCandidate)(nil),                     // 34: collaboration.v1.MemoryCandidate
	(*AgentMemory)(nil),                         // 35: collaboration.v1.AgentMemory
	(*v1.IssueSnapshot)(nil),                    // 36: types.v1.IssueSnapshot
	(*v1.SessionMemory)(nil),                    // 37: types.v1.SessionMemory
	(*timestamppb.Timestamp)(nil),               // 38: google.protobuf.Timestamp
	(*v1.SessionMessageContent)(nil),            // 39: types.v1.SessionMessageContent
}
var file_collaboration_v1_collaboration_proto_depIdxs = []int32{
	2,  // 0: collaboration.v1.ListCodingTaskLaunchOptionsResponse.items:type_name -> collaboration.v1.CodingTaskLaunchOption
	31, // 1: collaboration.v1.ListCodingTasksResponse.items:type_name -> collaboration.v1.CodingTask
	36, // 2: collaboration.v1.CreateCodingTaskRequest.issue_snapshot:type_name -> types.v1.IssueSnapshot
	31, // 3: collaboration.v1.CreateCodingTaskResponse.task:type_name -> collaboration.v1.CodingTask
	32, // 4: collaboration.v1.CreateCodingTaskResponse.session:type_name -> collaboration.v1.Session
	31, // 5: collaboration.v1.GetCodingTaskResponse.task:type_name -> collaboration.v1.CodingTask
	31, // 6: collaboration.v1.UpdateCodingTaskResponse.task:type_name -> collaboration.v1.CodingTask
	31, // 7: collaboration.v1.ContinueCodingTaskResponse.task:type_name -> collaboration.v1.CodingTask
	32, // 8: collaboration.v1.ContinueCodingTaskResponse.session:type_name -> collaboration.v1.Session
	32, // 9: collaboration.v1.GetCodingTaskSessionResponse.session:type_name -> collaboration.v1.Session
	37, // 10: collaboration.v1.UpdateCodingTaskSessionRequest.memory:type_name -> types.v1.SessionMemory
	32, // 11: collaboration.v1.UpdateCodingTaskSessionResponse.session:type_name -> collaboration.v1.Session
	33, // 12: collaboration.v1.ListSessionMessagesResponse.items:type_name -> collaboration.v1.SessionMessage
	34, // 13: collaboration.v1.ListMemoryCandidatesResponse.items:type_name -> collaboration.v1.MemoryCandidate
	34, // 14: collaboration.v1.ProposeMemoryCandidateResponse.candidate:type_name -> collaboration.v1.MemoryCandidate
	34, // 15: collaboration.v1.DecideMemoryCandidateResponse.candidate:type_name -> collaboration.v1.MemoryCandidate
	35, // 16: collaboration.v1.DecideMemoryCandidateResponse.memory:type_name -> collaboration.v1.AgentMemory
	35, // 17: collaboration.v1.ListAgentMemoriesResponse.items:type_name -> collaboration.v1.AgentMemory
	35, // 18: collaboration.v1.UpdateAgentMemoryResponse.memory:type_name -> collaboration.v1.AgentMemory
	35, // 19: collaboration.v1.DeleteAgentMemoryResponse.memory:type_name -> collaboration.v1.AgentMemory
	36, // 20: collaboration.v1.CodingTask.issue_snapshot:type_name -> types.v1.IssueSnapshot
	38, // 21: collaboration.v1.CodingTask.created_at:type_name -> google.protobuf.Timestamp
	38, // 22: collaboration.v1.CodingTask.updated_at:type_name -> google.protobuf.Timestamp
	38, // 23: collaboration.v1.CodingTask.completed_at:type_name -> google.protobuf.Timestamp
	37, // 24: collaboration.v1.Session.memory:type_name -> types.v1.SessionMemory
	38, // 25: collaboration.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	38, // 26: collaboration.v1.Session.updated_at:type_name -> google.protobuf.Timestamp
	39, // 27: collaboration.v1.SessionMessage.content:type_name -> types.v1.SessionMessageContent
	38, // 28: collaboration.v1.SessionMessage.created_at:type_name -> google.protobuf.Timestamp
	38, // 29: collaboration.v1.MemoryCandidate.proposed_at:type_name -> google.protobuf.Timestamp
	38, // 30: collaboration.v1.MemoryCandidate.decided_at:type_name -> google.protobuf.Timestamp
	38, // 31: collaboration.v1.AgentMemory.created_at:type_name -> google.protobuf.Timestamp
	38, // 32: collaboration.v1.AgentMemory.updated_at:type_name -> google.protobuf.Timestamp
	38, // 33: collaboration.v1.AgentMemory.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 34: collaboration.v1.CollaborationService.ListCodingTaskLaunchOptions:input_type -> collaboration.v1.ListCodingTaskLaunchOptionsRequest
	3,  // 35: collaboration.v1.CollaborationService.ListCodingTasks:input_type -> collaboration.v1.ListCodingTasksRequest
	5,  // 36: collaboration.v1.CollaborationService.CreateCodingTask:input_type -> collaboration.v1.CreateCodingTaskRequest
	7,  // 37: collaboration.v1.CollaborationService.GetCodingTask:input_type -> collaboration.v1.GetCodingTaskRequest
	9,  // 38: collaboration.v1.CollaborationService.UpdateCodingTask:input_type -> collaboration.v1.UpdateCodingTaskRequest
	11, // 39: collaboration.v1.CollaborationService.ContinueCodingTask:input_type -> collaboration.v1.ContinueCodingTaskRequest
	13, // 40: collaboration.v1.CollaborationService.GetCodingTaskSession:input_type -> collaboration.v1.GetCodingTaskSessionRequest
	15, // 41: collaboration.v1.CollaborationService.UpdateCodingTaskSession:input_type -> collaboration.v1.UpdateCodingTaskSessionRequest
	17, // 42: collaboration.v1.CollaborationService.ListSessionMessages:input_type -> collaboration.v1.ListSessionMessagesRequest
	19, // 43: collaboration.v1.CollaborationService.ListMemoryCandidates:input_type -> collaboration.v1.ListMemoryCandidatesRequest
	21, // 44: collaboration.v1.CollaborationService.ProposeMemoryCandidate:input_type -> collaboration.v1.ProposeMemoryCandidateRequest
	23, // 45: collaboration.v1.CollaborationService.DecideMemoryCandidate:input_type -> collaboration.v1.DecideMemoryCandidateRequest
	25, // 46: collaboration.v1.CollaborationService.ListAgentMemories:input_type -> collaboration.v1.ListAgentMemoriesRequest
	27, // 47: collaboration.v1.CollaborationService.UpdateAgentMemory:input_type -> collaboration.v1.UpdateAgentMemoryRequest
	29, // 48: collaboration.v1.CollaborationService.DeleteAgentMemory:input_type -> collaboration.v1.DeleteAgentMemoryRequest
	1,  // 49: collaboration.v1.CollaborationService.ListCodingTaskLaunchOptions:output_type -> collaboration.v1.ListCodingTaskLaunchOptionsResponse
	4,  // 50: collaboration.v1.CollaborationService.ListCodingTasks:output_type -> collaboration.v1.ListCodingTasksResponse
	6,  // 51: collaboration.v1.CollaborationService.CreateCodingTask:output_type -> collaboration.v1.CreateCodingTaskResponse
	31, // 52: collaboration.v1.CollaborationService.GetCodingTask:output_type -> collaboration.v1.CodingTask
	31, // 53: collaboration.v1.CollaborationService.UpdateCodingTask:output_type -> collaboration.v1.CodingTask
	12, // 54: collaboration.v1.CollaborationService.ContinueCodingTask:output_type -> collaboration.v1.ContinueCodingTaskResponse
	32, // 55: collaboration.v1.CollaborationService.GetCodingTaskSession:output_type -> collaboration.v1.Session
	32, // 56: collaboration.v1.CollaborationService.UpdateCodingTaskSession:output_type -> collaboration.v1.Session
	18, // 57: collaboration.v1.CollaborationService.ListSessionMessages:output_type -> collaboration.v1.ListSessionMessagesResponse
	20, // 58: collaboration.v1.CollaborationService.ListMemoryCandidates:output_type -> collaboration.v1.ListMemoryCandidatesResponse
	34, // 59: collaboration.v1.CollaborationService.ProposeMemoryCandidate:output_type -> collaboration.v1.MemoryCandidate
	24, // 60: collaboration.v1.CollaborationService.DecideMemoryCandidate:output_type -> collaboration.v1.DecideMemoryCandidateResponse
	26, // 61: collaboration.v1.CollaborationService.ListAgentMemories:output_type -> collaboration.v1.ListAgentMemoriesResponse
	35, // 62: collaboration.v1.CollaborationService.UpdateAgentMemory:output_type -> collaboration.v1.AgentMemory
	35, // 63: collaboration.v1.CollaborationService.DeleteAgentMemory:output_type -> collaboration.v1.AgentMemory
	49, // [49:64] is the sub-list for method output_type
	34, // [34:49] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_collaboration_v1_collaboration_proto_init() }
func file_collaboration_v1_collaboration_proto_init() {
	if File_collaboration_v1_collaboration_proto != nil {
		return
	}
	file_collaboration_v1_collaboration_proto_msgTypes[5].OneofWrappers = []any{}
	file_collaboration_v1_collaboration_proto_msgTypes[17].OneofWrappers = []any{}
	file_collaboration_v1_collaboration_proto_msgTypes[24].OneofWrappers = []any{}
	file_collaboration_v1_collaboration_proto_msgTypes[25].OneofWrappers = []any{}
	file_collaboration_v1_collaboration_proto_msgTypes[31].OneofWrappers = []any{}
	file_collaboration_v1_collaboration_proto_msgTypes[33].OneofWrappers = []any{}
	file_collaboration_v1_collaboration_proto_msgTypes[34].OneofWrappers = []any{}
	file_collaboration_v1_collaboration_proto_msgTypes[35].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collaboration_v1_collaboration_proto_rawDesc), len(file_collaboration_v1_collaboration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collaboration_v1_collaboration_proto_goTypes,
		DependencyIndexes: file_collaboration_v1_collaboration_proto_depIdxs,
		MessageInfos:      file_collaboration_v1_collaboration_proto_msgTypes,
	}.Build()
	File_collaboration_v1_collaboration_proto = out.File
	file_collaboration_v1_collaboration_proto_goTypes = nil
	file_collaboration_v1_collaboration_proto_depIdxs = nil
}
