// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: audit/v1/audit.proto

package auditv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAuditEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Action        *string                `protobuf:"bytes,2,opt,name=action,proto3,oneof" json:"action,omitempty"`
	ResourceType  *string                `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3,oneof" json:"resource_type,omitempty"`
	ResourceId    *string                `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3,oneof" json:"resource_id,omitempty"`
	ActorUserId   *string                `protobuf:"bytes,5,opt,name=actor_user_id,json=actorUserId,proto3,oneof" json:"actor_user_id,omitempty"`
	CreatedFrom   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_from,json=createdFrom,proto3,oneof" json:"created_from,omitempty"`
	CreatedTo     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_to,json=createdTo,proto3,oneof" json:"created_to,omitempty"`
	Limit         *int32                 `protobuf:"varint,8,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Outcome       *string                `protobuf:"bytes,9,opt,name=outcome,proto3,oneof" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEventsRequest) Reset() {
	*x = ListAuditEventsRequest{}
	mi := &file_audit_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsRequest) ProtoMessage() {}

func (x *ListAuditEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsRequest) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *ListAuditEventsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListAuditEventsRequest) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *ListAuditEventsRequest) GetResourceType() string {
	if x != nil && x.ResourceType != nil {
		return *x.ResourceType
	}
	return ""
}

func (x *ListAuditEventsRequest) GetResourceId() string {
	if x != nil && x.ResourceId != nil {
		return *x.ResourceId
	}
	return ""
}

func (x *ListAuditEventsRequest) GetActorUserId() string {
	if x != nil && x.ActorUserId != nil {
		return *x.ActorUserId
	}
	return ""
}

func (x *ListAuditEventsRequest) GetCreatedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedFrom
	}
	return nil
}

func (x *ListAuditEventsRequest) GetCreatedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTo
	}
	return nil
}

func (x *ListAuditEventsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListAuditEventsRequest) GetOutcome() string {
	if x != nil && x.Outcome != nil {
		return *x.Outcome
	}
	return ""
}

type ListAuditEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AuditEvent          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEventsResponse) Reset() {
	*x = ListAuditEventsResponse{}
	mi := &file_audit_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsResponse) ProtoMessage() {}

func (x *ListAuditEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditEventsResponse) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditEventsResponse) GetItems() []*AuditEvent {
	if x != nil {
		return x.Items
	}
	return nil
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ActorUserId   *string                `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3,oneof" json:"actor_user_id,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Outcome       string                 `protobuf:"bytes,9,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_audit_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditEvent) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AuditEvent) GetActorUserId() string {
	if x != nil && x.ActorUserId != nil {
		return *x.ActorUserId
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditEvent) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *AuditEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

var File_audit_v1_audit_proto protoreflect.FileDescriptor

const file_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x14audit/v1/audit.proto\x12\baudit.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x03\n" +
	"\x16ListAuditEventsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1b\n" +
	"\x06action\x18\x02 \x01(\tH\x00R\x06action\x88\x01\x01\x12(\n" +
	"\rresource_type\x18\x03 \x01(\tH\x01R\fresourceType\x88\x01\x01\x12$\n" +
	"\vresource_id\x18\x04 \x01(\tH\x02R\n" +
	"resourceId\x88\x01\x01\x12'\n" +
	"\ractor_user_id\x18\x05 \x01(\tH\x03R\vactorUserId\x88\x01\x01\x12B\n" +
	"\fcreated_from\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vcreatedFrom\x88\x01\x01\x12>\n" +
	"\n" +
	"created_to\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x05R\tcreatedTo\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\b \x01(\x05H\x06R\x05limit\x88\x01\x01\x12\x1d\n" +
	"\aoutcome\x18\t \x01(\tH\aR\aoutcome\x88\x01\x01B\t\n" +
	"\a_actionB\x10\n" +
	"\x0e_resource_typeB\x0e\n" +
	"\f_resource_idB\x10\n" +
	"\x0e_actor_user_idB\x0f\n" +
	"\r_created_fromB\r\n" +
	"\v_created_toB\b\n" +
	"\x06_limitB\n" +
	"\n" +
	"\b_outcome\"E\n" +
	"\x17ListAuditEventsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.audit.v1.AuditEventR\x05items\"\xd6\x02\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12'\n" +
	"\ractor_user_id\x18\x03 \x01(\tH\x00R\vactorUserId\x88\x01\x01\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x06 \x01(\tR\n" +
	"resourceId\x121\n" +
	"\adetails\x18\a \x01(\v2\x17.google.protobuf.StructR\adetails\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\aoutcome\x18\t \x01(\tR\aoutcomeB\x10\n" +
	"\x0e_actor_user_id2\x80\x01\n" +
	"\fAuditService\x12p\n" +
	"\x0fListAuditEvents\x12 .audit.v1.ListAuditEventsRequest\x1a!.audit.v1.ListAuditEventsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/audit-eventsB-Z+agent-platform/backend/api/audit/v1;auditv1b\x06proto3"

var (
	file_audit_v1_audit_proto_rawDescOnce sync.Once
	file_audit_v1_audit_proto_rawDescData []byte
)

func file_audit_v1_audit_proto_rawDescGZIP() []byte {
	file_audit_v1_audit_proto_rawDescOnce.Do(func() {
		file_audit_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_v1_audit_proto_rawDesc), len(file_audit_v1_audit_proto_rawDesc)))
	})
	return file_audit_v1_audit_proto_rawDescData
}

var file_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_audit_v1_audit_proto_goTypes = []any{
	(*ListAuditEventsRequest)(nil),  // 0: audit.v1.ListAuditEventsRequest
	(*ListAuditEventsResponse)(nil), // 1: audit.v1.ListAuditEventsResponse
	(*AuditEvent)(nil),              // 2: audit.v1.AuditEvent
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 4: google.protobuf.Struct
}
var file_audit_v1_audit_proto_depIdxs = []int32{
	3, // 0: audit.v1.ListAuditEventsRequest.created_from:type_name -> google.protobuf.Timestamp
	3, // 1: audit.v1.ListAuditEventsRequest.created_to:type_name -> google.protobuf.Timestamp
	2, // 2: audit.v1.ListAuditEventsResponse.items:type_name -> audit.v1.AuditEvent
	4, // 3: audit.v1.AuditEvent.details:type_name -> google.protobuf.Struct
	3, // 4: audit.v1.AuditEvent.created_at:type_name -> google.protobuf.Timestamp
	0, // 5: audit.v1.AuditService.ListAuditEvents:input_type -> audit.v1.ListAuditEventsRequest
	1, // 6: audit.v1.AuditService.ListAuditEvents:output_type -> audit.v1.ListAuditEventsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_audit_v1_audit_proto_init() }
func file_audit_v1_audit_proto_init() {
	if File_audit_v1_audit_proto != nil {
		return
	}
	file_audit_v1_audit_proto_msgTypes[0].OneofWrappers = []any{}
	file_audit_v1_audit_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_v1_audit_proto_rawDesc), len(file_audit_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_v1_audit_proto_goTypes,
		DependencyIndexes: file_audit_v1_audit_proto_depIdxs,
		MessageInfos:      file_audit_v1_audit_proto_msgTypes,
	}.Build()
	File_audit_v1_audit_proto = out.File
	file_audit_v1_audit_proto_goTypes = nil
	file_audit_v1_audit_proto_depIdxs = nil
}
