import { createI18n } from "vue-i18n";

export type SupportedLocale = "zh-CN" | "en-US";
export const localeStorageKey = "agent-workspace-locale";

const zh = {
  product: "Agent Workspace", nav: { sessions: "会话", workflows: "工作流", experts: "专家", settings: "设置", users: "账号管理" },
  auth: { checking: "正在连接工作空间", required: "登录后开始使用", body: "你的会话、工作流和扩展均为私有空间。", signIn: "登录", unavailable: "身份服务暂时不可用", signOut: "退出登录", online: "API 在线", offline: "API 离线", checkingApi: "正在检查 API" },
  common: { new: "新增", edit: "编辑", name: "名称", save: "保存", saving: "保存中…", cancel: "取消", delete: "删除", archive: "归档", unarchive: "取消归档", rename: "重命名", loading: "加载中…", empty: "这里还没有内容", close: "关闭", retry: "重试", run: "运行", running: "运行中", success: "成功", failed: "失败", queued: "排队中", copied: "已复制", copy: "复制", back: "返回", comingSoon: "即将开放", readOnly: "只读", upload: "上传", download: "下载", folder: "文件夹", enabled: "已启用" },
  sessions: { title: "会话", subtitle: "与专家或默认助手持续对话", new: "新建会话", archived: "已归档", active: "当前会话", chooseExpert: "选择专家（可选）", noExpert: "不选择专家", placeholder: "输入消息，Enter 发送，Shift + Enter 换行", welcome: "从一个问题开始。首条消息发送后，专家配置会冻结到本会话。", elapsed: "用时 {value}", jumpToLatest: "回到最新消息", copyQuestion: "复制当前问题", copyAnswer: "复制当前回答", thinking: "思考中", stopGeneration: "中止生成", stopping: "正在中止…", cancelled: "已中止生成", modelSelector: "选择本会话使用的模型", modelUnverified: "此模型与当前 Runtime 尚未验证", deleteTitle: "删除这个会话？", deleteDescription: "删除后，这段对话及其全部消息将从你的工作空间中永久移除。", deleteTarget: "即将删除", deleteWarning: "此操作无法撤销", deleteConfirm: "删除会话", deleting: "正在删除…", deleteAction: "删除会话 {title}", progress: { preparing: "正在准备运行环境", thinking: "正在分析问题", using_tool: "正在调用工具", working: "正在处理结果", responding: "正在组织答案" }, setupTitle: "开始前完成 3 个步骤", setupModel: "连接模型供应商并选择默认模型", setupRuntime: "选择可用 Runtime", setupStart: "开始会话或工作流" },
  workflows: { title: "工作流", subtitle: "把一个目标变成可重复、可调度、可通过 API 调用的执行单元", new: "新建工作流", name: "名称", goal: "目标", expert: "专家（可选）", runtime: "Runtime 引擎", model: "模型", open: "打开工作流", artifacts: "产物", workspace: "工作空间", history: "运行记录", settings: "设置", trigger: "触发方式", state: "状态", duration: "耗时", started: "运行时间", manual: "手动触发", scheduled: "自动触发", api: "API 调用", noRuns: "还没有运行记录", runNow: "立即运行", input: "本次补充输入（可选）", deletedRecords: "已删除记录", basic: "基本信息", execution: "执行设置", schedule: "定时触发", enableSchedule: "启用定时触发", frequency: "频率", hourly: "每小时", daily: "每天", weekly: "每周", hour: "小时", minute: "分钟", weekday: "星期", timezone: "时区", apiCredential: "API 凭证", generate: "生成", regenerate: "重新生成", copySecret: "请立即复制，Secret 不会再次显示。", gitSource: "Git 来源", gitDescription: "将公共 HTTPS 或私有 SSH 仓库克隆到空工作空间。", openWorkspace: "打开工作空间", deleteTitle: "删除工作流", deleteDescription: "配置、定时任务、凭证和工作空间会被删除，运行记录保留为只读。", queuedAt: "排队时间", startedAt: "开始时间", endedAt: "结束时间", inputLabel: "输入", eventsLabel: "事件与日志", runArtifacts: "本次运行产物", noRunArtifacts: "本次运行没有产物", snapshotLabel: "工作流快照", resultLabel: "结果", expired: "已过期", clearWorkspace: "清空工作空间", directoryName: "目录名称", gitURL: "Git URL（公共 HTTPS 或私有 SSH）", branch: "分支", privateKey: "SSH 私钥（保存后不可查看）", personalDefault: "个人默认", environment: "环境变量" },
  experts: { title: "专家", subtitle: "组合 MCP 与 Skills；描述仅用于展示，不会偷偷进入提示词", new: "创建专家", name: "专家名称", description: "描述", mcp: "MCP", skills: "Skills", noBindings: "未绑定扩展", descriptionHint: "仅用于展示，不会注入模型指令。", tested: "已测试", testRequired: "需要测试" },
  settings: { title: "设置", subtitle: "定义你的默认个性、模型、Runtime 与扩展", personality: "个性", gentle: "温和专业", direct: "直接高效", lively: "活泼亲切", custom: "自定义", instructions: "个性说明", model: "模型设置", providers: "模型供应商", provider: "供应商", addProvider: "添加供应商", providerSaved: "模型供应商已保存", providerSaveFailed: "保存失败，请检查 Endpoint、API Key 和 API 协议后重试。", protocols: "API 协议", importedModels: "个已导入模型", refreshModels: "刷新模型", manualModel: "手动添加模型", modelCatalog: "模型目录", modelType: "模型类型", runtimeModels: "各 Runtime 默认模型", verified: "已验证", unverified: "未验证", failed: "验证失败", runtime: "Runtime 引擎", extensions: "扩展", mcp: "MCP 管理", skills: "Skills 管理", cli: "第三方 CLI", language: "语言", timezone: "时区", addModel: "新增模型", endpoint: "Endpoint", secret: "API Secret（保存后不可查看）", modelId: "模型 ID", default: "默认", testPending: "测试中", tested: "已测试", testRequired: "需要测试", saved: "设置已保存", secretSet: "Secret 已配置", secretMissing: "缺少 Secret", keepSecret: "留空则保留现有 API Key", transport: "传输方式", bearerToken: "Bearer Token（可选）", optional: "可选", fixedVersion: "固定版本", arguments: "参数", onePerLine: "每行一个参数", value: "值", environment: "环境变量", source: "来源", skillHint: "Skill 根目录必须包含 SKILL.md；每次运行都会冻结精确版本。", available: "可用", unavailable: "不可用" },
  modelField: "模型",
  users: { title: "账号管理", subtitle: "创建普通账号、停用账号或重置临时密码", create: "创建账号", username: "用户名", displayName: "显示名称", email: "邮箱", enabled: "已启用", disabled: "已停用", reset: "重置密码", temporary: "临时密码仅显示一次", forceChange: "用户首次登录时必须修改密码", user: "用户", status: "状态", created: "创建时间", administrator: "管理员" },
  errors: { generic: "操作没有完成，请稍后重试。", conflict: "内容已被其他操作更新，请刷新后重试。", validation: "请检查填写内容。", copy: "复制失败，请检查浏览器剪贴板权限。" },
};

const en = {
  product: "Agent Workspace", nav: { sessions: "Sessions", workflows: "Workflows", experts: "Experts", settings: "Settings", users: "User accounts" },
  auth: { checking: "Connecting to your workspace", required: "Sign in to continue", body: "Your sessions, workflows, and extensions stay in your private workspace.", signIn: "Sign in", unavailable: "Identity service is unavailable", signOut: "Sign out", online: "API online", offline: "API offline", checkingApi: "Checking API" },
  common: { new: "New", edit: "Edit", name: "Name", save: "Save", saving: "Saving…", cancel: "Cancel", delete: "Delete", archive: "Archive", unarchive: "Unarchive", rename: "Rename", loading: "Loading…", empty: "Nothing here yet", close: "Close", retry: "Retry", run: "Run", running: "Running", success: "Succeeded", failed: "Failed", queued: "Queued", copied: "Copied", copy: "Copy", back: "Back", comingSoon: "Coming soon", readOnly: "Read only", upload: "Upload", download: "Download", folder: "Folder", enabled: "Enabled" },
  sessions: { title: "Sessions", subtitle: "Keep a conversation going with an Expert or your default assistant", new: "New session", archived: "Archived", active: "Current sessions", chooseExpert: "Choose an Expert (optional)", noExpert: "No Expert", placeholder: "Message your workspace — Enter to send, Shift + Enter for a new line", welcome: "Start with a question. Expert configuration freezes after the first message.", elapsed: "{value} elapsed", jumpToLatest: "Jump to latest message", copyQuestion: "Copy this question", copyAnswer: "Copy this answer", thinking: "Thinking", stopGeneration: "Stop generating", stopping: "Stopping…", cancelled: "Generation stopped", modelSelector: "Choose the model for this Session", modelUnverified: "This model and Runtime have not been verified", deleteTitle: "Delete this session?", deleteDescription: "This conversation and every message in it will be permanently removed from your workspace.", deleteTarget: "About to delete", deleteWarning: "This action cannot be undone", deleteConfirm: "Delete session", deleting: "Deleting…", deleteAction: "Delete session {title}", progress: { preparing: "Preparing the runtime", thinking: "Analyzing your request", using_tool: "Using a tool", working: "Processing the result", responding: "Composing the answer" }, setupTitle: "Complete three steps to start", setupModel: "Connect a model provider and choose a default", setupRuntime: "Select an available Runtime", setupStart: "Start a Session or Workflow" },
  workflows: { title: "Workflows", subtitle: "Turn one goal into an execution you can repeat, schedule, or call by API", new: "New workflow", name: "Name", goal: "Goal", expert: "Expert (optional)", runtime: "Runtime engine", model: "Model", open: "Open workflow", artifacts: "Artifacts", workspace: "Workspace", history: "Run history", settings: "Settings", trigger: "Trigger", state: "State", duration: "Duration", started: "Run time", manual: "Manual", scheduled: "Scheduled", api: "API", noRuns: "No runs yet", runNow: "Run now", input: "Optional input for this run", deletedRecords: "Deleted records", basic: "Basic", execution: "Execution", schedule: "Schedule", enableSchedule: "Enable schedule", frequency: "Frequency", hourly: "Hourly", daily: "Daily", weekly: "Weekly", hour: "Hour", minute: "Minute", weekday: "Weekday", timezone: "Timezone", apiCredential: "API credential", generate: "Generate", regenerate: "Regenerate", copySecret: "Copy now. The secret will not be shown again.", gitSource: "Git source", gitDescription: "Clone a public HTTPS or private SSH repository into an empty Workspace.", openWorkspace: "Open Workspace", deleteTitle: "Delete workflow", deleteDescription: "Configuration, schedule, credential, and Workspace are removed. Run history remains read-only.", queuedAt: "Queued", startedAt: "Started", endedAt: "Ended", inputLabel: "Input", eventsLabel: "Events and logs", runArtifacts: "Artifacts from this run", noRunArtifacts: "This run did not produce artifacts", snapshotLabel: "Workflow snapshot", resultLabel: "Result", expired: "Expired", clearWorkspace: "Clear Workspace", directoryName: "Directory name", gitURL: "Git URL (public HTTPS or private SSH)", branch: "Branch", privateKey: "Private SSH key (write-only)", personalDefault: "Personal default", environment: "Environment variable" },
  experts: { title: "Experts", subtitle: "Compose MCP and Skills. Descriptions are display-only and never silently become prompts.", new: "Create Expert", name: "Expert name", description: "Description", mcp: "MCP", skills: "Skills", noBindings: "No extensions bound", descriptionHint: "Display only — not injected into model instructions.", tested: "Tested", testRequired: "Test required" },
  settings: { title: "Settings", subtitle: "Choose your default personality, model, Runtime, and extensions", personality: "Personality", gentle: "Gentle & professional", direct: "Direct & efficient", lively: "Lively & friendly", custom: "Custom", instructions: "Personality instructions", model: "Models", providers: "Model providers", provider: "Provider", addProvider: "Add provider", providerSaved: "Model provider saved", providerSaveFailed: "Save failed. Check the Endpoint, API Key, and API protocols, then retry.", protocols: "API protocols", importedModels: "imported models", refreshModels: "Refresh models", manualModel: "Add model manually", modelCatalog: "Model catalog", modelType: "Model type", runtimeModels: "Default model for each Runtime", verified: "Verified", unverified: "Unverified", failed: "Verification failed", runtime: "Runtime engine", extensions: "Extensions", mcp: "MCP management", skills: "Skills management", cli: "Third-party CLI", language: "Language", timezone: "Timezone", addModel: "Add model", endpoint: "Endpoint", secret: "API Secret (write-only)", modelId: "Model ID", default: "Default", testPending: "Testing", tested: "Tested", testRequired: "Test required", saved: "Settings saved", secretSet: "Secret configured", secretMissing: "Secret missing", keepSecret: "Leave blank to keep the existing API Key", transport: "Transport", bearerToken: "Bearer token (optional)", optional: "Optional", fixedVersion: "Pinned version", arguments: "Arguments", onePerLine: "One argument per line", value: "Value", environment: "Environment variable", source: "Source", skillHint: "The Skill root must contain SKILL.md; every Run freezes the exact version.", available: "available", unavailable: "unavailable" },
  modelField: "Model",
  users: { title: "User accounts", subtitle: "Create, disable, or reset ordinary user accounts", create: "Create account", username: "Username", displayName: "Display name", email: "Email", enabled: "Enabled", disabled: "Disabled", reset: "Reset password", temporary: "Temporary password is shown once", forceChange: "The user must change it on first sign-in", user: "User", status: "Status", created: "Created", administrator: "Administrator" },
  errors: { generic: "The operation did not complete. Try again.", conflict: "This content changed elsewhere. Refresh and retry.", validation: "Check the entered values.", copy: "Copy failed. Check the browser clipboard permission." },
};

Object.assign(zh.common, { send: "发送" });
Object.assign(zh.workflows, { conversation: "运行对话", followUpPlaceholder: "继续对话，Enter 发送，Shift + Enter 换行" });
Object.assign(zh.sessions, { addAttachment: "添加图片或文件", removeAttachment: "移除附件 {name}", attachmentLimits: "每条消息最多 10 个附件，单个附件不能超过 100 MB" });
Object.assign(zh.sessions.progress, { finalizing: "正在安全保存会话" });
Object.assign(en.common, { send: "Send" });
Object.assign(en.workflows, { conversation: "Run conversation", followUpPlaceholder: "Continue the conversation — Enter to send, Shift + Enter for a new line" });
Object.assign(en.sessions, { addAttachment: "Attach images or files", removeAttachment: "Remove attachment {name}", attachmentLimits: "Up to 10 attachments per message, 100 MB each" });
Object.assign(en.sessions.progress, { finalizing: "Saving the session securely" });

export function resolveInitialLocale(stored: string | null, browserLanguage: string): SupportedLocale {
  if (stored === "zh-CN" || stored === "en-US") return stored;
  return browserLanguage.toLowerCase().startsWith("zh") ? "zh-CN" : "en-US";
}

export function createAppI18n(storage: Pick<Storage, "getItem"> = localStorage, browserLanguage = navigator.language) {
  const locale = resolveInitialLocale(storage.getItem(localeStorageKey), browserLanguage);
  document.documentElement.lang = locale;
  return createI18n({ legacy: false, locale, fallbackLocale: "en-US", messages: { "zh-CN": zh, "en-US": en } });
}

export function formatDuration(milliseconds: number, locale: SupportedLocale): string {
  const seconds = Math.max(0, Math.round(milliseconds / 1000));
  if (seconds < 60) return new Intl.NumberFormat(locale, { style: "unit", unit: "second", unitDisplay: "short" }).format(seconds);
  return new Intl.NumberFormat(locale, { style: "unit", unit: "minute", unitDisplay: "short" }).format(Math.round(seconds / 60));
}
